// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AgeBand
 *
 * The reading age band a story targets.
 */
export type AgeBand = '3-5' | '5-8' | '8-11' | '10-13' | '13-16' | '16+';

/**
 * AllowlistCreateBody
 *
 * POST body to add a new allowlist row.
 */
export type AllowlistCreateBody = {
    /**
     * Provider
     */
    provider: 'anthropic' | 'openrouter' | 'modal' | 'ollama';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * AllowlistListView
 *
 * The whole allowlist table, ordered by (provider, model_id).
 */
export type AllowlistListView = {
    /**
     * Rows
     */
    rows: Array<AllowlistView>;
};

/**
 * AllowlistUpdateBody
 *
 * PUT body: full replace of the mutable fields (mirrors ThresholdUpsertBody).
 */
export type AllowlistUpdateBody = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * AllowlistView
 *
 * One provider/model allowlist row.
 */
export type AllowlistView = {
    /**
     * Id
     */
    id: string;
    /**
     * Provider
     */
    provider: 'anthropic' | 'openrouter' | 'modal' | 'ollama';
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Display Name
     */
    display_name: string | null;
};

/**
 * AlternativeView
 *
 * One in-cell, production-eligible skeleton the admin could pick instead.
 */
export type AlternativeView = {
    /**
     * Slug
     */
    slug: string;
};

/**
 * AnchorContext
 *
 * Soft-continuation context extracted from a series anchor storybook.
 *
 * Deterministic extraction, not an LLM summary (WS-B PR 3, decision B2): the
 * anchor document's title, the protagonist name recovered from the anchor's
 * concept brief, and truncated ending excerpts. Serialized into the Stage A
 * prompt with the rest of the brief (build_structure_prompt injects
 * ``model_dump_json`` wholesale), so the generated book can follow on
 * thematically without embedding document-level Series metadata (SR-1..SR-7
 * stay dormant until WS-G).
 *
 * ``variable_names`` (WS-G PR 3, decision G3) lists the anchor's declared
 * story-state variable names, read from the published blob's top-level
 * ``variables`` array. The structure prompt instructs the generator to reuse
 * these exact names where the continuation tracks the same state; the
 * reader's name-matched var-state seeding (spec section 4, PR 2) only
 * carries state when the names match.
 */
export type AnchorContext = {
    /**
     * Title
     */
    title: string;
    /**
     * Character Names
     */
    character_names?: Array<string>;
    /**
     * Ending Summary
     */
    ending_summary?: string;
    /**
     * Variable Names
     */
    variable_names?: Array<string>;
};

/**
 * ApproveBody
 *
 * Optional approve-time release options (WS-E decision E2).
 *
 * ``visibility`` defaults to ``family`` so an approve with no body keeps the
 * pre-WS-E behavior; ``catalog`` shares the book with every family.
 */
export type ApproveBody = {
    /**
     * Visibility
     */
    visibility?: 'family' | 'catalog';
};

/**
 * ApprovedView
 *
 * The response to a successful approve action.
 *
 * ``approved_by`` and ``published_at`` are REQUIRED: a published story always
 * carries its approver and publish time, so this model cannot represent the
 * illegal "published without an approver" combination.
 */
export type ApprovedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'published';
    /**
     * Current Published Version
     */
    current_published_version: number;
    /**
     * Approved By
     */
    approved_by: string;
    /**
     * Published At
     */
    published_at: string;
    /**
     * Visibility
     */
    visibility: 'family' | 'catalog';
};

/**
 * ArchivedView
 *
 * The response to a successful archive action.
 */
export type ArchivedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'archived';
};

/**
 * AssignmentCreateBody
 *
 * A guardian's request to assign a story to one or more child profiles.
 */
export type AssignmentCreateBody = {
    /**
     * Profile Ids
     */
    profile_ids: Array<string>;
};

/**
 * AssignmentListView
 *
 * The full current set of profiles a story is assigned to.
 */
export type AssignmentListView = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Profile Ids
     */
    profile_ids: Array<string>;
};

/**
 * AuthoringPlanRequest
 *
 * Admin's choice of authoring method, mechanism, and prep model.
 *
 * ``review_stage1_model`` / ``review_stage2_model`` are optional overrides
 * for the Stage 1 fidelity review and Stage 2 model, used only when
 * method='skeleton_fill'. ``provider``/``model`` (WS-C PR1) select the
 * generation backend when ``mechanism='automated_provider'``; both are
 * required together in that case and are validated against the enabled
 * provider/model allowlist by ``build_authoring_plan`` (a DB-backed check
 * the schema layer cannot perform). ``skeleton_slug`` is an optional admin
 * override (decision C-6): any slug on disk is accepted, including a
 * non-production-eligible or out-of-cell one, with a warning surfaced on
 * mismatch rather than a rejection. It is "unconstrained" in WHICH skeleton it
 * may name, but the value is charset-bounded to a slug (lowercase, digits,
 * hyphens) so a path-traversal string can never reach the filesystem path
 * builders; the DB provenance column is String(120), so the length is capped
 * to match.
 */
export type AuthoringPlanRequest = {
    /**
     * Method
     */
    method: 'skeleton_fill' | 'fresh_generation';
    /**
     * Mechanism
     */
    mechanism: 'skill' | 'automated_provider';
    /**
     * Prep Model
     */
    prep_model: string;
    /**
     * Provider
     */
    provider?: 'anthropic' | 'openrouter' | 'modal' | 'ollama' | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Review Stage1 Model
     */
    review_stage1_model?: string | null;
    /**
     * Review Stage2 Model
     */
    review_stage2_model?: string | null;
    /**
     * Skeleton Slug
     */
    skeleton_slug?: string | null;
};

/**
 * AuthoringPlanResponse
 *
 * The generation job created (or parked) by an authoring-plan decision.
 */
export type AuthoringPlanResponse = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Concept Id
     */
    concept_id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Method
     */
    method: 'skeleton_fill' | 'fresh_generation';
    /**
     * Mechanism
     */
    mechanism: 'skill' | 'automated_provider';
    /**
     * Status
     */
    status: 'queued' | 'running' | 'passed' | 'needs_review' | 'failed' | 'awaiting_manual_fill';
    /**
     * Skeleton Slug
     */
    skeleton_slug?: string | null;
    /**
     * Skeleton Alternatives
     */
    skeleton_alternatives?: Array<AlternativeView>;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * CategoryInsightView
 *
 * Override evidence for one (age_band, category) pair (WS-F).
 */
export type CategoryInsightView = {
    /**
     * Age Band
     */
    age_band: string;
    /**
     * Category
     */
    category: string;
    /**
     * Advisory Findings
     */
    advisory_findings: number;
    /**
     * Flag Findings
     */
    flag_findings: number;
    /**
     * Decided Versions
     */
    decided_versions: number;
    /**
     * Released Versions
     */
    released_versions: number;
    /**
     * Override Rate
     */
    override_rate: number | null;
    /**
     * Last Seen
     */
    last_seen: string;
};

/**
 * CompletionBody
 *
 * A request to record that a child reached an ending.
 */
export type CompletionBody = {
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Ending Id
     */
    ending_id: string;
    /**
     * Event Id
     */
    event_id?: string | null;
};

/**
 * CompletionView
 *
 * A recorded completion.
 */
export type CompletionView = {
    /**
     * Child Profile Id
     */
    child_profile_id: string;
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Ending Id
     */
    ending_id: string;
    /**
     * Found At
     */
    found_at: string;
};

/**
 * ConceptBrief
 *
 * Guardian-supplied creative brief for a single story-generation job.
 *
 * Passed to the generation orchestrator after PII screening. Fields map
 * directly to the intake spec in ``docs/planning/tech-spec.md`` (section
 * "Concept brief (intake fields)"). Free-text fields carry ``max_length``
 * bounds (and list fields a count cap) so a brief cannot inflate prompt size
 * or smuggle an oversized payload into a generation prompt. Every string
 * field (including nested ``protagonist`` fields and list items) additionally
 * has ASCII control characters stripped at intake, before field validation
 * runs (see ``_strip_control_chars`` above; safety-eval Finding 5 / #64).
 *
 * ``extra="forbid"`` ensures that any unexpected field name is rejected at
 * parse time, preventing accidental injection of undeclared data.
 */
export type ConceptBrief = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Premise
     *
     * Short story premise; the seed for generation.
     */
    premise: string;
    /**
     * Fictional story character (name/age/role). NOT a real child.
     */
    protagonist: Protagonist;
    /**
     * Point Of View
     *
     * Narrative POV (default: second person).
     */
    point_of_view?: string;
    /**
     * Target reading age band.
     */
    age_band: AgeBand;
    /**
     * Reading Level Target
     *
     * Target Flesch-Kincaid grade level.
     */
    reading_level_target: number;
    /**
     * Tier
     *
     * Story tier: 1 = simple (no variables), 2 = stateful.
     */
    tier: number;
    /**
     * Tone
     *
     * Desired narrative tone (e.g. 'adventurous', 'cosy').
     */
    tone: string;
    /**
     * Themes Allowed
     *
     * Themes the story is allowed to explore.
     */
    themes_allowed?: Array<string>;
    /**
     * Content Nogo
     *
     * Content categories explicitly prohibited in this story.
     */
    content_nogo?: Array<string>;
    /**
     * Target Node Count
     *
     * Desired number of passage nodes.
     */
    target_node_count: number;
    /**
     * Ending Count
     *
     * Number of distinct endings to generate.
     */
    ending_count: number;
    /**
     * Narrative-structure template to apply.
     */
    structure_pattern: StructurePattern;
    /**
     * Story-scale length tier (short/medium/long); None = band budget.
     */
    length?: Length | null;
    /**
     * Prose or gamebook chunking of the word budget (ADR-011).
     */
    narrative_style?: NarrativeStyle;
    /**
     * Desired Variables
     *
     * Names of state variables the story should declare (Tier-2).
     */
    desired_variables?: Array<string>;
    /**
     * Special Constraints
     *
     * Free-text constraints passed to the generator as guidance.
     */
    special_constraints?: Array<string>;
    /**
     * Soft-continuation context from a series anchor (WS-B PR 3).
     */
    anchor_context?: AnchorContext | null;
};

/**
 * ConceptCreateRequest
 *
 * Guardian request to create a concept brief.
 *
 * ``extra="forbid"`` propagates ConceptBrief's strictness at the API boundary.
 */
export type ConceptCreateRequest = {
    brief: ConceptBrief;
};

/**
 * ConceptCreatedResponse
 *
 * Response returned after a concept is persisted.
 */
export type ConceptCreatedResponse = {
    /**
     * Concept Id
     */
    concept_id: string;
};

/**
 * ConflictView
 *
 * The 409 body returned when a reading-state save loses a revision race.
 */
export type ConflictView = {
    /**
     * Detail
     */
    detail: string;
    current_row: ReadingStateView;
    /**
     * Options
     */
    options?: Array<string>;
};

/**
 * ContentSummaryView
 *
 * The guardian-facing content review summary for a published story.
 *
 * A redacted projection of the admin review surface: it carries the gating
 * summary and story-level findings, plus a total flagged count, but never the
 * per-node flagged passages (which can spoil content and leak generation
 * internals). ``findings`` holds only whole-story findings; per-node findings
 * are counted in ``flagged_count`` but not enumerated.
 */
export type ContentSummaryView = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Screened
     */
    screened: boolean;
    summary: ReviewSummary | null;
    /**
     * Flagged Count
     */
    flagged_count: number;
    /**
     * Findings
     */
    findings: Array<GuardianFinding>;
};

/**
 * CoverStatusView
 *
 * Cover generation status for one story version.
 */
export type CoverStatusView = {
    /**
     * Cover Status
     */
    cover_status: string;
    /**
     * Cover Url
     */
    cover_url?: string | null;
};

/**
 * FamilyListView
 *
 * All families, admin-only (powers the required family selector).
 */
export type FamilyListView = {
    /**
     * Families
     */
    families: Array<FamilyView>;
};

/**
 * FamilyView
 *
 * A family as listed for the admin authored-request form.
 */
export type FamilyView = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * FindingView
 *
 * One moderation finding, shaped for the guardian review UI.
 */
export type FindingView = {
    /**
     * Stage
     */
    stage: number;
    source: Source;
    /**
     * Category
     */
    category: string;
    /**
     * Node Id
     */
    node_id: string | null;
    verdict: Verdict;
    /**
     * Score
     */
    score: number | null;
    /**
     * Message
     */
    message: string;
};

/**
 * FlaggedPassage
 *
 * A node's prose plus the findings that concern it.
 */
export type FlaggedPassage = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Prose
     */
    prose: string;
    /**
     * Findings
     */
    findings: Array<FindingView>;
};

/**
 * GenerationEnqueuedResponse
 *
 * Response returned after a generation job is created and enqueued.
 */
export type GenerationEnqueuedResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status?: 'queued';
};

/**
 * GenerationJobListItem
 *
 * One row in the guardian's "My Requests" list.
 *
 * Deliberately omits the raw ``report`` column (ADR-007): guardian-facing
 * endpoints expose job status and the linked storybook only, never the
 * multi-stage model output. ``storybook_status`` is the linked storybook's
 * current lifecycle state (or ``None`` when no storybook row exists yet), so
 * the UI can tell an awaiting-review story from a published one.
 */
export type GenerationJobListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'queued' | 'running' | 'passed' | 'needs_review' | 'failed' | 'awaiting_manual_fill';
    /**
     * Storybook Id
     */
    storybook_id?: string | null;
    /**
     * Storybook Status
     */
    storybook_status?: string | null;
    /**
     * Version
     */
    version?: number | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Premise Snippet
     */
    premise_snippet?: string;
    /**
     * Age Band
     */
    age_band?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * GenerationJobListView
 *
 * The generation jobs visible to the calling guardian's family.
 */
export type GenerationJobListView = {
    /**
     * Jobs
     */
    jobs: Array<GenerationJobListItem>;
};

/**
 * GenerationJobResponse
 *
 * Full status payload for a generation job.
 */
export type GenerationJobResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'queued' | 'running' | 'passed' | 'needs_review' | 'failed' | 'awaiting_manual_fill';
    /**
     * Report
     */
    report?: {
        [key: string]: unknown;
    } | null;
    /**
     * Storybook Id
     */
    storybook_id?: string | null;
    /**
     * Version
     */
    version?: number | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Skeleton Slug
     */
    skeleton_slug?: string | null;
    /**
     * Theme Brief
     */
    theme_brief?: {
        [key: string]: unknown;
    } | null;
};

/**
 * GuardianBookItem
 *
 * A published family book as the guardian browses it to assign (Task 2.2).
 *
 * Carries a redacted content badge (``screened`` + ``flagged_count``, the same
 * two signals the assign dialog and console rows show) and the set of child
 * profiles the book is currently assigned to. The full story-level findings are
 * deliberately not embedded here: the assign dialog lazy-fetches them from the
 * content-summary endpoint (Task 2.1) when it opens, so the browse list stays
 * lean and the findings projection lives in exactly one place.
 */
export type GuardianBookItem = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Version
     */
    version: number;
    /**
     * Age Band
     */
    age_band: string;
    /**
     * Visibility
     */
    visibility: 'family' | 'catalog';
    /**
     * Screened
     */
    screened: boolean;
    /**
     * Flagged Count
     */
    flagged_count: number;
    /**
     * Assigned Profile Ids
     */
    assigned_profile_ids: Array<string>;
};

/**
 * GuardianBooksView
 *
 * The family's published books for the guardian browse-and-assign page.
 */
export type GuardianBooksView = {
    /**
     * Books
     */
    books: Array<GuardianBookItem>;
};

/**
 * GuardianFinding
 *
 * A redacted, story-level moderation finding shown to a guardian.
 *
 * Deliberately narrower than FindingView: it drops source, stage, score, and
 * node_id so the guardian assign flow never leaks generation internals or a
 * per-node passage locator. Only the category, gating verdict, and the
 * human-readable message reach the guardian.
 */
export type GuardianFinding = {
    /**
     * Category
     */
    category: string;
    verdict: Verdict;
    /**
     * Message
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 *
 * Health check response model.
 */
export type HealthStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
};

/**
 * Length
 *
 * The story-scale (length) tier: a total-word budget, world size.
 *
 * Production stories place themselves on the ``(band, length, style)`` matrix
 * from ADR-011; the node-count envelope is derived per cell. Young bands cap
 * at ``MEDIUM``; epic scale is a series, not a fourth tier. A story that
 * declares no length is not scale-classified and keeps the band-level budget.
 */
export type Length = 'short' | 'medium' | 'long';

/**
 * LibraryItem
 *
 * A published story as seen in a child's library listing.
 */
export type LibraryItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Version
     */
    version: number;
    /**
     * Age Band
     */
    age_band: string;
    /**
     * Tier
     */
    tier: number;
    /**
     * Reading Level Target
     */
    reading_level_target: number;
    /**
     * Node Count
     */
    node_count?: number;
    /**
     * Rating
     */
    rating?: number | null;
    progress?: LibraryProgress | null;
    /**
     * Series Id
     */
    series_id?: string | null;
    /**
     * Book Index
     */
    book_index?: number | null;
    /**
     * Cover Url
     */
    cover_url?: string | null;
};

/**
 * LibraryProgress
 *
 * A child's reading progress on one library book (for shelf progress bars).
 *
 * ``nodes_visited`` counts distinct visited nodes; percent completion is a
 * frontend concern (``nodes_visited / node_count`` of the containing item).
 * ``updated_at`` is the server-maintained ReadingState timestamp and drives
 * "Continue Reading" (most recently active) selection.
 */
export type LibraryProgress = {
    /**
     * Current Node
     */
    current_node: string;
    /**
     * Nodes Visited
     */
    nodes_visited: number;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LibraryView
 *
 * A library listing for a profile.
 */
export type LibraryView = {
    /**
     * Stories
     */
    stories: Array<LibraryItem>;
};

/**
 * MeResponse
 *
 * The authenticated caller's own identity and role.
 *
 * The frontend has no way to inspect a bearer token itself (it may be an
 * opaque dev-stub string locally, or a signed Supabase JWT it should not
 * parse); this is the sole source of truth for which shell (kid vs
 * guardian) and nav to render for the current session.
 */
export type MeResponse = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Role
     */
    role: string;
    /**
     * Family Id
     */
    family_id: string;
    /**
     * Profile Ids
     */
    profile_ids: Array<string>;
};

/**
 * ModerationDashboardView
 *
 * Aggregated moderation evidence for the admin dashboard (WS-F).
 */
export type ModerationDashboardView = {
    /**
     * Insights
     */
    insights: Array<CategoryInsightView>;
    /**
     * Recent Changes
     */
    recent_changes: Array<ThresholdChangeView>;
};

/**
 * NarrativeStyle
 *
 * Prose vs gamebook chunking of one word budget (ADR-011).
 *
 * Meaningful only for ``13-16`` and ``16+``; lower bands are implicitly
 * ``PROSE``. Gamebook packs the same total words into more, shorter nodes.
 */
export type NarrativeStyle = 'prose' | 'gamebook';

/**
 * NoiseFloorUpdateBody
 *
 * PUT body for the global admin noise floor.
 */
export type NoiseFloorUpdateBody = {
    /**
     * Value
     */
    value: number;
};

/**
 * NoiseFloorView
 *
 * The global admin noise floor: the ADVISORY-score cutoff for admin review.
 */
export type NoiseFloorView = {
    /**
     * Value
     */
    value: number;
};

/**
 * ProfileCreateBody
 *
 * A guardian's request to create a child profile.
 */
export type ProfileCreateBody = {
    /**
     * Display Name
     */
    display_name: string;
    age_band: AgeBand;
    /**
     * Reading Level Cap
     */
    reading_level_cap?: number;
    /**
     * Avatar
     */
    avatar?: 'fox' | 'owl' | 'dragon' | 'cat' | 'unicorn' | 'robot' | 'rocket' | 'frog' | null;
    /**
     * Tts Enabled
     */
    tts_enabled?: boolean;
};

/**
 * ProfileListView
 *
 * The profiles the calling principal may act on.
 */
export type ProfileListView = {
    /**
     * Profiles
     */
    profiles: Array<ProfileView>;
};

/**
 * ProfileUpdateBody
 *
 * A guardian's partial update to a child profile.
 *
 * ``avatar`` distinguishes "omitted" from "explicit null" via
 * ``model_fields_set``: an explicit ``"avatar": null`` clears the avatar.
 * The other four fields have no legitimate "clear" semantics, so an explicit
 * ``null`` on them is a deliberate no-op (the router only applies non-null
 * values); see ``update_profile`` and
 * ``test_update_ignores_explicit_null_on_non_avatar_fields``.
 */
export type ProfileUpdateBody = {
    /**
     * Display Name
     */
    display_name?: string | null;
    age_band?: AgeBand | null;
    /**
     * Reading Level Cap
     */
    reading_level_cap?: number | null;
    /**
     * Avatar
     */
    avatar?: 'fox' | 'owl' | 'dragon' | 'cat' | 'unicorn' | 'robot' | 'rocket' | 'frog' | null;
    /**
     * Tts Enabled
     */
    tts_enabled?: boolean | null;
};

/**
 * ProfileView
 *
 * A child profile as seen by its guardian or the child themself.
 */
export type ProfileView = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    age_band: AgeBand;
    /**
     * Reading Level Cap
     */
    reading_level_cap: number;
    /**
     * Avatar
     */
    avatar: string | null;
    /**
     * Tts Enabled
     */
    tts_enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Protagonist
 *
 * The fictional story character whose role the reader takes.
 *
 * This is a STORY character defined by the guardian for the narrative. It is
 * not a real child's profile. The ``name`` field here is a fictional character
 * name and is not subject to PII screening (see module docstring).
 */
export type Protagonist = {
    /**
     * Name
     *
     * Fictional character name for the story.
     */
    name: string;
    /**
     * Age
     *
     * Story character's age in years (0-18, for a children's app).
     */
    age: number;
    /**
     * Role
     *
     * Character's narrative role (e.g. 'young explorer').
     */
    role: string;
};

/**
 * RatingBody
 *
 * A request to set or update a child's rating of a storybook.
 */
export type RatingBody = {
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Value
     */
    value: number;
};

/**
 * RatingListView
 *
 * All ratings recorded by a single child profile.
 */
export type RatingListView = {
    /**
     * Ratings
     */
    ratings: Array<RatingView>;
};

/**
 * RatingView
 *
 * A child's recorded rating of a storybook.
 */
export type RatingView = {
    /**
     * Child Profile Id
     */
    child_profile_id: string;
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Value
     */
    value: number;
    /**
     * Rated At
     */
    rated_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ReadinessCheck
 *
 * Individual dependency check result.
 */
export type ReadinessCheck = {
    /**
     * Name
     *
     * Dependency name
     */
    name: string;
    /**
     * Status
     *
     * Check passed
     */
    status: boolean;
    /**
     * Latency Ms
     *
     * Check latency in milliseconds
     */
    latency_ms?: number | null;
    /**
     * Error
     *
     * Error message if failed
     */
    error?: string | null;
};

/**
 * ReadinessStatus
 *
 * Readiness check response with dependency details.
 */
export type ReadinessStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
    /**
     * Checks
     *
     * Individual dependency checks
     */
    checks?: {
        [key: string]: ReadinessCheck;
    };
};

/**
 * ReadingStateBody
 *
 * A reading-state save submitted by the client (PUT body).
 */
export type ReadingStateBody = {
    /**
     * Version
     */
    version: number;
    /**
     * Current Node
     */
    current_node: string;
    /**
     * Var State
     */
    var_state?: {
        [key: string]: boolean | number | string;
    };
    /**
     * Path
     */
    path?: Array<string>;
    /**
     * Visit Set
     */
    visit_set?: Array<string>;
    /**
     * Save Slots
     */
    save_slots?: {
        [key: string]: unknown;
    };
    /**
     * State Revision
     */
    state_revision: number;
    /**
     * Device Id
     */
    device_id?: string | null;
    /**
     * Event Id
     */
    event_id?: string | null;
    /**
     * Choice Path
     */
    choice_path?: Array<string> | null;
};

/**
 * ReadingStateView
 *
 * A reading-state row returned to the client.
 */
export type ReadingStateView = {
    /**
     * Child Profile Id
     */
    child_profile_id: string;
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Current Node
     */
    current_node: string;
    /**
     * Var State
     */
    var_state: {
        [key: string]: boolean | number | string;
    };
    /**
     * Path
     */
    path: Array<string>;
    /**
     * Visit Set
     */
    visit_set: Array<string>;
    /**
     * Save Slots
     */
    save_slots: {
        [key: string]: unknown;
    };
    /**
     * State Revision
     */
    state_revision: number;
    /**
     * Updated By Device Id
     */
    updated_by_device_id: string | null;
    /**
     * Last Synced At
     */
    last_synced_at: string | null;
};

/**
 * ReviewQueueItem
 *
 * One storybook in the admin review queue, shaped for client bucketing.
 *
 * ``screened`` plus ``flagged_count`` let the console bucket into "Flagged"
 * (screened with findings, or never screened) versus "Ready to review"
 * (screened clean). ``summary`` carries the report's gating flags when present.
 */
export type ReviewQueueItem = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: number;
    /**
     * Screened
     */
    screened: boolean;
    /**
     * Flagged Count
     */
    flagged_count: number;
    summary: ReviewSummary | null;
};

/**
 * ReviewQueueView
 *
 * The admin review queue: storybooks awaiting a publish decision.
 */
export type ReviewQueueView = {
    /**
     * Items
     */
    items: Array<ReviewQueueItem>;
};

/**
 * ReviewSummary
 *
 * The moderation report's derived gating summary.
 */
export type ReviewSummary = {
    /**
     * Count
     */
    count: number;
    /**
     * Hard Block
     */
    hard_block: boolean;
    /**
     * Soft Flag
     */
    soft_flag: boolean;
    /**
     * Repaired
     */
    repaired: boolean;
    /**
     * Reviewer Independent
     */
    reviewer_independent: boolean;
};

/**
 * ReviewSurfaceView
 *
 * The full guardian review surface for one story version (C3-4).
 */
export type ReviewSurfaceView = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Status
     */
    status: string;
    /**
     * Blob
     */
    blob: {
        [key: string]: unknown;
    };
    /**
     * Screened
     */
    screened: boolean;
    summary: ReviewSummary | null;
    /**
     * Flagged Passages
     */
    flagged_passages: Array<FlaggedPassage>;
    /**
     * Story Level Findings
     */
    story_level_findings: Array<FindingView>;
};

/**
 * SendBackRequest
 *
 * Body for the send-back endpoint.
 */
export type SendBackRequest = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * SentBackView
 *
 * The response to a successful send-back action; ``reason`` is required.
 */
export type SentBackView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'needs_revision';
    /**
     * Reason
     */
    reason: string;
};

/**
 * SeriesNextBook
 *
 * The next readable book in a series, resolved for one profile.
 */
export type SeriesNextBook = {
    /**
     * Storybook Id
     */
    storybook_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Title
     */
    title: string;
    /**
     * Series Entry Node
     */
    series_entry_node?: string | null;
    /**
     * Carries State
     */
    carries_state: boolean;
};

/**
 * SeriesNextView
 *
 * GET /series-next response; ``next`` is null for every expected absence.
 */
export type SeriesNextView = {
    next?: SeriesNextBook | null;
};

/**
 * Source
 *
 * Which stage or classifier produced a finding.
 */
export type Source = 'openai' | 'perspective' | 'llm_safety' | 'llm_readability' | 'llm_coherence' | 'llm_engagement' | 'pipeline';

/**
 * StoryRequestApproveBody
 *
 * Guardian confirmation required to approve a request (WS-B).
 *
 * The request becomes the source of truth for band and length at approval;
 * ``narrative_style`` follows ADR-011: gamebook only for 13-16 and 16+.
 * ``series_title`` ratifies or edits the kid's proposed series title;
 * omitting it declines the proposal (the anchored-plus-title conflict is a
 * service-layer check because it needs the row).
 */
export type StoryRequestApproveBody = {
    age_band: AgeBand;
    length: Length;
    narrative_style?: NarrativeStyle;
    /**
     * Series Title
     */
    series_title?: string | null;
};

/**
 * StoryRequestApprovedView
 *
 * The result of approving a request: the linked concept.
 *
 * No GenerationJob is created at approval time; an admin creates one by
 * calling POST /story-requests/{id}/authoring-plan (see
 * story_requests/authoring_plan.py).
 */
export type StoryRequestApprovedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'approved';
    /**
     * Concept Id
     */
    concept_id: string;
};

/**
 * StoryRequestAuthoredCreateBody
 *
 * A guardian's or admin's pre-approved story request (WS-B PR 2).
 *
 * ``profile_id`` is optional (an authored request need not target a child).
 * ``family_id`` is admin-only: admins must name the target family (decision
 * B3); guardians must omit it (their own family is server-derived).
 * ``series_title`` and ``anchor_storybook_id`` are mutually exclusive: the
 * former creates a new series immediately (no ratification step), the
 * latter continues an existing one.
 */
export type StoryRequestAuthoredCreateBody = {
    age_band: AgeBand;
    length: Length;
    narrative_style?: NarrativeStyle;
    /**
     * Request Text
     */
    request_text: string;
    /**
     * Profile Id
     */
    profile_id?: string | null;
    /**
     * Family Id
     */
    family_id?: string | null;
    /**
     * Series Title
     */
    series_title?: string | null;
    /**
     * Anchor Storybook Id
     */
    anchor_storybook_id?: string | null;
};

/**
 * StoryRequestAuthoredCreatedView
 *
 * The result of an authored create: approved with a concept, or blocked.
 */
export type StoryRequestAuthoredCreatedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'declined' | 'blocked';
    /**
     * Concept Id
     */
    concept_id: string | null;
};

/**
 * StoryRequestCreateBody
 *
 * A child's free-text story request (kid surface; guardian-scoped in R1).
 *
 * ``proposed_series_title`` and ``anchor_storybook_id`` are mutually
 * exclusive: the former proposes a brand-new, unratified series name; the
 * latter asks for a soft continuation anchored to an existing storybook.
 */
export type StoryRequestCreateBody = {
    /**
     * Profile Id
     */
    profile_id: string;
    /**
     * Request Text
     */
    request_text: string;
    /**
     * Proposed Series Title
     */
    proposed_series_title?: string | null;
    /**
     * Anchor Storybook Id
     */
    anchor_storybook_id?: string | null;
};

/**
 * StoryRequestCreatedView
 *
 * The result of submitting a request: its id and post-screening status.
 */
export type StoryRequestCreatedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'declined' | 'blocked';
};

/**
 * StoryRequestDeclinedView
 *
 * The result of declining a request.
 */
export type StoryRequestDeclinedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'declined';
};

/**
 * StoryRequestFlag
 *
 * A redacted screening flag shown to a guardian.
 *
 * Mirrors GuardianFinding: category, gating verdict, and message only. Never
 * the classifier score, source, or the child's raw request text.
 */
export type StoryRequestFlag = {
    /**
     * Category
     */
    category: string;
    verdict: Verdict;
    /**
     * Message
     */
    message: string;
};

/**
 * StoryRequestListView
 *
 * The story requests visible to the caller, newest first.
 */
export type StoryRequestListView = {
    /**
     * Requests
     */
    requests: Array<StoryRequestView>;
};

/**
 * StoryRequestView
 *
 * One story request as seen by a guardian, admin, or (via guardian token) child.
 *
 * ``request_text`` is ``None`` for a ``blocked`` row: the raw text of a
 * bright-line request is never surfaced. ``moderation_flags`` carries only the
 * redacted StoryRequestFlag list. ``age_band``, ``length``, and
 * ``narrative_style`` are request-sourced (WS-B): for a still-pending
 * request they reflect the profile-stamped defaults from creation; for an
 * approved request they reflect the guardian's approval confirmation, and
 * the guardian UI uses the band/length/style trio to prefill the approve
 * dialog. ``profile_id`` is ``None`` for an authored request with no target
 * child (WS-B PR 2). ``proposed_series_title`` is ``None`` for blocked rows
 * (screened content, same redaction as ``request_text``).
 *
 * ``series_id``, ``proposed_series_title``, and ``anchor_storybook_id``
 * default to ``None`` rather than being required so older tests
 * constructing a view directly need not supply them; ``_to_view``
 * (api/story_requests.py) populates all three from the row for every
 * caller (WS-B PR 3).
 */
export type StoryRequestView = {
    /**
     * Id
     */
    id: string;
    /**
     * Profile Id
     */
    profile_id: string | null;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'declined' | 'blocked';
    /**
     * Request Text
     */
    request_text: string | null;
    /**
     * Moderation Flags
     */
    moderation_flags: Array<StoryRequestFlag>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Initiator Role
     */
    initiator_role: 'child' | 'guardian' | 'admin';
    age_band: AgeBand;
    length: Length | null;
    narrative_style: NarrativeStyle;
    /**
     * Series Id
     */
    series_id?: string | null;
    /**
     * Proposed Series Title
     */
    proposed_series_title?: string | null;
    /**
     * Anchor Storybook Id
     */
    anchor_storybook_id?: string | null;
};

/**
 * StructurePattern
 *
 * Narrative-structure templates available for story generation.
 *
 * Patterns follow the vocabulary from "Choose Your Own Adventure" design
 * theory. Each describes how branches and convergence points are arranged.
 */
export type StructurePattern = 'time_cave' | 'gauntlet' | 'branch_and_bottleneck' | 'quest' | 'loop_and_grow';

/**
 * SubmittedView
 *
 * The response to a successful submit action.
 */
export type SubmittedView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'in_review';
    /**
     * Current Published Version
     */
    current_published_version: number | null;
};

/**
 * SuggestionListView
 *
 * Computed proposals plus the gates that produced them (WS-F).
 */
export type SuggestionListView = {
    /**
     * Min Decided Versions
     */
    min_decided_versions: number;
    /**
     * Min Override Rate
     */
    min_override_rate: number;
    /**
     * Suggestions
     */
    suggestions: Array<ThresholdSuggestionView>;
};

/**
 * ThresholdChangeView
 *
 * One recent threshold or noise-floor change event (WS-F).
 */
export type ThresholdChangeView = {
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
};

/**
 * ThresholdListView
 *
 * All overrides plus the code default and the category suggestion list.
 */
export type ThresholdListView = {
    /**
     * Default Min Verdict
     */
    default_min_verdict: 'advisory' | 'flag' | 'block';
    /**
     * Default Min Score
     */
    default_min_score: number | null;
    /**
     * Known Categories
     */
    known_categories: Array<string>;
    /**
     * Rows
     */
    rows: Array<ThresholdView>;
};

/**
 * ThresholdSuggestionView
 *
 * A computed threshold proposal awaiting admin ratification (WS-F).
 */
export type ThresholdSuggestionView = {
    /**
     * Age Band
     */
    age_band: string;
    /**
     * Category
     */
    category: string;
    /**
     * Current Min Verdict
     */
    current_min_verdict: 'advisory' | 'flag' | 'block';
    /**
     * Current Min Score
     */
    current_min_score: number | null;
    /**
     * Suggested Min Verdict
     */
    suggested_min_verdict: 'advisory' | 'flag' | 'block';
    /**
     * Override Rate
     */
    override_rate: number;
    /**
     * Decided Versions
     */
    decided_versions: number;
    /**
     * Released Versions
     */
    released_versions: number;
};

/**
 * ThresholdUpsertBody
 *
 * PUT body for a threshold override.
 */
export type ThresholdUpsertBody = {
    /**
     * Min Verdict
     */
    min_verdict: 'advisory' | 'flag' | 'block';
    /**
     * Min Score
     */
    min_score?: number | null;
};

/**
 * ThresholdView
 *
 * One stored (age_band, category) surfacing override.
 */
export type ThresholdView = {
    /**
     * Age Band
     */
    age_band: string;
    /**
     * Category
     */
    category: string;
    /**
     * Min Verdict
     */
    min_verdict: 'advisory' | 'flag' | 'block';
    /**
     * Min Score
     */
    min_score: number | null;
};

/**
 * ValidateResponse
 *
 * Response returned by the re-validate endpoint.
 */
export type ValidateResponse = {
    /**
     * Blocked
     */
    blocked: boolean;
    /**
     * Report
     */
    report: {
        [key: string]: unknown;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Verdict
 *
 * A finding's gating role.
 *
 * ``BLOCK`` is a hard gate (Stage 0 bright-line or Stage 1 block). ``FLAG`` is a
 * soft gate (auto-repair then surface). ``ADVISORY`` never gates. ``PASS`` records
 * a clean check.
 */
export type Verdict = 'block' | 'flag' | 'advisory' | 'pass';

export type LivenessHealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessHealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type LivenessHealthLiveGetResponse = LivenessHealthLiveGetResponses[keyof LivenessHealthLiveGetResponses];

export type ReadinessHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessHealthReadyGetErrors = {
    /**
     * Application is not ready (dependencies unavailable)
     */
    503: unknown;
};

export type ReadinessHealthReadyGetResponses = {
    /**
     * Application is ready to serve traffic
     */
    200: ReadinessStatus;
};

export type ReadinessHealthReadyGetResponse = ReadinessHealthReadyGetResponses[keyof ReadinessHealthReadyGetResponses];

export type StartupHealthStartupGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/startup';
};

export type StartupHealthStartupGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type StartupHealthStartupGetResponse = StartupHealthStartupGetResponses[keyof StartupHealthStartupGetResponses];

export type ListLibraryApiV1LibraryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    url: '/api/v1/library';
};

export type ListLibraryApiV1LibraryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLibraryApiV1LibraryGetError = ListLibraryApiV1LibraryGetErrors[keyof ListLibraryApiV1LibraryGetErrors];

export type ListLibraryApiV1LibraryGetResponses = {
    /**
     * Successful Response
     */
    200: LibraryView;
};

export type ListLibraryApiV1LibraryGetResponse = ListLibraryApiV1LibraryGetResponses[keyof ListLibraryApiV1LibraryGetResponses];

export type GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/versions/{version}';
};

export type GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetError = GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetErrors[keyof GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetErrors];

export type GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetResponses = {
    /**
     * Response Get Storybook Version Api V1 Storybooks  Storybook Id  Versions  Version  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetResponse = GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetResponses[keyof GetStorybookVersionApiV1StorybooksStorybookIdVersionsVersionGetResponses];

export type GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/reading-state/{profile_id}/{storybook_id}';
};

export type GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetError = GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetErrors[keyof GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetErrors];

export type GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReadingStateView;
};

export type GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetResponse = GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetResponses[keyof GetReadingStateApiV1ReadingStateProfileIdStorybookIdGetResponses];

export type PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutData = {
    body: ReadingStateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/reading-state/{profile_id}/{storybook_id}';
};

export type PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutErrors = {
    /**
     * Revision or version conflict; the body carries the current row for client-side reconciliation.
     */
    409: ConflictView;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutError = PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutErrors[keyof PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutErrors];

export type PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutResponses = {
    /**
     * Successful Response
     */
    200: ReadingStateView;
};

export type PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutResponse = PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutResponses[keyof PutReadingStateApiV1ReadingStateProfileIdStorybookIdPutResponses];

export type GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/series-next/{profile_id}/{storybook_id}';
};

export type GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetError = GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetErrors[keyof GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetErrors];

export type GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetResponses = {
    /**
     * Successful Response
     */
    200: SeriesNextView;
};

export type GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetResponse = GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetResponses[keyof GetSeriesNextApiV1SeriesNextProfileIdStorybookIdGetResponses];

export type RecordCompletionApiV1CompletionsPostData = {
    body: CompletionBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/completions';
};

export type RecordCompletionApiV1CompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordCompletionApiV1CompletionsPostError = RecordCompletionApiV1CompletionsPostErrors[keyof RecordCompletionApiV1CompletionsPostErrors];

export type RecordCompletionApiV1CompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: CompletionView;
};

export type RecordCompletionApiV1CompletionsPostResponse = RecordCompletionApiV1CompletionsPostResponses[keyof RecordCompletionApiV1CompletionsPostResponses];

export type CreateConceptApiV1ConceptsPostData = {
    body: ConceptCreateRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/concepts';
};

export type CreateConceptApiV1ConceptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConceptApiV1ConceptsPostError = CreateConceptApiV1ConceptsPostErrors[keyof CreateConceptApiV1ConceptsPostErrors];

export type CreateConceptApiV1ConceptsPostResponses = {
    /**
     * Successful Response
     */
    201: ConceptCreatedResponse;
};

export type CreateConceptApiV1ConceptsPostResponse = CreateConceptApiV1ConceptsPostResponses[keyof CreateConceptApiV1ConceptsPostResponses];

export type EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Concept Id
         */
        concept_id: string;
    };
    query?: never;
    url: '/api/v1/concepts/{concept_id}/generate';
};

export type EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostError = EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostErrors[keyof EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostErrors];

export type EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostResponses = {
    /**
     * Successful Response
     */
    202: GenerationEnqueuedResponse;
};

export type EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostResponse = EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostResponses[keyof EnqueueConceptGenerationApiV1ConceptsConceptIdGeneratePostResponses];

export type ListGenerationJobsApiV1GenerationJobsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/generation-jobs';
};

export type ListGenerationJobsApiV1GenerationJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGenerationJobsApiV1GenerationJobsGetError = ListGenerationJobsApiV1GenerationJobsGetErrors[keyof ListGenerationJobsApiV1GenerationJobsGetErrors];

export type ListGenerationJobsApiV1GenerationJobsGetResponses = {
    /**
     * Successful Response
     */
    200: GenerationJobListView;
};

export type ListGenerationJobsApiV1GenerationJobsGetResponse = ListGenerationJobsApiV1GenerationJobsGetResponses[keyof ListGenerationJobsApiV1GenerationJobsGetResponses];

export type GetGenerationJobApiV1GenerationJobsJobIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/generation-jobs/{job_id}';
};

export type GetGenerationJobApiV1GenerationJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGenerationJobApiV1GenerationJobsJobIdGetError = GetGenerationJobApiV1GenerationJobsJobIdGetErrors[keyof GetGenerationJobApiV1GenerationJobsJobIdGetErrors];

export type GetGenerationJobApiV1GenerationJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: GenerationJobResponse;
};

export type GetGenerationJobApiV1GenerationJobsJobIdGetResponse = GetGenerationJobApiV1GenerationJobsJobIdGetResponses[keyof GetGenerationJobApiV1GenerationJobsJobIdGetResponses];

export type ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/versions/{version}/validate';
};

export type ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostError = ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostErrors[keyof ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostErrors];

export type ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostResponse = ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostResponses[keyof ValidateStorybookVersionApiV1StorybooksStorybookIdVersionsVersionValidatePostResponses];

export type ListProfilesApiV1ProfilesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles';
};

export type ListProfilesApiV1ProfilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProfilesApiV1ProfilesGetError = ListProfilesApiV1ProfilesGetErrors[keyof ListProfilesApiV1ProfilesGetErrors];

export type ListProfilesApiV1ProfilesGetResponses = {
    /**
     * Successful Response
     */
    200: ProfileListView;
};

export type ListProfilesApiV1ProfilesGetResponse = ListProfilesApiV1ProfilesGetResponses[keyof ListProfilesApiV1ProfilesGetResponses];

export type CreateProfileApiV1ProfilesPostData = {
    body: ProfileCreateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles';
};

export type CreateProfileApiV1ProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileApiV1ProfilesPostError = CreateProfileApiV1ProfilesPostErrors[keyof CreateProfileApiV1ProfilesPostErrors];

export type CreateProfileApiV1ProfilesPostResponses = {
    /**
     * Successful Response
     */
    201: ProfileView;
};

export type CreateProfileApiV1ProfilesPostResponse = CreateProfileApiV1ProfilesPostResponses[keyof CreateProfileApiV1ProfilesPostResponses];

export type UpdateProfileApiV1ProfilesProfileIdPatchData = {
    body: ProfileUpdateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{profile_id}';
};

export type UpdateProfileApiV1ProfilesProfileIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileApiV1ProfilesProfileIdPatchError = UpdateProfileApiV1ProfilesProfileIdPatchErrors[keyof UpdateProfileApiV1ProfilesProfileIdPatchErrors];

export type UpdateProfileApiV1ProfilesProfileIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProfileView;
};

export type UpdateProfileApiV1ProfilesProfileIdPatchResponse = UpdateProfileApiV1ProfilesProfileIdPatchResponses[keyof UpdateProfileApiV1ProfilesProfileIdPatchResponses];

export type ListFamiliesApiV1AdminFamiliesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/families';
};

export type ListFamiliesApiV1AdminFamiliesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFamiliesApiV1AdminFamiliesGetError = ListFamiliesApiV1AdminFamiliesGetErrors[keyof ListFamiliesApiV1AdminFamiliesGetErrors];

export type ListFamiliesApiV1AdminFamiliesGetResponses = {
    /**
     * Successful Response
     */
    200: FamilyListView;
};

export type ListFamiliesApiV1AdminFamiliesGetResponse = ListFamiliesApiV1AdminFamiliesGetResponses[keyof ListFamiliesApiV1AdminFamiliesGetResponses];

export type RecordRatingApiV1RatingsPostData = {
    body: RatingBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/ratings';
};

export type RecordRatingApiV1RatingsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordRatingApiV1RatingsPostError = RecordRatingApiV1RatingsPostErrors[keyof RecordRatingApiV1RatingsPostErrors];

export type RecordRatingApiV1RatingsPostResponses = {
    /**
     * Successful Response
     */
    200: RatingView;
};

export type RecordRatingApiV1RatingsPostResponse = RecordRatingApiV1RatingsPostResponses[keyof RecordRatingApiV1RatingsPostResponses];

export type ListRatingsApiV1RatingsProfileIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/ratings/{profile_id}';
};

export type ListRatingsApiV1RatingsProfileIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRatingsApiV1RatingsProfileIdGetError = ListRatingsApiV1RatingsProfileIdGetErrors[keyof ListRatingsApiV1RatingsProfileIdGetErrors];

export type ListRatingsApiV1RatingsProfileIdGetResponses = {
    /**
     * Successful Response
     */
    200: RatingListView;
};

export type ListRatingsApiV1RatingsProfileIdGetResponse = ListRatingsApiV1RatingsProfileIdGetResponses[keyof ListRatingsApiV1RatingsProfileIdGetResponses];

export type GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/content-summary';
};

export type GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetError = GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetErrors[keyof GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetErrors];

export type GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: ContentSummaryView;
};

export type GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetResponse = GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetResponses[keyof GetContentSummaryApiV1StorybooksStorybookIdContentSummaryGetResponses];

export type ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/assignments';
};

export type ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetError = ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetErrors[keyof ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetErrors];

export type ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetResponses = {
    /**
     * Successful Response
     */
    200: AssignmentListView;
};

export type ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetResponse = ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetResponses[keyof ListAssignmentsApiV1StorybooksStorybookIdAssignmentsGetResponses];

export type AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostData = {
    body: AssignmentCreateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/assignments';
};

export type AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostError = AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostErrors[keyof AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostErrors];

export type AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    200: AssignmentListView;
};

export type AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostResponse = AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostResponses[keyof AssignStorybookApiV1StorybooksStorybookIdAssignmentsPostResponses];

export type ListGuardianBooksApiV1GuardianBooksGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/guardian/books';
};

export type ListGuardianBooksApiV1GuardianBooksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGuardianBooksApiV1GuardianBooksGetError = ListGuardianBooksApiV1GuardianBooksGetErrors[keyof ListGuardianBooksApiV1GuardianBooksGetErrors];

export type ListGuardianBooksApiV1GuardianBooksGetResponses = {
    /**
     * Successful Response
     */
    200: GuardianBooksView;
};

export type ListGuardianBooksApiV1GuardianBooksGetResponse = ListGuardianBooksApiV1GuardianBooksGetResponses[keyof ListGuardianBooksApiV1GuardianBooksGetResponses];

export type SubmitStorybookApiV1StorybooksStorybookIdSubmitPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/submit';
};

export type SubmitStorybookApiV1StorybooksStorybookIdSubmitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitStorybookApiV1StorybooksStorybookIdSubmitPostError = SubmitStorybookApiV1StorybooksStorybookIdSubmitPostErrors[keyof SubmitStorybookApiV1StorybooksStorybookIdSubmitPostErrors];

export type SubmitStorybookApiV1StorybooksStorybookIdSubmitPostResponses = {
    /**
     * Successful Response
     */
    200: SubmittedView;
};

export type SubmitStorybookApiV1StorybooksStorybookIdSubmitPostResponse = SubmitStorybookApiV1StorybooksStorybookIdSubmitPostResponses[keyof SubmitStorybookApiV1StorybooksStorybookIdSubmitPostResponses];

export type ApproveStorybookApiV1StorybooksStorybookIdApprovePostData = {
    /**
     * Body
     */
    body?: ApproveBody | null;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/approve';
};

export type ApproveStorybookApiV1StorybooksStorybookIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveStorybookApiV1StorybooksStorybookIdApprovePostError = ApproveStorybookApiV1StorybooksStorybookIdApprovePostErrors[keyof ApproveStorybookApiV1StorybooksStorybookIdApprovePostErrors];

export type ApproveStorybookApiV1StorybooksStorybookIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: ApprovedView;
};

export type ApproveStorybookApiV1StorybooksStorybookIdApprovePostResponse = ApproveStorybookApiV1StorybooksStorybookIdApprovePostResponses[keyof ApproveStorybookApiV1StorybooksStorybookIdApprovePostResponses];

export type SendBackStorybookApiV1StorybooksStorybookIdSendBackPostData = {
    body: SendBackRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/send-back';
};

export type SendBackStorybookApiV1StorybooksStorybookIdSendBackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendBackStorybookApiV1StorybooksStorybookIdSendBackPostError = SendBackStorybookApiV1StorybooksStorybookIdSendBackPostErrors[keyof SendBackStorybookApiV1StorybooksStorybookIdSendBackPostErrors];

export type SendBackStorybookApiV1StorybooksStorybookIdSendBackPostResponses = {
    /**
     * Successful Response
     */
    200: SentBackView;
};

export type SendBackStorybookApiV1StorybooksStorybookIdSendBackPostResponse = SendBackStorybookApiV1StorybooksStorybookIdSendBackPostResponses[keyof SendBackStorybookApiV1StorybooksStorybookIdSendBackPostResponses];

export type ArchiveStorybookApiV1StorybooksStorybookIdArchivePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/archive';
};

export type ArchiveStorybookApiV1StorybooksStorybookIdArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveStorybookApiV1StorybooksStorybookIdArchivePostError = ArchiveStorybookApiV1StorybooksStorybookIdArchivePostErrors[keyof ArchiveStorybookApiV1StorybooksStorybookIdArchivePostErrors];

export type ArchiveStorybookApiV1StorybooksStorybookIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: ArchivedView;
};

export type ArchiveStorybookApiV1StorybooksStorybookIdArchivePostResponse = ArchiveStorybookApiV1StorybooksStorybookIdArchivePostResponses[keyof ArchiveStorybookApiV1StorybooksStorybookIdArchivePostResponses];

export type GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
    };
    query?: {
        /**
         * Version
         */
        version?: number | null;
    };
    url: '/api/v1/storybooks/{storybook_id}/review';
};

export type GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetError = GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetErrors[keyof GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetErrors];

export type GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetResponses = {
    /**
     * Successful Response
     */
    200: ReviewSurfaceView;
};

export type GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetResponse = GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetResponses[keyof GetReviewSurfaceApiV1StorybooksStorybookIdReviewGetResponses];

export type GetReviewQueueApiV1ReviewQueueGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/review-queue';
};

export type GetReviewQueueApiV1ReviewQueueGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReviewQueueApiV1ReviewQueueGetError = GetReviewQueueApiV1ReviewQueueGetErrors[keyof GetReviewQueueApiV1ReviewQueueGetErrors];

export type GetReviewQueueApiV1ReviewQueueGetResponses = {
    /**
     * Successful Response
     */
    200: ReviewQueueView;
};

export type GetReviewQueueApiV1ReviewQueueGetResponse = GetReviewQueueApiV1ReviewQueueGetResponses[keyof GetReviewQueueApiV1ReviewQueueGetResponses];

export type CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/versions/{version}/cover';
};

export type CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetError = CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetErrors[keyof CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetErrors];

export type CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetResponses = {
    /**
     * Successful Response
     */
    200: CoverStatusView;
};

export type CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetResponse = CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetResponses[keyof CoverStatusApiV1StorybooksStorybookIdVersionsVersionCoverGetResponses];

export type RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Storybook Id
         */
        storybook_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/storybooks/{storybook_id}/versions/{version}/cover';
};

export type RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostError = RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostErrors[keyof RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostErrors];

export type RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostResponses = {
    /**
     * Successful Response
     */
    200: CoverStatusView;
};

export type RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostResponse = RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostResponses[keyof RequestCoverApiV1StorybooksStorybookIdVersionsVersionCoverPostResponses];

export type ListThresholdsApiV1AdminModerationThresholdsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/moderation-thresholds';
};

export type ListThresholdsApiV1AdminModerationThresholdsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListThresholdsApiV1AdminModerationThresholdsGetError = ListThresholdsApiV1AdminModerationThresholdsGetErrors[keyof ListThresholdsApiV1AdminModerationThresholdsGetErrors];

export type ListThresholdsApiV1AdminModerationThresholdsGetResponses = {
    /**
     * Successful Response
     */
    200: ThresholdListView;
};

export type ListThresholdsApiV1AdminModerationThresholdsGetResponse = ListThresholdsApiV1AdminModerationThresholdsGetResponses[keyof ListThresholdsApiV1AdminModerationThresholdsGetResponses];

export type DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Age Band
         */
        age_band: string;
    };
    query: {
        /**
         * Category
         */
        category: string;
    };
    url: '/api/v1/admin/moderation-thresholds/{age_band}';
};

export type DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteError = DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteErrors[keyof DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteErrors];

export type DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteResponses = {
    /**
     * Successful Response
     */
    200: ThresholdListView;
};

export type DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteResponse = DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteResponses[keyof DeleteThresholdApiV1AdminModerationThresholdsAgeBandDeleteResponses];

export type UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutData = {
    body: ThresholdUpsertBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Age Band
         */
        age_band: string;
    };
    query: {
        /**
         * Category
         */
        category: string;
    };
    url: '/api/v1/admin/moderation-thresholds/{age_band}';
};

export type UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutError = UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutErrors[keyof UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutErrors];

export type UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutResponses = {
    /**
     * Successful Response
     */
    200: ThresholdView;
};

export type UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutResponse = UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutResponses[keyof UpsertThresholdApiV1AdminModerationThresholdsAgeBandPutResponses];

export type GetNoiseFloorApiV1AdminModerationNoiseFloorGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/moderation/noise-floor';
};

export type GetNoiseFloorApiV1AdminModerationNoiseFloorGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNoiseFloorApiV1AdminModerationNoiseFloorGetError = GetNoiseFloorApiV1AdminModerationNoiseFloorGetErrors[keyof GetNoiseFloorApiV1AdminModerationNoiseFloorGetErrors];

export type GetNoiseFloorApiV1AdminModerationNoiseFloorGetResponses = {
    /**
     * Successful Response
     */
    200: NoiseFloorView;
};

export type GetNoiseFloorApiV1AdminModerationNoiseFloorGetResponse = GetNoiseFloorApiV1AdminModerationNoiseFloorGetResponses[keyof GetNoiseFloorApiV1AdminModerationNoiseFloorGetResponses];

export type UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutData = {
    body: NoiseFloorUpdateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/moderation/noise-floor';
};

export type UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutError = UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutErrors[keyof UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutErrors];

export type UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutResponses = {
    /**
     * Successful Response
     */
    200: NoiseFloorView;
};

export type UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutResponse = UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutResponses[keyof UpdateNoiseFloorApiV1AdminModerationNoiseFloorPutResponses];

export type ModerationDashboardApiV1AdminModerationDashboardGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/moderation/dashboard';
};

export type ModerationDashboardApiV1AdminModerationDashboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModerationDashboardApiV1AdminModerationDashboardGetError = ModerationDashboardApiV1AdminModerationDashboardGetErrors[keyof ModerationDashboardApiV1AdminModerationDashboardGetErrors];

export type ModerationDashboardApiV1AdminModerationDashboardGetResponses = {
    /**
     * Successful Response
     */
    200: ModerationDashboardView;
};

export type ModerationDashboardApiV1AdminModerationDashboardGetResponse = ModerationDashboardApiV1AdminModerationDashboardGetResponses[keyof ModerationDashboardApiV1AdminModerationDashboardGetResponses];

export type ModerationSuggestionsApiV1AdminModerationSuggestionsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/moderation/suggestions';
};

export type ModerationSuggestionsApiV1AdminModerationSuggestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModerationSuggestionsApiV1AdminModerationSuggestionsGetError = ModerationSuggestionsApiV1AdminModerationSuggestionsGetErrors[keyof ModerationSuggestionsApiV1AdminModerationSuggestionsGetErrors];

export type ModerationSuggestionsApiV1AdminModerationSuggestionsGetResponses = {
    /**
     * Successful Response
     */
    200: SuggestionListView;
};

export type ModerationSuggestionsApiV1AdminModerationSuggestionsGetResponse = ModerationSuggestionsApiV1AdminModerationSuggestionsGetResponses[keyof ModerationSuggestionsApiV1AdminModerationSuggestionsGetResponses];

export type ListAllowlistApiV1AdminProviderAllowlistGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider-allowlist';
};

export type ListAllowlistApiV1AdminProviderAllowlistGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllowlistApiV1AdminProviderAllowlistGetError = ListAllowlistApiV1AdminProviderAllowlistGetErrors[keyof ListAllowlistApiV1AdminProviderAllowlistGetErrors];

export type ListAllowlistApiV1AdminProviderAllowlistGetResponses = {
    /**
     * Successful Response
     */
    200: AllowlistListView;
};

export type ListAllowlistApiV1AdminProviderAllowlistGetResponse = ListAllowlistApiV1AdminProviderAllowlistGetResponses[keyof ListAllowlistApiV1AdminProviderAllowlistGetResponses];

export type AddAllowlistEntryApiV1AdminProviderAllowlistPostData = {
    body: AllowlistCreateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider-allowlist';
};

export type AddAllowlistEntryApiV1AdminProviderAllowlistPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddAllowlistEntryApiV1AdminProviderAllowlistPostError = AddAllowlistEntryApiV1AdminProviderAllowlistPostErrors[keyof AddAllowlistEntryApiV1AdminProviderAllowlistPostErrors];

export type AddAllowlistEntryApiV1AdminProviderAllowlistPostResponses = {
    /**
     * Successful Response
     */
    201: AllowlistView;
};

export type AddAllowlistEntryApiV1AdminProviderAllowlistPostResponse = AddAllowlistEntryApiV1AdminProviderAllowlistPostResponses[keyof AddAllowlistEntryApiV1AdminProviderAllowlistPostResponses];

export type DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/admin/provider-allowlist/{entry_id}';
};

export type DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteError = DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteErrors[keyof DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteErrors];

export type DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: AllowlistListView;
};

export type DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteResponse = DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteResponses[keyof DeleteAllowlistEntryApiV1AdminProviderAllowlistEntryIdDeleteResponses];

export type UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutData = {
    body: AllowlistUpdateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/admin/provider-allowlist/{entry_id}';
};

export type UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutError = UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutErrors[keyof UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutErrors];

export type UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutResponses = {
    /**
     * Successful Response
     */
    200: AllowlistView;
};

export type UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutResponse = UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutResponses[keyof UpdateAllowlistEntryApiV1AdminProviderAllowlistEntryIdPutResponses];

export type WhoamiApiV1MeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type WhoamiApiV1MeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WhoamiApiV1MeGetError = WhoamiApiV1MeGetErrors[keyof WhoamiApiV1MeGetErrors];

export type WhoamiApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type WhoamiApiV1MeGetResponse = WhoamiApiV1MeGetResponses[keyof WhoamiApiV1MeGetResponses];

export type ListStoryRequestsApiV1StoryRequestsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Profile Id
         */
        profile_id?: string | null;
    };
    url: '/api/v1/story-requests';
};

export type ListStoryRequestsApiV1StoryRequestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStoryRequestsApiV1StoryRequestsGetError = ListStoryRequestsApiV1StoryRequestsGetErrors[keyof ListStoryRequestsApiV1StoryRequestsGetErrors];

export type ListStoryRequestsApiV1StoryRequestsGetResponses = {
    /**
     * Successful Response
     */
    200: StoryRequestListView;
};

export type ListStoryRequestsApiV1StoryRequestsGetResponse = ListStoryRequestsApiV1StoryRequestsGetResponses[keyof ListStoryRequestsApiV1StoryRequestsGetResponses];

export type CreateStoryRequestApiV1StoryRequestsPostData = {
    body: StoryRequestCreateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/story-requests';
};

export type CreateStoryRequestApiV1StoryRequestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStoryRequestApiV1StoryRequestsPostError = CreateStoryRequestApiV1StoryRequestsPostErrors[keyof CreateStoryRequestApiV1StoryRequestsPostErrors];

export type CreateStoryRequestApiV1StoryRequestsPostResponses = {
    /**
     * Successful Response
     */
    201: StoryRequestCreatedView;
};

export type CreateStoryRequestApiV1StoryRequestsPostResponse = CreateStoryRequestApiV1StoryRequestsPostResponses[keyof CreateStoryRequestApiV1StoryRequestsPostResponses];

export type CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostData = {
    body: StoryRequestAuthoredCreateBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/story-requests/authored';
};

export type CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostError = CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostErrors[keyof CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostErrors];

export type CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostResponses = {
    /**
     * Successful Response
     */
    201: StoryRequestAuthoredCreatedView;
};

export type CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostResponse = CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostResponses[keyof CreateAuthoredStoryRequestApiV1StoryRequestsAuthoredPostResponses];

export type ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostData = {
    body: StoryRequestApproveBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/story-requests/{request_id}/approve';
};

export type ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostError = ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostErrors[keyof ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostErrors];

export type ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: StoryRequestApprovedView;
};

export type ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostResponse = ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostResponses[keyof ApproveStoryRequestEndpointApiV1StoryRequestsRequestIdApprovePostResponses];

export type CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostData = {
    body: AuthoringPlanRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/story-requests/{request_id}/authoring-plan';
};

export type CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostError = CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostErrors[keyof CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostErrors];

export type CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostResponses = {
    /**
     * Successful Response
     */
    201: AuthoringPlanResponse;
};

export type CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostResponse = CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostResponses[keyof CreateAuthoringPlanApiV1StoryRequestsRequestIdAuthoringPlanPostResponses];

export type DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/story-requests/{request_id}/decline';
};

export type DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostError = DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostErrors[keyof DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostErrors];

export type DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostResponses = {
    /**
     * Successful Response
     */
    200: StoryRequestDeclinedView;
};

export type DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostResponse = DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostResponses[keyof DeclineStoryRequestEndpointApiV1StoryRequestsRequestIdDeclinePostResponses];
