#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Byron Williams <byronawilliams@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Fuzz Storybook schema validation, the pipeline's first structural gate.

Every LLM-generated story must pass ``Storybook.model_validate`` before the
deterministic validator layers or any human sees it, so this boundary takes
fully attacker-shaped input (the model's raw JSON). The contract fuzzed
here: malformed documents raise pydantic ``ValidationError`` and nothing
else, and any accepted document satisfies the model's own structural
invariants (unique ids, resolvable start node).

Seeded from ``tests/fixtures/storybook/`` (valid and invalid corpus; see
.clusterfuzzlite/build.sh), so mutation-based fuzzing starts from real
document shapes instead of raw noise.

Run locally (requires the fuzzing toolchain):
    uv pip install atheris
    python fuzz/fuzz_storybook_validation.py -max_total_time=60

The check logic is importable without atheris so the unit suite can drive
it directly (tests/unit/test_fuzz_harnesses.py).
"""

from __future__ import annotations

import json
import sys

from pydantic import ValidationError

from cyo_adventure.storybook.models import Storybook

# Same interpreter-recursion guard as fuzz_condition_evaluator.py: deep
# nesting exhausts Python's stack inside json/pydantic, which is not a
# storybook-schema bug.
_MAX_NESTING_HINT = 200


def check_storybook_text(text: str) -> None:
    """Drive Storybook.model_validate for one fuzzed input.

    Args:
        text: Candidate JSON text for a Storybook document.

    Raises:
        AssertionError: If an accepted document violates its own invariants.
        Exception: Any non-``ValidationError`` escaping validation is a
            finding.
    """
    if text.count("{") + text.count("[") > _MAX_NESTING_HINT:
        return
    try:
        parsed = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if not isinstance(parsed, dict):
        return
    try:
        book = Storybook.model_validate(parsed)
    except ValidationError:
        return  # correctly rejected malformed document
    node_ids = [node.id for node in book.nodes]
    assert book.start_node in node_ids, "accepted book with dangling start_node"
    assert len(node_ids) == len(set(node_ids)), "accepted book with duplicate ids"


def test_one_input(data: bytes) -> None:
    """Atheris entry point: decode fuzzed bytes and run the contract check.

    Args:
        data: Random bytes generated by the fuzzer.
    """
    check_storybook_text(data.decode("utf-8", errors="replace"))


def main() -> None:
    """Initialize and run the fuzzer (atheris imported here on purpose)."""
    import atheris  # noqa: PLC0415  # fuzzing-toolchain-only dependency

    # atheris ships no type stubs and is only installed in the fuzz toolchain.
    atheris.instrument_all()  # pyright: ignore[reportAttributeAccessIssue]
    atheris.Setup(sys.argv, test_one_input)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
