#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Byron Williams <byronawilliams@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Fuzz the storybook condition DSL: validation gate plus evaluator totality.

The condition evaluator (ADR-006, in-house) decides which choices a child
reader sees, so its contract is security-relevant: ``validate_condition``
must reject every malformed shape with ``ValueError``, and any condition it
accepts must evaluate to a ``bool`` for any variable state without raising.
This harness feeds fuzzed JSON through exactly that contract; any other
exception (or a non-bool result) is a crash for the fuzzer to report.

Seeded from ``schema/conformance/conditions.json`` (see
.clusterfuzzlite/build.sh), so mutation-based fuzzing starts from every
operator the DSL supports.

Run locally (requires the fuzzing toolchain):
    uv pip install atheris
    python fuzz/fuzz_condition_evaluator.py -max_total_time=60

The check logic is importable without atheris so the unit suite can drive
it directly (tests/unit/test_fuzz_harnesses.py).
"""

from __future__ import annotations

import json
import sys

from cyo_adventure.storybook.condition import validate_condition
from cyo_adventure.storybook.evaluator import VarState, evaluate

# Variable states the totality check evaluates against: empty, booleans,
# in-range ints, and out-of-band values a hostile document could reference.
_VAR_STATES: tuple[VarState, ...] = (
    {},
    {"a": 1, "b": 0, "courage": 5, "trust": True},
    {"a": True, "b": False, "courage": -1, "trust": 6},
)

# json.loads (and any recursive walker) hits Python's recursion limit on
# deeply nested input long before project logic runs. That is an interpreter
# bound, not a condition-DSL bug, so inputs past this structural depth are
# out of scope for this harness rather than a permanent red herring crash.
_MAX_NESTING_HINT = 200


def check_condition_text(text: str) -> None:
    """Drive the validate-then-evaluate contract for one fuzzed input.

    Args:
        text: Candidate JSON text for a condition object.

    Raises:
        AssertionError: If an accepted condition evaluates to a non-bool.
        Exception: Any non-``ValueError`` escaping the DSL is a finding.
    """
    if text.count("{") + text.count("[") > _MAX_NESTING_HINT:
        return
    try:
        parsed = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return
    if not isinstance(parsed, dict):
        return
    try:
        validate_condition(parsed)
    except ValueError:
        return  # correctly rejected malformed condition
    for var_state in _VAR_STATES:
        result = evaluate(parsed, var_state)
        assert isinstance(result, bool), (
            f"evaluate returned {type(result).__name__} for accepted condition"
        )


def test_one_input(data: bytes) -> None:
    """Atheris entry point: decode fuzzed bytes and run the contract check.

    Args:
        data: Random bytes generated by the fuzzer.
    """
    check_condition_text(data.decode("utf-8", errors="replace"))


def main() -> None:
    """Initialize and run the fuzzer (atheris imported here on purpose)."""
    import atheris  # noqa: PLC0415  # fuzzing-toolchain-only dependency

    # atheris ships no type stubs and is only installed in the fuzz toolchain.
    atheris.instrument_all()  # pyright: ignore[reportAttributeAccessIssue]
    atheris.Setup(sys.argv, test_one_input)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
