#!/usr/bin/env python3
"""
Fuzz target for input validation functions.

This module uses Atheris (Google's Python fuzzing engine) to test
input validation and parsing functions for edge cases and crashes.

Usage:
    # Run locally with Atheris
    python fuzz_input_validation.py

    # Run via ClusterFuzzLite (in CI)
    # The CI workflow handles this automatically

Reference:
    https://github.com/google/atheris
    https://google.github.io/clusterfuzzlite/
"""

from __future__ import annotations

import contextlib
import sys

import atheris

# TODO: Import the module functions you want to fuzz
# Example: from cyo_adventure.validation import validate_input


def test_one_input(data: bytes) -> None:
    """
    Test a single fuzzing input.

    This function is called by Atheris with random byte data.
    Convert the data to the appropriate format and call your
    validation functions.

    Args:
        data: Random bytes generated by the fuzzer
    """
    fdp = atheris.FuzzedDataProvider(data)

    # Example: Fuzz string input validation
    # TODO: Import your validation functions and call them here
    # TODO: Add assertions to verify expected behavior
    with contextlib.suppress(ValueError, TypeError):
        _ = fdp.ConsumeUnicodeNoSurrogates(1024)


def main() -> None:
    """Initialize and run the fuzzer."""
    # Setup atheris with automatic instrumentation
    atheris.instrument_all()
    atheris.Setup(sys.argv, test_one_input)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
