"""Build the D-7 rig: does a shared *wordless* plan avoid the D-2 convergence?

This is the last untested repair from `AL-208` and it is the central claim of
[the architecture re-specification](../../architecture-respecification-2026-08-10.md).

**The claim.** A narrative contract mixes two things and shares both. Split it:

- the **structural stratum**, topology plus `entry_state`, `establishes`,
  `forbids`, fact *names* and `world_recipe` categories. Carries no prose an
  author ever reads as prose. `AL-197` and `AL-212` prove it does not determine
  the decision, and that long-standing weakness becomes its licence: sharing it
  cannot make the decisions repeat.
- the **decisional stratum**, `premise`, `choice_semantics`, `beat_hint` and
  `affect`. This is at once where D-3b locates the property readers respond to
  and where D-6 locates the fingerprint. Generated per book.

**What D-6 already settled, and what it left.** D-6 tested the two repairs that
keep one shared decisional stratum and change its wording: flatten it
(`neutral`, 11.8 per 1000) or tell authors to diverge from it (`diverge`, 13.6),
against `verbatim` at 17.2, a budget of 4.0 and a measured generator floor of
3.3. Neither is close. The repair that removes the shared decisional stratum
entirely was never run.

(Those three anchors read 11.4, 12.9 and 16.9 when this file was written. They
were re-derived on 2026-08-11: the published figures were label-inclusive while
being described as body-only. The prediction and falsifier below were fixed
against the old numbers and are left exactly as written, because both are
stated as thresholds against the 4.0 budget, which did not move.)

**What `AL-223` predicts.** Convergence keys on *sentence identity*, not on
lexical similarity: two contracts sharing 118 shared 4-grams per 1000 but zero
sentences filled at 2.9, the floor. Two independently generated decisional
strata share no sentences by construction, so this should land at the floor.

**And what would make it fail, which is the point of running it.** The
structural stratum is shared here in a way it was not in any earlier arm: the
same fact names, the same per-node obligations, the same device categories. If
*that* leaks into prose, the whole stratification idea is wrong and the only
remaining option is one full contract per book, which is what the pilot did and
what makes the capital cost scale with readership rather than catalog size
(`AL-213`).

**Design.** One structural stratum from `contract_v2`. Two decisional strata,
generated by authors who see the structural stratum and their own binding and
**never a sibling's decisional stratum**, which is the mechanism `AL-222`
measured (withholding, not instructing: 126.7 per 1000 down to 1.0). Two
bindings held constant, `armC` and `armD`, the pilot's own. Two fills.

**Outcome is the guard battery**, so no rater is involved and the result cannot
be argued with. Anchors on the same scale: generator floor 3.3, budget 4.0,
pilot's separate contracts 2.9, D-6 `neutral` 11.8, D-6 `verbatim` 17.2.

**Prediction, fixed before any artifact exists:** at or under 4.0.

**Falsifier, fixed before any artifact exists:** materially above 4.0 means the
shared structural stratum leaks wording on its own, and section 2 of the
architecture re-specification should be discarded rather than defended.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

HERE = Path(__file__).parent
SRC = HERE.parent / "obligation-variance"

# Everything the decisional stratum owns, and therefore everything stripped from
# the shared half.
#
# **The list is longer than the architecture re-specification said, and finding
# that out is the first result this rig produced.** Section 2 named
# `choice_semantics` and `beat_hint`, and 2.1 added `premise`. Building the
# stratum surfaced two more prose-bearing fields nobody had counted:
#
# - `constraints`, on 25 of 26 nodes, which is choice semantics under another
#   name: "three genuinely different virtues to lead with: patience,
#   self-reliance, humility; no option is the smart one".
# - `mechanisms`, on all 8 endings, which restates `premise.resolution_space`
#   verbatim: "the archive teaches them what the trial was really testing".
#
# Re-tracing D-6's shared grams against these shows why its repairs only bought
# a third: `constraints` matches 21, 19 and 18 grams across the three
# conditions, barely moving, because **no condition touched it**, while
# `choice_semantics` falls 18, 13, 10. D-6 repaired one prose field of five.
#
# `merge_note` goes too. It is closure guidance, but it spells the intersection
# out in prose ("the challenge exists, the friends accepted it"), and
# `entry_state` already carries the same content formally.
# `affect` goes as prose about how a beat should feel; the safety envelope's
# `forbid_affect` list stays, being a constraint rather than a description.
_DECISIONAL_NODE = (
    "choice_semantics",
    "beat_hint",
    "affect",
    "constraints",
    "mechanisms",
    "merge_note",
)
_DECISIONAL_TOP = ("premise", "label_styles")


def _load(path: Path) -> dict[str, Any]:
    """Load a JSON object from path."""
    return cast("dict[str, Any]", json.loads(path.read_text(encoding="utf-8")))


def structural(contract: dict[str, Any]) -> dict[str, Any]:
    """Return the shareable half: structure, obligations and names, no prose.

    Fact *definitions* are deliberately kept. They are one-line glosses of what
    a fact name means, an author cannot honour an obligation without them, and
    they are the strongest test available of the stratification claim: if
    sharing them alone drives convergence, no wordless plan exists at all.

    Args:
        contract: The decoded full narrative contract.

    Returns:
        The structural stratum, safe to share across books.
    """
    out = json.loads(json.dumps(contract))
    for key in _DECISIONAL_TOP:
        out.pop(key, None)
    for node in cast("dict[str, Any]", out["nodes"]).values():
        for key in _DECISIONAL_NODE:
            cast("dict[str, Any]", node).pop(key, None)
    out["stratum"] = "structural"
    return out


def main() -> int:
    """Write the shared structural stratum and report what it still carries."""
    contract = _load(SRC / "contract_v2.json")
    stratum = structural(contract)
    (HERE / "structural.json").write_text(
        json.dumps(stratum, indent=1, ensure_ascii=False), encoding="utf-8"
    )

    nodes = cast("dict[str, Any]", stratum["nodes"])
    print(f"structural stratum: {len(nodes)} nodes, {len(stratum['facts'])} facts")
    print(f"  top-level keys : {sorted(stratum)}")
    print(f"  per-node keys  : {sorted({k for n in nodes.values() for k in n})}")
    node_blob = json.dumps(nodes)
    for gone in (*_DECISIONAL_NODE, *_DECISIONAL_TOP):
        present = gone in node_blob or gone in set(stratum)
        print(f"  {gone + ' removed':28s} {not present}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
