"""add concept and generation_job

Revision ID: 78336bfff81e
Revises: ddf3f6d1346f
Create Date: 2026-06-22 08:35:22.949787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78336bfff81e'
down_revision: Union[str, Sequence[str], None] = 'ddf3f6d1346f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_family_id'), 'concept', ['family_id'], unique=False)
    op.create_table('generation_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storybook_id', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_job_concept_id'), 'generation_job', ['concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_job_concept_id'), table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_index(op.f('ix_concept_family_id'), table_name='concept')
    op.drop_table('concept')
    # ### end Alembic commands ###
