"""initial schema

Revision ID: ddf3f6d1346f
Revises:
Create Date: 2026-06-21 19:26:57.830674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf3f6d1346f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('age_band', sa.String(length=16), nullable=False),
    sa.Column('reading_level_cap', sa.Float(), nullable=False),
    sa.Column('allowed_content_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_profile_family_id'), 'child_profile', ['family_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('authn_subject', sa.String(length=255), nullable=False),
    sa.Column('child_profile_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profile.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_authn_subject'), 'user', ['authn_subject'], unique=True)
    op.create_index(op.f('ix_user_family_id'), 'user', ['family_id'], unique=False)
    op.create_table('storybook',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('current_published_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storybook_family_id'), 'storybook', ['family_id'], unique=False)
    op.create_table('storybook_version',
    sa.Column('storybook_id', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blob_ref', sa.String(length=512), nullable=True),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moderation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybook.id'], ),
    sa.PrimaryKeyConstraint('storybook_id', 'version')
    )
    op.create_table('reading_state',
    sa.Column('child_profile_id', sa.Uuid(), nullable=False),
    sa.Column('storybook_id', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_node', sa.String(length=120), nullable=False),
    sa.Column('var_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visit_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('save_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_revision', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.String(length=64), nullable=True),
    sa.Column('updated_by_device_id', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profile.id'], ),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybook.id'], ),
    sa.ForeignKeyConstraint(['storybook_id', 'version'], ['storybook_version.storybook_id', 'storybook_version.version'], ),
    sa.PrimaryKeyConstraint('child_profile_id', 'storybook_id')
    )
    op.create_table('completion',
    sa.Column('child_profile_id', sa.Uuid(), nullable=False),
    sa.Column('storybook_id', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ending_id', sa.String(length=120), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profile.id'], ),
    sa.ForeignKeyConstraint(['storybook_id', 'version'], ['storybook_version.storybook_id', 'storybook_version.version'], ),
    sa.PrimaryKeyConstraint('child_profile_id', 'storybook_id', 'version', 'ending_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion')
    op.drop_table('reading_state')
    op.drop_table('storybook_version')
    op.drop_index(op.f('ix_storybook_family_id'), table_name='storybook')
    op.drop_table('storybook')
    op.drop_index(op.f('ix_user_family_id'), table_name='user')
    op.drop_index(op.f('ix_user_authn_subject'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_child_profile_family_id'), table_name='child_profile')
    op.drop_table('child_profile')
    op.drop_table('family')
    # ### end Alembic commands ###
