#!/usr/bin/env python
"""Skeleton catalog census: the one place a catalog count comes from.

    uv run python scripts/catalog_census.py                  # human-readable report
    uv run python scripts/catalog_census.py --json           # machine-readable
    uv run python scripts/catalog_census.py --write          # regenerate the doc
    uv run python scripts/catalog_census.py --check          # fail if the doc is stale

Why this exists
---------------
The figures "61 graphs", "11,458 nodes" and "3-4 skeletons per cell" were
exactly correct on 2026-08-12 (commit ``154d44f``) and were then copied by hand
into four documents while the catalog grew to 84 shells and 15,470 nodes.
Nothing flagged the drift, because every copy agreed with every other copy
(``AL-551``, ``UW-G24``).

Separately, three independent recomputations of skeletons-per-cell disagreed
with each other: one grouped on ``(band, length)`` and ignored style, one read
a ``style`` metadata key where the key is ``narrative_style``, and one skipped
the deprecated and series-continuation exclusions (``AL-554``). So this module
computes NOTHING itself. Shell identity comes from
``generation.skeleton.is_sidecar``, commissioned words from
``commissioned_words_by_node``, and cell membership from the real selector via
``analyze_sibling_exposure.iter_cells``, which wraps
``skeleton_match.candidates_for_cell``. If those disagree with this report, the
report is wrong by construction, which is the intended failure direction.

The coverage grid is the OFFERED grid
-------------------------------------
Coverage is reported against ``band_profile.offered_cells()`` and not against
any cross-product of the band, length, and style enums. Three separate
analyses invented a grid here and each reported empty cells no request can
reach (``AL-554``). The rationale is stated once, in ``_GRID_RATIONALE``, and
rendered into the generated document from there.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path, PurePath
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cyo_adventure.generation.skeleton import (
    commissioned_words_by_node,
    is_sidecar,
)
from cyo_adventure.storybook.models import AgeBand, age_band_rank
from cyo_adventure.validator.band_profile import offered_cells
from scripts.analyze_sibling_exposure import iter_cells

_REPO_ROOT = Path(__file__).resolve().parent.parent
SKELETON_ROOT = Path("skeletons")
GENERATED_DOC = Path("docs/planning/catalog-census.md")

_MARKER = "<!-- generated by scripts/catalog_census.py; do not edit by hand -->"

# The single statement of why coverage is reported against the offered grid.
# It was written three times in this file (module docstring, an inline comment,
# and the rendered document) and three hand-kept copies of one rationale is the
# defect this script exists to remove (`UW-G24`).
_GRID_RATIONALE = (
    "The coverage grid is the set of cells ADR-011 **offers**",
    "(`validator/band_profile.py::offered_cells`), not a cross-product of the",
    "band, length, and style enums. A combination the matrix does not sell",
    "(a 3-5 long, an 8-11 gamebook) is not an uncovered cell; no request can",
    "reach it. Reporting coverage against an invented grid manufactures gaps",
    "that do not exist (`AL-554`).",
)


def _band_rank(band: str) -> int:
    """Return the reading-age rank of a band directory name.

    Bands sort by reading age, not lexicographically: "10-13" must not precede
    "3-5" in a table a person reads top to bottom. The ordering is defined once
    in ``storybook.models`` and is read from there rather than re-derived, so a
    new band cannot land in two different orders in two different files.

    Args:
        band: A band directory name, such as ``"8-11"``.

    Returns:
        The rank used to sort per-band rows.

    Raises:
        ValueError: If ``band`` is not an age band, which means a stray
            directory is sitting in the skeleton catalog.
    """
    try:
        return age_band_rank(AgeBand(band))
    except ValueError as exc:
        valid = ", ".join(b.value for b in AgeBand)
        msg = f"{band!r} is not an age band; expected one of: {valid}"
        raise ValueError(msg) from exc


@dataclass(frozen=True)
class Shell:
    """One skeleton shell, with the three quantities documents quote.

    ``path`` is a `PurePath` rather than a `Path` because the census only ever
    renders it as text (`_doc_path`) and never reads through it. Saying so lets
    a test hand this a `PureWindowsPath` on a Linux runner, which is the only
    way the separator regression can be caught anywhere but a Windows job.
    """

    path: PurePath
    band: str
    nodes: int
    commissioned_words: int
    production_eligible: bool


@dataclass
class BandRow:
    """Per-band totals.

    ``shells`` and ``nodes`` are derived from ``node_counts`` rather than
    accumulated alongside it, so the three cannot disagree.
    """

    band: str
    words: int = 0
    node_counts: list[int] = field(default_factory=list)

    @property
    def shells(self) -> int:
        """Return the number of shells in this band."""
        return len(self.node_counts)

    @property
    def nodes(self) -> int:
        """Return the total node count across this band's shells."""
        return sum(self.node_counts)


def load_shells(root: Path = SKELETON_ROOT) -> list[Shell]:
    """Return every true skeleton shell under ``root``, sidecars excluded.

    Args:
        root: The skeleton catalog root.

    Returns:
        One Shell per non-sidecar ``*.json`` file, sorted by path.

    Raises:
        FileNotFoundError: If ``root`` does not exist, which almost always
            means the caller is not at the repository root.
        ValueError: If a non-sidecar ``*.json`` file is not a JSON object, or
            is one but has no ``nodes`` list. Skipping either would silently
            undercount the catalog, which is the exact drift this census
            exists to detect (`UW-G24`).
    """
    if not root.is_dir():
        msg = f"skeleton root {root} not found; run from the repository root"
        raise FileNotFoundError(msg)
    shells: list[Shell] = []
    for path in sorted(root.rglob("*.json")):
        if is_sidecar(path):
            continue
        decoded: object = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(decoded, dict):
            msg = (
                f"{path} has a {type(decoded).__name__} at its JSON root, not an "
                "object; a shell must be a mapping"
            )
            raise ValueError(msg)
        story: dict[str, object] = decoded
        metadata = story.get("metadata")
        eligible = (
            metadata.get("production_eligible") is True
            if isinstance(metadata, dict)
            else False
        )
        nodes = story.get("nodes")
        if not isinstance(nodes, list):
            msg = (
                f"{path} is not a sidecar but has no 'nodes' list; "
                "the census refuses to silently undercount the catalog"
            )
            raise ValueError(msg)
        shells.append(
            Shell(
                path=path,
                band=path.parent.name,
                nodes=len(nodes),
                commissioned_words=sum(commissioned_words_by_node(story).values()),
                production_eligible=eligible,
            )
        )
    return shells


def _doc_path(path: PurePath) -> str:
    """Return *path* as it should appear in the generated document.

    Always forward-slashed, never the host separator. The census is rendered
    into a committed document that `test_generated_doc_is_current` compares
    byte for byte, so `str(path)` makes the doc drift on Windows against the
    same doc generated on Linux, and the census reports a repository location
    rather than a location on whichever machine happened to run it.

    Args:
        path: A path to a catalog file.

    Returns:
        The path with ``/`` separators on every platform.
    """
    return path.as_posix()


def census() -> dict[str, Any]:
    """Compute the whole census of the live skeleton catalog.

    This deliberately takes no root parameter. Cell coverage comes from
    ``iter_cells()``, which reads ``skeleton_match._SKELETON_ROOT`` and cannot
    be pointed elsewhere, so a ``root`` argument could only scope half the
    report: totals would follow the caller while coverage silently kept
    describing the real catalog, and the two halves would be blended into one
    object that looks authoritative and is not.

    Returns:
        A JSON-serializable census: totals, per-band rows, cell coverage, and
        the two "largest" answers (which are different books, so a document
        must say which one it means).

    Raises:
        ValueError: If the process is not at the repository root, if the
            catalog holds no shells, or if no shell covers any offered cell.
            The latter two would otherwise surface as a bare
            ``ValueError``/``IndexError`` from ``max()``/``sizes[0]``.
    """
    # Both halves of this report must read the same catalog. `load_shells`
    # honours a relative root, but `iter_cells` reaches `skeleton_match`, whose
    # root is a module-level relative constant with no override. Anchoring only
    # the first half would leave the two halves describing different catalogs,
    # so the working directory is checked instead of half-fixed (`UW-G24`).
    if Path.cwd() != _REPO_ROOT:
        msg = (
            f"run this from the repository root ({_REPO_ROOT}); "
            f"the working directory is {Path.cwd()}. Cell coverage comes from "
            "skeleton_match, which resolves its catalog root relative to the "
            "working directory, so any other directory yields a census whose "
            "totals and coverage describe different catalogs."
        )
        raise ValueError(msg)
    shells = load_shells()
    if not shells:
        msg = f"no skeleton shells found under {SKELETON_ROOT}; nothing to report"
        raise ValueError(msg)
    bands: dict[str, BandRow] = {}
    for shell in shells:
        row = bands.setdefault(shell.band, BandRow(band=shell.band))
        row.words += shell.commissioned_words
        row.node_counts.append(shell.nodes)

    # Why this grid and not a cross-product: see `_GRID_RATIONALE`.
    offered = offered_cells()
    populated = {
        (c.band, c.length, style): c.slugs
        for c in iter_cells()
        for style in c.style.split("+")
        if c.slugs
    }
    covered_keys = offered & populated.keys()
    if not covered_keys:
        msg = (
            f"no shell covers any of the {len(offered)} offered cells; "
            "the catalog and the offered grid have diverged completely"
        )
        raise ValueError(msg)
    sizes = sorted(len(populated[k]) for k in covered_keys)

    by_nodes = max(shells, key=lambda s: s.nodes)
    by_words = max(shells, key=lambda s: s.commissioned_words)

    return {
        "totals": {
            "shells": len(shells),
            "nodes": sum(s.nodes for s in shells),
            "commissioned_words": sum(s.commissioned_words for s in shells),
        },
        "bands": [
            {
                "band": r.band,
                "shells": r.shells,
                "nodes": r.nodes,
                "commissioned_words": r.words,
                "min_nodes": min(r.node_counts),
                "median_nodes": statistics.median(r.node_counts),
                "max_nodes": max(r.node_counts),
            }
            for r in sorted(bands.values(), key=lambda r: _band_rank(r.band))
        ],
        "cells": {
            # Two distinct quantities were both being read as "production
            # eligible": the number of shells that DECLARE the flag, and the
            # smaller number the selector can actually reach through a cell
            # ADR-011 offers. They differ, so both are reported and each says
            # which it is (`UW-G24`).
            "declared_production_eligible": sum(
                1 for s in shells if s.production_eligible
            ),
            "reachable_in_offered_cells": len(
                {s for k in covered_keys for s in populated[k]}
            ),
            "offered": len(offered),
            "covered": len(covered_keys),
            "uncovered": len(offered) - len(covered_keys),
            "min_per_covered_cell": sizes[0],
            "max_per_covered_cell": sizes[-1],
            "median_per_covered_cell": statistics.median(sizes),
        },
        "largest": {
            "by_nodes": {
                "path": _doc_path(by_nodes.path),
                "nodes": by_nodes.nodes,
                "commissioned_words": by_nodes.commissioned_words,
            },
            "by_commissioned_words": {
                "path": _doc_path(by_words.path),
                "nodes": by_words.nodes,
                "commissioned_words": by_words.commissioned_words,
            },
        },
    }


def render(data: dict[str, Any]) -> str:
    """Render the census as the generated Markdown document.

    Args:
        data: A census mapping from :func:`census`.

    Returns:
        The full document text, including the do-not-edit marker.
    """
    t, c, lg = data["totals"], data["cells"], data["largest"]
    # Bound out of the list literal below: inside a collection, a two-line
    # implicit f-string concatenation is `ISC004`, and it reads as a missing
    # comma, which is the defect the rule exists to catch.
    declared = c["declared_production_eligible"]
    reachable = c["reachable_in_offered_cells"]
    lines = [
        "# Skeleton catalog census",
        "",
        _MARKER,
        "",
        "Regenerate with `uv run python scripts/catalog_census.py --write`.",
        "Cite this page rather than transcribing a number from it into prose:",
        "every count below was, at some point, exactly correct somewhere else",
        "and then went stale in place (`AL-551`, `UW-G24`).",
        "",
        "## Totals",
        "",
        "| Quantity | Value |",
        "| --- | ---: |",
        f"| Shells (sidecars excluded) | {t['shells']:,} |",
        f"| Nodes | {t['nodes']:,} |",
        f"| Commissioned words | {t['commissioned_words']:,} |",
        f"| Shells declaring `production_eligible` | {declared:,} |",
        f"| ...of those, reachable in an offered cell | {reachable:,} |",
        "",
        "## By band",
        "",
        "| Band | Shells | Nodes | Commissioned words | Nodes min / median / max |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    lines += [
        (
            f"| {b['band']} | {b['shells']} | {b['nodes']:,} | "
            f"{b['commissioned_words']:,} | "
            f"{b['min_nodes']} / {b['median_nodes']:g} / {b['max_nodes']} |"
        )
        for b in data["bands"]
    ]
    lines += [
        "",
        "## Cell coverage",
        "",
        *_GRID_RATIONALE,
        "",
        "| Quantity | Value |",
        "| --- | ---: |",
        f"| Offered cells | {c['offered']} |",
        f"| Covered | {c['covered']} |",
        f"| Uncovered | {c['uncovered']} |",
        "",
        (
            f"Per covered cell: {c['min_per_covered_cell']} to "
            f"{c['max_per_covered_cell']} skeletons, median "
            f"{c['median_per_covered_cell']:g}."
        ),
        "",
        "## Largest graph",
        "",
        "The node maximum and the commissioned-word maximum are **different",
        "books**, which is how a node count once became a word count.",
        "",
        "| Superlative | Skeleton | Nodes | Commissioned words |",
        "| --- | --- | ---: | ---: |",
        (
            f"| Most nodes | `{lg['by_nodes']['path']}` | "
            f"{lg['by_nodes']['nodes']} | "
            f"{lg['by_nodes']['commissioned_words']:,} |"
        ),
        (
            f"| Most commissioned words | "
            f"`{lg['by_commissioned_words']['path']}` | "
            f"{lg['by_commissioned_words']['nodes']} | "
            f"{lg['by_commissioned_words']['commissioned_words']:,} |"
        ),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run the census CLI.

    Args:
        argv: Argument vector; defaults to ``sys.argv[1:]``.

    Returns:
        0 on success, 1 when ``--check`` finds the generated doc stale or
        missing.
    """
    parser = argparse.ArgumentParser(
        description="Skeleton catalog census: the one place a count comes from."
    )
    parser.add_argument("--json", action="store_true", help="emit JSON")
    # Mutually exclusive: --write was tested first, so `--check --write` used to
    # rewrite the tracked document and exit 0. Asking for a check must never
    # perform a write.
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate the doc")
    mode.add_argument(
        "--check", action="store_true", help="fail if the generated doc is stale"
    )
    args = parser.parse_args(argv)

    data = census()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0

    rendered = render(data)
    regenerate = "Run: uv run python scripts/catalog_census.py --write"
    if args.write:
        GENERATED_DOC.write_text(rendered, encoding="utf-8")
        print(f"wrote {GENERATED_DOC}")
        return 0
    if args.check:
        if not GENERATED_DOC.exists():
            print(
                f"missing: {GENERATED_DOC} has never been generated. {regenerate}",
                file=sys.stderr,
            )
            return 1
        if GENERATED_DOC.read_text(encoding="utf-8") != rendered:
            print(
                f"stale: {GENERATED_DOC} does not match the catalog. {regenerate}",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {GENERATED_DOC} matches the catalog")
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
