#!/usr/bin/env python
"""Skeleton catalog census: the one place a catalog count comes from.

    uv run python scripts/catalog_census.py                  # human-readable report
    uv run python scripts/catalog_census.py --json           # machine-readable
    uv run python scripts/catalog_census.py --write          # regenerate the doc
    uv run python scripts/catalog_census.py --check          # fail if the doc is stale

Why this exists
---------------
The figures "61 graphs", "11,458 nodes" and "3-4 skeletons per cell" were
exactly correct on 2026-08-12 (commit ``154d44f``) and were then copied by hand
into four documents while the catalog grew to 84 shells and 15,470 nodes.
Nothing flagged the drift, because every copy agreed with every other copy
(``AL-551``, ``UW-G24``).

Separately, three independent recomputations of skeletons-per-cell disagreed
with each other: one grouped on ``(band, length)`` and ignored style, one read
a ``style`` metadata key where the key is ``narrative_style``, and one skipped
the deprecated and series-continuation exclusions (``AL-554``). So this module
computes NOTHING itself. Shell identity comes from
``generation.skeleton.is_sidecar``, commissioned words from
``commissioned_words_by_node``, and cell membership from the real selector via
``analyze_sibling_exposure.iter_cells``, which wraps
``skeleton_match.candidates_for_cell``. If those disagree with this report, the
report is wrong by construction, which is the intended failure direction.

The coverage grid is the OFFERED grid
-------------------------------------
Coverage is reported against ``band_profile.offered_cells()``, the 18 cells
ADR-011 actually sells, and not against any cross-product of the band, length,
and style enums. Three separate analyses invented a grid here (36 raw
combinations, 24 "semantic" cells, 22 collapsed selector rows) and each
reported empty cells that no request can reach, because a 3-5 long and an
8-11 gamebook are not offered. Against the offered grid the catalog has no
uncovered cells, and the manufactured gap disappears (``AL-554``).
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cyo_adventure.generation.skeleton import (
    commissioned_words_by_node,
    is_sidecar,
)
from cyo_adventure.storybook.models import AgeBand
from cyo_adventure.validator.band_profile import offered_cells
from scripts.analyze_sibling_exposure import iter_cells

SKELETON_ROOT = Path("skeletons")

# Bands sort by reading age, not lexicographically: "10-13" must not precede
# "3-5" in a table a person reads top to bottom.
_BAND_ORDER = {band.value: i for i, band in enumerate(AgeBand)}
GENERATED_DOC = Path("docs/planning/catalog-census.md")

_MARKER = "<!-- generated by scripts/catalog_census.py; do not edit by hand -->"


@dataclass(frozen=True)
class Shell:
    """One skeleton shell, with the three quantities documents quote."""

    path: Path
    band: str
    nodes: int
    commissioned_words: int


@dataclass
class BandRow:
    """Per-band totals."""

    band: str
    shells: int = 0
    nodes: int = 0
    words: int = 0
    node_counts: list[int] = field(default_factory=list)


def load_shells(root: Path = SKELETON_ROOT) -> list[Shell]:
    """Return every true skeleton shell under ``root``, sidecars excluded.

    Args:
        root: The skeleton catalog root.

    Returns:
        One Shell per non-sidecar ``*.json`` file, sorted by path.

    Raises:
        FileNotFoundError: If ``root`` does not exist, which almost always
            means the caller is not at the repository root.
    """
    if not root.is_dir():
        msg = f"skeleton root {root} not found; run from the repository root"
        raise FileNotFoundError(msg)
    shells: list[Shell] = []
    for path in sorted(root.rglob("*.json")):
        if is_sidecar(path):
            continue
        story: dict[str, object] = json.loads(path.read_text())
        nodes = story.get("nodes")
        if not isinstance(nodes, list):
            continue
        shells.append(
            Shell(
                path=path,
                band=path.parent.name,
                nodes=len(nodes),
                commissioned_words=sum(commissioned_words_by_node(story).values()),
            )
        )
    return shells


def census(root: Path = SKELETON_ROOT) -> dict[str, Any]:
    """Compute the whole census.

    Args:
        root: The skeleton catalog root.

    Returns:
        A JSON-serializable census: totals, per-band rows, cell coverage under
        both conventions, and the two "largest" answers (which are different
        books, so a document must say which one it means).
    """
    shells = load_shells(root)
    bands: dict[str, BandRow] = {}
    for shell in shells:
        row = bands.setdefault(shell.band, BandRow(band=shell.band))
        row.shells += 1
        row.nodes += shell.nodes
        row.words += shell.commissioned_words
        row.node_counts.append(shell.nodes)

    # The coverage grid is the set of cells ADR-011 actually OFFERS, which is
    # `band_profile.offered_cells()`, not any cross-product of the three enums.
    # Three separate analyses invented a grid here (36 raw combinations, 24
    # "semantic" cells, 22 collapsed selector rows) and each reported empty
    # cells that no request can reach, because a combination like a 3-5 long or
    # an 8-11 gamebook is not sold. Against the offered grid there are no empty
    # cells to report.
    offered = offered_cells()
    populated = {
        (c.band, c.length, style): c.slugs
        for c in iter_cells()
        for style in c.style.split("+")
        if c.slugs
    }
    covered_keys = offered & populated.keys()
    sizes = sorted(len(populated[k]) for k in covered_keys)

    by_nodes = max(shells, key=lambda s: s.nodes)
    by_words = max(shells, key=lambda s: s.commissioned_words)

    return {
        "totals": {
            "shells": len(shells),
            "nodes": sum(s.nodes for s in shells),
            "commissioned_words": sum(s.commissioned_words for s in shells),
        },
        "bands": [
            {
                "band": r.band,
                "shells": r.shells,
                "nodes": r.nodes,
                "commissioned_words": r.words,
                "min_nodes": min(r.node_counts),
                "median_nodes": int(statistics.median(r.node_counts)),
                "max_nodes": max(r.node_counts),
            }
            for r in sorted(bands.values(), key=lambda r: _BAND_ORDER[r.band])
        ],
        "cells": {
            "production_eligible_shells": len(
                {s for k in covered_keys for s in populated[k]}
            ),
            "offered": len(offered),
            "covered": len(covered_keys),
            "uncovered": len(offered) - len(covered_keys),
            "min_per_covered_cell": sizes[0],
            "max_per_covered_cell": sizes[-1],
            "median_per_covered_cell": statistics.median(sizes),
        },
        "largest": {
            "by_nodes": {
                "path": str(by_nodes.path),
                "nodes": by_nodes.nodes,
                "commissioned_words": by_nodes.commissioned_words,
            },
            "by_commissioned_words": {
                "path": str(by_words.path),
                "nodes": by_words.nodes,
                "commissioned_words": by_words.commissioned_words,
            },
        },
    }


def render(data: dict[str, Any]) -> str:
    """Render the census as the generated Markdown document.

    Args:
        data: A census mapping from :func:`census`.

    Returns:
        The full document text, including the do-not-edit marker.
    """
    t, c, lg = data["totals"], data["cells"], data["largest"]
    lines = [
        "# Skeleton catalog census",
        "",
        _MARKER,
        "",
        "Regenerate with `uv run python scripts/catalog_census.py --write`.",
        "Cite this page rather than transcribing a number from it into prose:",
        "every count below was, at some point, exactly correct somewhere else",
        "and then went stale in place (`AL-551`, `UW-G24`).",
        "",
        "## Totals",
        "",
        "| Quantity | Value |",
        "| --- | ---: |",
        f"| Shells (sidecars excluded) | {t['shells']:,} |",
        f"| Nodes | {t['nodes']:,} |",
        f"| Commissioned words | {t['commissioned_words']:,} |",
        f"| Production-eligible shells | {c['production_eligible_shells']:,} |",
        "",
        "## By band",
        "",
        "| Band | Shells | Nodes | Commissioned words | Nodes min / median / max |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    lines += [
        (
            f"| {b['band']} | {b['shells']} | {b['nodes']:,} | "
            f"{b['commissioned_words']:,} | "
            f"{b['min_nodes']} / {b['median_nodes']} / {b['max_nodes']} |"
        )
        for b in data["bands"]
    ]
    lines += [
        "",
        "## Cell coverage",
        "",
        "The coverage grid is the set of cells ADR-011 **offers**",
        "(`validator/band_profile.py::offered_cells`), not a cross-product of the",
        "band, length, and style enums. A combination the matrix does not sell",
        "(a 3-5 long, an 8-11 gamebook) is not an uncovered cell; no request can",
        "reach it. Reporting coverage against an invented grid manufactures gaps",
        "that do not exist (`AL-554`).",
        "",
        "| Quantity | Value |",
        "| --- | ---: |",
        f"| Offered cells | {c['offered']} |",
        f"| Covered | {c['covered']} |",
        f"| Uncovered | {c['uncovered']} |",
        "",
        (
            f"Per covered cell: {c['min_per_covered_cell']} to "
            f"{c['max_per_covered_cell']} skeletons, median "
            f"{c['median_per_covered_cell']:g}."
        ),
        "",
        "## Largest graph",
        "",
        "The node maximum and the commissioned-word maximum are **different",
        "books**, which is how a node count once became a word count.",
        "",
        "| Superlative | Skeleton | Nodes | Commissioned words |",
        "| --- | --- | ---: | ---: |",
        (
            f"| Most nodes | `{lg['by_nodes']['path']}` | "
            f"{lg['by_nodes']['nodes']} | "
            f"{lg['by_nodes']['commissioned_words']:,} |"
        ),
        (
            f"| Most commissioned words | "
            f"`{lg['by_commissioned_words']['path']}` | "
            f"{lg['by_commissioned_words']['nodes']} | "
            f"{lg['by_commissioned_words']['commissioned_words']:,} |"
        ),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run the census CLI.

    Args:
        argv: Argument vector; defaults to ``sys.argv[1:]``.

    Returns:
        0 on success, 1 when ``--check`` finds the generated doc stale.
    """
    parser = argparse.ArgumentParser(
        description="Skeleton catalog census: the one place a count comes from."
    )
    parser.add_argument("--json", action="store_true", help="emit JSON")
    parser.add_argument("--write", action="store_true", help="regenerate the doc")
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated doc is stale"
    )
    args = parser.parse_args(argv)

    data = census()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0

    rendered = render(data)
    if args.write:
        GENERATED_DOC.write_text(rendered)
        print(f"wrote {GENERATED_DOC}")
        return 0
    if args.check:
        current = GENERATED_DOC.read_text() if GENERATED_DOC.exists() else ""
        if current != rendered:
            print(
                f"stale: {GENERATED_DOC} does not match the catalog. "
                "Run: uv run python scripts/catalog_census.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {GENERATED_DOC} matches the catalog")
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
