"""Emit the per-book unit-cost model from committed evidence and prices.

Step 4 of the generation-review workstream plan
(``docs/planning/generation-review-workstream-plan-2026-08-22.md``) asks for a
per-book cost model in which every leg price traces to a committed run record.
This script is that model, and its main job is to be honest about how little
the committed evidence supports.

Three sources, all in-tree, none of them a live call:

* **Tokens** come from the committed run records under
  :data:`EVIDENCE_ROOT`, less the runs that corpus's own README excludes from
  analysis (:data:`EXCLUDED_RUNS`) and less records replayed byte-for-byte into
  a second run directory. Only some of what remains carries token counts, and
  they cover a strict subset of the offered grid; every one of those
  subtractions is counted and published rather than smoothed over.
* **Prices** come from :mod:`cyo_adventure.core.pricing`, the same table
  ``generation/worker.py`` stamps ``generation_job.cost_usd`` with, so a figure
  here and a figure in the database cannot disagree about what a token costs.
* **Book size** comes from the skeleton catalog via
  ``generation/skeleton.py::commissioned_words_by_node``, reached through
  ``scripts/catalog_census.py::load_shells`` so this page and the catalog
  census cannot disagree about how large a book is.

WHAT THIS DELIBERATELY DOES NOT EMIT. D3 was ruled only partially on
2026-08-23: the revenue anchor is a subscription at $1.99 or $4.99 and which
of the two is still open. An absolute per-book cost ceiling therefore cannot
be derived yet, so the model carries both candidate price points and publishes
headroom at each. ``cap`` is ``None`` by construction, not by omission.

The cell grid is ``band_profile.offered_cells()``, never a cross-product; the
rationale is stated once in ``scripts/catalog_census.py`` and not repeated.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cyo_adventure.core.pricing import estimate_cost, price_for
from cyo_adventure.storybook.models import AgeBand, age_band_rank
from cyo_adventure.validator.band_profile import offered_cells
from scripts.analyze_sibling_exposure import iter_cells
from scripts.catalog_census import load_shells

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DOC = Path("docs/planning/unit-cost-model.md")
EVIDENCE_ROOT = Path("docs/planning/evidence/skeleton-author-vendors/runs")
FILL_EVIDENCE_ROOT = Path("docs/planning/vendor-comparison/runs")

# The evidence README marks these two run directories "harness validation,
# excluded from S-1 analysis": they ran under a different token cap and
# without `--allow-mvp`, so their records are not comparable with the rest of
# the corpus. Reading them would not merely add noise; two of the five priced
# legs have no clean record anywhere else, so an unfiltered read publishes a
# median for those legs computed entirely from runs the corpus disowns.
#
# #CRITICAL: data-integrity: this list is hand-synced against
# `docs/planning/evidence/skeleton-author-vendors/README.md`. A run excluded
# there and absent here is priced as if it were evidence, and nothing in the
# rendered page would show it.
# #VERIFY: tests/unit/test_unit_cost_model.py::test_excluded_runs_match_the_evidence_readme
EXCLUDED_RUNS: frozenset[str] = frozenset({"smoke-2026-08-21", "smoke2-2026-08-21"})

_MARKER = "<!-- generated by scripts/unit_cost_model.py; do not edit by hand -->"

# The two candidate subscription price points D3 left open (2026-08-23).
PRICE_POINTS_USD: tuple[float, float] = (1.99, 4.99)

# The ``leg`` labels the committed run records use, mapped to the
# ``(provider, model)`` keys ``core.pricing.PRICES`` is keyed by. Hand-synced
# against both sides; `tests/unit/test_unit_cost_model.py` fails if either
# moves. Legs absent from this map (the four claude-*-subagent legs and
# moonshot-kimi-k3-modal) carry no token counts in any committed record, which
# is itself reported below rather than silently dropped.
LEG_MODELS: dict[str, tuple[str, str]] = {
    "anthropic-sonnet-5": ("openrouter", "anthropic/claude-sonnet-5"),
    "deepseek-v4-flash": ("openrouter", "deepseek/deepseek-v4-flash"),
    "deepseek-v4-pro": ("openrouter", "deepseek/deepseek-v4-pro"),
    "google-gemini-3.1-pro": ("openrouter", "google/gemini-3.1-pro-preview"),
    "openai-gpt-5.6-sol": ("openrouter", "openai/gpt-5.6-sol"),
}

# D1 (2026-08-23) fixed the family-lane pair: this fill leg and this review leg.
RULED_FILL_LEG = "deepseek-v4-pro"
RULED_REVIEW_LEG = "deepseek-v4-flash"

_LENGTH_ORDER = {"short": 0, "medium": 1, "long": 2}

# A label this file does not recognise sorts after every one it does.
_UNRANKED = len(AgeBand)


def _band_rank(band: str) -> int:
    """Return the reading-age rank of a band label.

    Bands sort by reading age, not lexicographically: "10-13" must not precede
    "3-5" in a table a person reads top to bottom. The ordering is read from
    ``storybook.models`` rather than re-derived here, the same way
    ``scripts/catalog_census.py`` reads it, so a new band cannot land in two
    different orders in two different files.

    Unlike the census, an unrecognised label sorts last instead of raising.
    The census reads directory names in a catalog it owns, where a stray name
    is a real fault. This file reads a ``band`` field off a run record, and
    :func:`_record_cell` deliberately tolerates that field being absent, which
    yields the literal ``"None"``. Refusing to render the whole report over
    one malformed record is the worse failure of the two.

    Args:
        band: A band label, such as ``"8-11"``.

    Returns:
        The rank used to sort per-band rows, or a rank past every real band
        when the label is not one.
    """
    try:
        return age_band_rank(AgeBand(band))
    except ValueError:
        return _UNRANKED


def _cell_sort_key(cell: tuple[str, str, str]) -> tuple[int, int, str]:
    """Return a stable sort key so the rendered tables never reorder.

    Args:
        cell: A ``(band, length, style)`` cell.

    Returns:
        A total ordering key. An unrecognised band or length sorts last
        rather than raising; see :func:`_band_rank`.
    """
    band, length, style = cell
    return (_band_rank(band), _LENGTH_ORDER.get(length, _UNRANKED), style)


def _scan_records(root: Path) -> tuple[list[dict[str, Any]], dict[str, int]]:
    """Read the evidence tree once, returning the records and what was skipped.

    Two filters apply, and both are facts about the corpus rather than
    preferences about it:

    * A record under a run directory in :data:`EXCLUDED_RUNS` is skipped. The
      evidence README excludes those runs from analysis; reading them anyway
      would publish a price for a leg whose only clean records live there.
    * A record whose decoded content is identical to one already read is a
      replay of the same authoring episode into a second run directory, not a
      second episode. Three of them carry the same ``latency_s`` to the
      microsecond, which two independent model calls do not produce. Counting
      one episode twice pulls the median toward whatever it happened to cost.

    Args:
        root: The committed evidence root, absolute or repo-relative.

    Returns:
        The surviving records in path order, and the counts behind them.

    Raises:
        FileNotFoundError: If ``root`` does not exist, which almost always
            means the caller is not at the repository root.
        ValueError: If a record file does not hold a JSON object. The census
            refuses to silently undercount its catalog and this refuses the
            same way: a malformed record dropped in silence is a leg priced
            from fewer episodes than the page claims.
    """
    anchored = _REPO_ROOT / root
    if not anchored.is_dir():
        msg = f"evidence root {root} not found; run from the repository root"
        raise FileNotFoundError(msg)
    records: list[dict[str, Any]] = []
    seen: set[str] = set()
    counts = {"files": 0, "excluded_run": 0, "replays": 0}
    for path in sorted(anchored.rglob("*.record.json")):
        counts["files"] += 1
        if path.relative_to(anchored).parts[0] in EXCLUDED_RUNS:
            counts["excluded_run"] += 1
            continue
        decoded: object = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(decoded, dict):
            msg = f"{path} does not hold a JSON object; the corpus is malformed"
            raise ValueError(msg)
        key = json.dumps(decoded, sort_keys=True)
        if key in seen:
            counts["replays"] += 1
            continue
        seen.add(key)
        records.append(decoded)
    return records, counts


def load_records(root: Path = EVIDENCE_ROOT) -> list[dict[str, Any]]:
    """Return every analysable committed run record, token-bearing or not.

    Args:
        root: The committed evidence root.

    Returns:
        One decoded record per ``*.record.json`` file that survives the
        exclusion and replay filters :func:`_scan_records` documents.
    """
    return _scan_records(root)[0]


def record_provenance(root: Path = EVIDENCE_ROOT) -> dict[str, int]:
    """Return how many record files were read, skipped, and de-duplicated.

    Published rather than kept internal: a filter that quietly removes a third
    of a corpus is indistinguishable, in the rendered page, from a corpus that
    was always that size.

    Args:
        root: The committed evidence root.

    Returns:
        ``files`` scanned, ``excluded_run`` skipped, ``replays`` dropped, and
        the ``analysed`` remainder.
    """
    records, counts = _scan_records(root)
    return {**counts, "analysed": len(records)}


def _record_cell(record: dict[str, Any]) -> tuple[str, str, str]:
    """Return the ``(band, length, style)`` cell a record was run against."""
    return (
        str(record.get("band")),
        str(record.get("length")),
        str(record.get("style")),
    )


def leg_costs(root: Path = EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Recompute per-leg cost from committed tokens and committed prices.

    Three counts are reported per leg and they are not interchangeable:
    ``records`` is every token-bearing record, ``without_error`` drops the legs
    that raised, and ``strict_pass`` keeps only those that also cleared the
    deterministic gate. Only the last are delivered books; a run that returned
    prose and then failed validation cost real money and delivered nothing.

    A fourth count, ``corpus_records``, is the leg's whole analysable record
    count. Most records carry no token counts at all, so ``records`` is a
    minority of them, and a table that printed only the minority would read as
    the leg's full history.

    Args:
        root: The committed evidence root.

    Returns:
        One entry per leg that has at least one token-bearing record, keyed by
        the leg label the records use.
    """
    buckets: dict[str, list[dict[str, Any]]] = {}
    corpus: dict[str, int] = {}
    for record in load_records(root):
        leg = str(record.get("leg"))
        if leg not in LEG_MODELS:
            continue
        corpus[leg] = corpus.get(leg, 0) + 1
        if isinstance(record.get("input_tokens"), int):
            buckets.setdefault(leg, []).append(record)

    out: dict[str, dict[str, Any]] = {}
    for leg, records in sorted(buckets.items()):
        out[leg] = _summarize_leg(leg, records, corpus[leg])
    return out


def _summarize_leg(
    leg: str, records: list[dict[str, Any]], corpus_records: int
) -> dict[str, Any]:
    """Return one leg's cost summary from its token-bearing records.

    Every dollar figure in the row is computed over the same population, the
    records that did not error. An earlier draft averaged the reasoning share
    over every record while taking the median over the clean ones, so two
    numbers printed side by side described different sets of runs.

    Args:
        leg: The leg label.
        records: That leg's token-bearing records.
        corpus_records: Every analysable record for the leg, priced or not.

    Returns:
        The summary row rendered into the per-leg table. The dollar fields are
        ``None`` when no record survived, which is a reachable state: a leg
        whose every token-bearing record errored has costs but no clean cost.
    """
    price = price_for(*LEG_MODELS[leg])
    priced = [
        (estimate_cost(price, r["input_tokens"], r.get("output_tokens")), r)
        for r in records
    ]
    ok = [(e, r) for e, r in priced if not r.get("error")]
    clean = [float(e.amount_usd) for e, _ in ok]
    shares = [
        (r.get("reasoning_tokens") or 0) / r["output_tokens"]
        for _, r in ok
        if r.get("output_tokens")
    ]
    return {
        "model": LEG_MODELS[leg][1],
        "price_as_of": price.as_of.isoformat(),
        "corpus_records": corpus_records,
        "records": len(records),
        "without_error": len(clean),
        "strict_pass": sum(1 for r in records if r.get("strict_pass")),
        "median_usd": round(statistics.median(clean), 4) if clean else None,
        "min_usd": round(min(clean), 4) if clean else None,
        "max_usd": round(max(clean), 4) if clean else None,
        "reasoning_share": (round(statistics.mean(shares), 4) if shares else None),
        "complete": all(e.complete for e, _ in ok),
        "cells": sorted({_record_cell(r) for r in records}, key=_cell_sort_key),
    }


def cell_weights() -> dict[tuple[str, str, str], dict[str, Any]]:
    """Return the credit weight of every offered cell, from commissioned words.

    D3 ruled that credits scale with book length and age band. Commissioned
    words are that scale: they are declared per node in the catalog, committed,
    and already what the catalog census counts, so a weight here and a size
    there cannot disagree. Weights are normalised to the smallest offered cell.

    Returns:
        One entry per offered cell, keyed by ``(band, length, style)``.

    Raises:
        ValueError: If the working directory is not the repository root, or
            if no shell covers any offered cell, which means the catalog and
            the offered grid have diverged completely.
    """
    _require_repo_root()
    by_slug = {shell.path.stem: shell for shell in load_shells()}
    populated = {
        (cell.band, cell.length, style): cell.slugs
        for cell in iter_cells()
        for style in cell.style.split("+")
        if cell.slugs
    }
    covered = offered_cells() & populated.keys()
    if not covered:
        msg = "no shell covers any offered cell; catalog and grid have diverged"
        raise ValueError(msg)

    sizes = {
        key: [by_slug[slug] for slug in populated[key] if slug in by_slug]
        for key in covered
    }
    medians = {
        key: statistics.median([s.commissioned_words for s in shells])
        for key, shells in sizes.items()
        if shells
    }
    base = min(medians.values())
    return {
        key: {
            "shells": len(sizes[key]),
            "median_words": int(medians[key]),
            "median_nodes": int(statistics.median([s.nodes for s in sizes[key]])),
            "weight": round(medians[key] / base, 2),
        }
        for key in sorted(medians, key=_cell_sort_key)
    }


def _require_repo_root() -> None:
    """Fail loudly when the process is not rooted at the repository.

    Same anchoring `scripts/catalog_census.py` states in full: `load_shells`
    honours a relative root but `iter_cells` reaches `skeleton_match`, whose
    root is a module-level relative constant with no override, so the two
    halves would describe different catalogs from any other directory.

    Raises:
        ValueError: If the working directory is not the repository root.
    """
    if Path.cwd() != _REPO_ROOT:
        msg = (
            f"run this from the repository root ({_REPO_ROOT}); "
            f"the working directory is {Path.cwd()}."
        )
        raise ValueError(msg)


def load_fill_books(root: Path = FILL_EVIDENCE_ROOT) -> list[dict[str, Any]]:
    """Return every billed book record from the vendor-comparison fill runs.

    This is a different workload from `load_records`. That one reads skeleton
    authoring: a leg is asked to invent a story shell from a premise, and its
    record accumulates every attempt and repair round. This one reads prose
    fill: a leg is given a finished skeleton and writes the bodies. Only the
    second is what a family's book costs, so only the second may anchor a price.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        Book records carrying a metered `cost`, in path order.

        A book without one is dropped, and the drop is counted by
        :func:`fill_provenance` rather than passing in silence. The record that
        this removes today says why itself: `cost_complete: false`,
        `cost_unavailable_reason: "no provider call was metered for this
        book"`, in a run where every other book carries a real metered cost.
        Its spend is unknown, not zero, so neither including it as free nor
        dropping it unannounced is honest. Cost instrumentation arrived in
        #701; `AL-329` is a different lesson, about `finish_reason` and
        reasoning-token diagnostics, and does not explain this null.
    """
    _require_repo_root()
    catalog = {shell.path.stem: shell for shell in load_shells()}
    books: list[dict[str, Any]] = []
    for report in sorted((_REPO_ROOT / root).glob("**/report.json")):
        data: dict[str, Any] = json.loads(report.read_text(encoding="utf-8"))
        if data.get("mock"):
            continue
        skeletons: list[str] = [str(name) for name in data.get("skeletons", [])]
        for raw in data.get("books", []):
            book: dict[str, Any] = dict(raw)
            if book.get("cost") is None:
                continue
            index = int(book.get("brief_index", -1))
            slug = Path(skeletons[index]).stem if 0 <= index < len(skeletons) else ""
            shell = catalog.get(slug)
            book["skeleton"] = slug
            book["band"] = shell.band if shell else ""
            book["commissioned_words"] = shell.commissioned_words if shell else 0
            books.append(book)
    return books


def fill_provenance(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, int]:
    """Return how many book records were read, and how many carried no cost.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        ``books`` written by the runs, ``unmetered`` dropped for want of a
        metered cost, and the ``analysed`` remainder.
    """
    _require_repo_root()
    books = unmetered = 0
    for report in sorted((_REPO_ROOT / root).glob("**/report.json")):
        data: dict[str, Any] = json.loads(report.read_text(encoding="utf-8"))
        if data.get("mock"):
            continue
        for raw in data.get("books", []):
            books += 1
            if raw.get("cost") is None:
                unmetered += 1
    return {"books": books, "unmetered": unmetered, "analysed": books - unmetered}


def delivery_quality(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, Any]:
    """Return what the corpus records about how completely books were measured.

    This exists to settle a question the page used to leave open. Delivered
    words come to about half of commissioned words, and that is consistent with
    two very different readings: the books are short, or the measurement missed
    what they wrote. The second reading would mean every dollars-per-word
    figure on the page is overstated by up to 2x, so it cannot be left as a
    shrug. The corpus does separate them: `fill_completeness` is the filler's
    own report of how much of the skeleton it filled, and
    `reading_level_nodes_dropped` counts what repair removed before measuring.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        The aggregate over delivered books, or zeros and ``None`` when no book
        was delivered.
    """
    delivered = [
        b
        for b in load_fill_books(root)
        if b.get("complete") and int(b.get("leaf_words") or 0) > 0
    ]
    if not delivered:
        return {
            "books": 0,
            "min_fill_completeness": None,
            "nodes_dropped_to_reading_level": 0,
            "degraded_books": 0,
        }
    return {
        "books": len(delivered),
        "min_fill_completeness": min(
            float(b.get("fill_completeness") or 0.0) for b in delivered
        ),
        "nodes_dropped_to_reading_level": sum(
            int(b.get("reading_level_nodes_dropped") or 0) for b in delivered
        ),
        "degraded_books": sum(1 for b in delivered if b.get("reading_level_degraded")),
    }


def fill_by_band(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Summarize billed fill cost per age band.

    The band comes from the skeleton the book filled, not from the book, so it
    is the catalog's own classification rather than anything the run asserted.
    Reporting per band is what makes the model's linear scaling falsifiable: if
    dollars per commissioned word were wildly different at `3-5` and `16+`, a
    single rate scaled by word count would be indefensible, and this table is
    where that would show.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        One summary per band that has at least one delivered book, ordered by
        band.
    """
    by_band: dict[str, list[dict[str, Any]]] = {}
    for book in load_fill_books(root):
        if book["band"] and book.get("complete"):
            by_band.setdefault(str(book["band"]), []).append(book)

    out: dict[str, dict[str, Any]] = {}
    for band in sorted(by_band, key=_band_rank):
        books = by_band[band]
        billed = sum(float(b["cost"]) for b in books)
        commissioned = sum(int(b["commissioned_words"]) for b in books)
        delivered_words = sum(int(b["leaf_words"] or 0) for b in books)
        if commissioned <= 0:
            continue
        out[band] = {
            "books": len(books),
            "billed_usd": round(billed, 4),
            "commissioned_words": commissioned,
            "delivered_words": delivered_words,
            "usd_per_1k_commissioned_words": round(1000 * billed / commissioned, 4),
            "delivered_share_of_commission": round(delivered_words / commissioned, 3),
        }
    return out


def fill_costs(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Summarize billed prose-fill cost per leg.

    The figures are metered, not recomputed. The book records carry no
    `input_tokens`, so a token-derived estimate is not even available here, and
    the billed number is the better evidence anyway: it is what was charged,
    including whatever endpoint, cache state and discount actually applied.

    Failed books are charged to the books that landed. A call that returns
    nothing is still billed and still has to be retried, so cost per delivered
    book is the figure a subscription has to cover; cost per call is not.

    Two rates come out of this and they are not interchangeable.
    ``usd_per_1k_words`` is per thousand words the leg actually delivered.
    ``usd_per_1k_commissioned_words`` is per thousand words the skeleton asked
    for. These books delivered roughly half their commission, so the two differ
    by about 2.2x, and only the second may be scaled by a cell's commissioned
    word count.

    #CRITICAL: payment/financial: these two rates have the same units and
    differ by a factor of two, so a caller that reaches for the wrong one gets
    a plausible number rather than an error. :func:`_headroom` is the caller
    that matters, and it is what decides whether a $1.99 subscription looks
    affordable or nearly consumed.
    #VERIFY: tests/unit/test_unit_cost_model.py::test_headroom_scales_the_commissioned_word_rate

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        One summary per leg, keyed by the leg label the run recorded.
    """
    by_leg: dict[str, list[dict[str, Any]]] = {}
    for book in load_fill_books(root):
        by_leg.setdefault(str(book.get("vendor")), []).append(book)

    out: dict[str, dict[str, Any]] = {}
    for leg, books in sorted(by_leg.items()):
        delivered = [
            b for b in books if b.get("complete") and int(b.get("leaf_words") or 0) > 0
        ]
        if not delivered:
            continue
        billed = sum(float(b["cost"]) for b in books)
        failed = billed - sum(float(b["cost"]) for b in delivered)
        words = sum(int(b["leaf_words"]) for b in delivered)
        commissioned = sum(int(b["commissioned_words"]) for b in delivered)
        per_1k = [1000 * float(b["cost"]) / int(b["leaf_words"]) for b in delivered]
        emitted = sum(int(b.get("output_tokens") or 0) for b in delivered)
        out[leg] = {
            "source": "metered",
            "books": len(books),
            "delivered": len(delivered),
            "billed_usd": round(billed, 4),
            "failed_usd": round(failed, 4),
            "words": words,
            "commissioned_words": commissioned,
            "usd_per_delivered_book": round(billed / len(delivered), 4),
            "usd_per_1k_words": round(1000 * billed / words, 4),
            "usd_per_1k_commissioned_words": (
                round(1000 * billed / commissioned, 6) if commissioned else None
            ),
            "usd_per_1k_words_min": round(min(per_1k), 4),
            "usd_per_1k_words_max": round(max(per_1k), 4),
            "output_tokens_per_word": round(emitted / words, 2),
            "reasoning_tokens": sum(int(b.get("reasoning_tokens") or 0) for b in books),
        }
    return out


def _headroom(
    cells: dict[tuple[str, str, str], dict[str, Any]],
) -> list[dict[str, Any]]:
    """Return per-price-point headroom against the billed fill rate.

    An earlier draft of this model scaled the skeleton-authoring cost by fill
    word counts. Those are different workloads measured on different corpora,
    so that was a category error and the figures it produced were meaningless.

    A second, subtler version of the same error followed it. A cell's
    ``median_words`` is **commissioned** words, what the skeleton asks a filler
    to write. ``usd_per_1k_words`` is dollars per **delivered** word, what the
    filler actually wrote. These books delivered roughly half their commission,
    so multiplying one by the other inflated every figure by about 2.2x and put
    the dearest cell at 95% of a $1.99 subscription instead of 44%. The rate
    scaled here is therefore ``usd_per_1k_commissioned_words``: the same
    billed dollars over the same books, divided by the same quantity the cell
    supplies.

    The scaling is still an assumption, but a checked one: the per-band table
    reports this rate across the bands measured, and the single rate used here
    falls inside that spread rather than above it.

    #CRITICAL: payment/financial: this is the figure D3 will be ruled with, and
    the two candidate rates differ by a factor of two with identical units, so
    picking the wrong one produces a confident answer rather than a failure.
    #VERIFY: tests/unit/test_unit_cost_model.py::test_headroom_scales_the_commissioned_word_rate

    Args:
        cells: The per-cell credit weights, carrying commissioned words.

    Returns:
        One row per candidate price point, or an empty list when the ruled fill
        leg has no billed record or delivered no commissioned words.
    """
    fill = fill_costs().get(RULED_FILL_LEG)
    if not fill or fill.get("usd_per_1k_commissioned_words") is None:
        return []
    rate = float(fill["usd_per_1k_commissioned_words"])
    scaled = {
        cell: rate * int(row["median_words"]) / 1000 for cell, row in cells.items()
    }
    cheapest = min(scaled, key=lambda c: scaled[c])
    dearest = max(scaled, key=lambda c: scaled[c])
    return [
        {
            "price_usd": price,
            "basis": "billed fill, ruled leg, per commissioned word",
            "usd_per_1k_commissioned_words": fill["usd_per_1k_commissioned_words"],
            "cheapest_cell": "/".join(cheapest),
            "dearest_cell": "/".join(dearest),
            "scaled_min_usd": round(scaled[cheapest], 4),
            "scaled_max_usd": round(scaled[dearest], 4),
            "share_of_price_min": round(scaled[cheapest] / price, 4),
            "share_of_price_max": round(scaled[dearest] / price, 4),
        }
        for price in PRICE_POINTS_USD
    ]


def model() -> dict[str, Any]:
    """Compute the whole unit-cost model.

    Returns:
        A JSON-serializable model: per-leg costs, per-cell credit weights,
        headroom at each candidate price point, and the assumptions that are
        not measured. ``cap`` is always ``None``; see the module docstring.
    """
    legs = leg_costs()
    cells = cell_weights()
    seen_cells = {tuple(c) for row in legs.values() for c in row["cells"]}
    measured = seen_cells & offered_cells()
    unpriced = sorted(
        {
            str(r.get("leg"))
            for r in load_records()
            if str(r.get("leg")) not in LEG_MODELS
        }
    )
    return {
        "legs": legs,
        "fill": fill_costs(),
        "fill_by_band": fill_by_band(),
        "delivery": delivery_quality(),
        "cells": {"/".join(k): v for k, v in cells.items()},
        "provenance": {
            "records": record_provenance(),
            "fill_books": fill_provenance(),
        },
        "coverage": {
            "offered_cells": len(offered_cells()),
            "measured_cells": len(measured),
            "measured": sorted("/".join(c) for c in measured),
            "off_grid": sorted("/".join(c) for c in seen_cells - offered_cells()),
            "legs_without_token_records": unpriced,
        },
        "headroom": _headroom(cells),
        "cap": None,
        "assumptions": {
            "scaling": (
                "Cost at an unmeasured cell is the billed dollars-per-thousand "
                "COMMISSIONED words on the ruled fill leg, scaled by that "
                "cell's commissioned words. Both sides are commissioned words, "
                "which is the whole point: the delivered-word rate is roughly "
                "twice as large, and scaling a cell's commission by it "
                "overstates every figure it touches. Linear by assumption, but "
                "the assumption is checkable rather than bare: the per-band "
                "spread of that same rate is reported above, and the single "
                "rate used is shown against it."
            ),
            "review_leg": (
                f"D1 ruled the review leg to `{RULED_REVIEW_LEG}`, and no "
                "committed run bills that leg on the fill workload, so every "
                "figure here is the FILL half of the pair only. The review pass "
                "is a real cost that is simply not measured, so the pair costs "
                "more than the fill figures above. That makes the fill half a "
                "floor on the pair; it does not make any single number here a "
                "floor on itself, and the fill half carries its own two-sided "
                "uncertainty from a five-book corpus."
            ),
            "workloads": (
                "Skeleton authoring and prose fill are separate workloads on "
                "separate corpora and must not be scaled by each other's word "
                "counts. The skeleton table above prices inventing a story "
                "shell, including every retry and repair round in the record; "
                "the fill table prices writing the prose for a finished shell."
            ),
            "human_minutes": (
                "D3 ruled that human approval minutes are costed at a notional "
                "rate rather than excluded, but named no rate, and S-6 has not "
                "run, so the minutes are unmeasured. No minutes term is folded "
                "into any figure here; every cost above is LLM spend only."
            ),
            "modal": (
                "Modal is billed per GPU-second and carries no per-MTok price, "
                "so a Modal-served leg cannot be costed from this table at all."
            ),
        },
    }


def _usd(value: float | None) -> str:
    """Render a dollar figure, or ``n/a`` when there is none.

    A leg whose every token-bearing record errored has no clean cost, and that
    is a reachable state rather than a theoretical one: one leg in the corpus
    today errored on every record that survived the run exclusions. Formatting
    ``None`` is a crash, and a crash in the renderer takes the whole page with
    it, including the rows that are fine.

    #EDGE: data-integrity: an empty row is a real finding, not a blank. A leg
    that billed money and returned nothing usable is exactly what a cost model
    should show.
    #VERIFY: tests/unit/test_unit_cost_model.py::test_a_leg_with_no_clean_record_renders_rather_than_crashing

    Args:
        value: A dollar amount, or ``None`` when none could be computed.

    Returns:
        The amount to four decimal places, or ``n/a``.
    """
    return "n/a" if value is None else f"{value:.4f}"


def _render_legs(data: dict[str, Any]) -> list[str]:
    """Return the per-leg cost table lines.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The section's markdown lines.
    """
    legs: dict[str, Any] = data["legs"]
    dates = sorted({row["price_as_of"] for row in legs.values()})
    lines = [
        "## Skeleton-authoring cost, recomputed from committed tokens",
        "",
        (
            "**This is not the cost of a book.** It prices inventing a story "
            "shell from a premise, and each record accumulates every attempt "
            "and repair round it took, so a record is a whole authoring "
            "episode rather than a call. Recomputed as `input_tokens x input "
            "price + output_tokens x output price` using `core/pricing.py`, "
            "over the committed run records that carry token counts. "
            "`delivered` counts records that also cleared the deterministic "
            "gate; the others cost money and delivered nothing."
        ),
        "",
        (
            "Most records carry no token counts, so `priced` is a minority of "
            "`corpus`; both are printed so the table cannot be read as a leg's "
            "whole history. A price is a fact about a day rather than a "
            "constant, and every price below was read "
            + (
                f"on `{dates[0]}`"
                if len(dates) == 1
                else f"between `{dates[0]}` and `{dates[-1]}`"
            )
            + " (`core/pricing.py`)."
        ),
        "",
        (
            "| Leg | Model | Corpus | Priced | No error | Delivered | "
            "Median $ | Min $ | Max $ | Reasoning share |"
        ),
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for leg, row in legs.items():
        share = row["reasoning_share"]
        lines.append(
            f"| `{leg}` | `{row['model']}` | {row['corpus_records']} | "
            f"{row['records']} | {row['without_error']} | {row['strict_pass']} | "
            f"{_usd(row['median_usd'])} | {_usd(row['min_usd'])} | "
            f"{_usd(row['max_usd'])} | "
            f"{'n/a' if share is None else f'{share:.1%}'} |"
        )
    partial = [leg for leg, row in legs.items() if not row["complete"]]
    empty = [leg for leg, row in legs.items() if row["median_usd"] is None]
    lines += [
        "",
        (
            "Every priced record above carries both token counts, so no row "
            "sums a half-priced call as though it were a whole one."
            if not partial
            else "These legs have a record missing an `output_tokens` count, so "
            "their cost is the input half only and is understated: "
            + ", ".join(f"`{leg}`" for leg in partial)
            + "."
        ),
    ]
    if empty:
        lines += [
            "",
            (
                "These legs have priced records but none that came back without "
                "an error, so they have a spend and no cost per delivered "
                "shell: "
                + ", ".join(f"`{leg}`" for leg in empty)
                + ". An `n/a` above is that state, not a missing measurement."
            ),
        ]
    return lines


def _render_fill(data: dict[str, Any]) -> list[str]:
    """Return the billed prose-fill cost table lines.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The section's markdown lines.
    """
    lines = [
        "## Prose-fill cost, as billed",
        "",
        (
            "This is what a book costs. The figures are metered, not "
            "recomputed: the book records carry no `input_tokens`, and the "
            "billed number is better evidence anyway because it already "
            "includes whichever endpoint, cache state and discount applied. "
            "Failed books are charged to the books that landed, because a call "
            "that returns nothing is still billed and still has to be retried."
        ),
        "",
        (
            "Two rates are printed and they are not interchangeable. "
            "`$/1k delivered` divides by the words the leg wrote; "
            "`$/1k commissioned` divides by the words the skeleton asked for. "
            "A cell's size is a commission, so only the second may be scaled "
            "by it, and the headroom table below uses that one."
        ),
        "",
        (
            "| Leg | Books | Delivered | Billed $ | Spent on failures $ | "
            "Words delivered | Words commissioned | $/delivered book | "
            "$/1k delivered | $/1k delivered range | $/1k commissioned | "
            "Output tok/word |"
        ),
        (
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | "
            "---: | ---: | ---: |"
        ),
    ]
    lines.extend(
        f"| `{leg}` | {row['books']} | {row['delivered']} | "
        f"{row['billed_usd']:.4f} | {row['failed_usd']:.4f} | "
        f"{row['words']:,} | {row['commissioned_words']:,} | "
        f"{row['usd_per_delivered_book']:.4f} | "
        f"{row['usd_per_1k_words']:.4f} | "
        f"{row['usd_per_1k_words_min']:.4f} to "
        f"{row['usd_per_1k_words_max']:.4f} | "
        f"{_usd(row['usd_per_1k_commissioned_words'])} | "
        f"{row['output_tokens_per_word']:.2f} |"
        for leg, row in data["fill"].items()
    )
    return lines


def _band_reconciliation(data: dict[str, Any]) -> str:
    """Return the sentence reconciling the per-band total with the leg total.

    The two tables are both headed with billed dollars over the same runs and
    they do not agree, because one charges failed books to the books that
    landed and the other, being per band, has nowhere to put a book that
    delivered nothing. A difference a reader has to discover by subtracting two
    tables is a defect in the page, not a subtlety.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        A sentence stating both totals and what the difference is.
    """
    leg_total = sum(float(row["billed_usd"]) for row in data["fill"].values())
    leg_books = sum(int(row["books"]) for row in data["fill"].values())
    band_total = sum(float(row["billed_usd"]) for row in data["fill_by_band"].values())
    band_books = sum(int(row["books"]) for row in data["fill_by_band"].values())
    return (
        f"**These are not the same dollars as the table above.** That one "
        f"bills ${leg_total:.4f} across {leg_books} books, this one "
        f"${band_total:.4f} across the {band_books} that landed, a difference "
        f"of ${leg_total - band_total:.4f}. The gap is what the failed books "
        "cost. The leg table charges that to the books that did land, which is "
        "the figure a subscription has to cover; a per-band table has no band "
        "to charge it to, because a book that delivered nothing is not "
        "evidence about the band it was aimed at."
    )


def _render_fill_bands(data: dict[str, Any]) -> list[str]:
    """Return the per-band billed fill table lines.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The section's markdown lines.
    """
    lines = [
        "### The same cost, per band",
        "",
        (
            "The band is the catalog's classification of the skeleton each "
            "book filled, not anything the run asserted. This table is what "
            "makes the linear scaling below falsifiable: if dollars per "
            "commissioned word differed sharply across bands, scaling one rate "
            "by word count would be indefensible."
        ),
        "",
        (
            "| Band | Books landed | Billed $ (landed only) | Commissioned "
            "words | Scorable words delivered | Scorable share | "
            "$/1k commissioned words |"
        ),
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    lines.extend(
        f"| `{band}` | {row['books']} | {row['billed_usd']:.4f} | "
        f"{row['commissioned_words']:,} | {row['delivered_words']:,} | "
        f"{row['delivered_share_of_commission']:.1%} | "
        f"{row['usd_per_1k_commissioned_words']:.4f} |"
        for band, row in data["fill_by_band"].items()
    )
    lines += ["", _band_reconciliation(data)]
    lines += _render_linearity(data)
    lines += _render_scorable_share(data)
    return lines


def _render_linearity(data: dict[str, Any]) -> list[str]:
    """Return the sentence on how far the single scaled rate is evidenced.

    Suppressed below two bands, and where a rate rounds to zero. One band
    yields a spread of exactly 1.00x, which reads as perfect linearity when it
    is really an absence of any second point to compare against; and a rate
    under $0.00005 per thousand words rounds to zero, which is a division by
    zero rather than a small denominator.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The lines, or an empty list when there is nothing defensible to say.
    """
    rates = [
        float(row["usd_per_1k_commissioned_words"])
        for row in data["fill_by_band"].values()
    ]
    if len(rates) < 2 or min(rates) <= 0:
        return [
            "",
            (
                "Fewer than two bands carry a nonzero measured rate, so this "
                "table cannot yet say anything about how the rate moves with "
                "band. Every figure scaled below is an extrapolation from a "
                "single point."
            ),
        ]
    used = data["fill"].get(RULED_FILL_LEG, {}).get("usd_per_1k_commissioned_words")
    inside = used is not None and min(rates) <= float(used) <= max(rates)
    scaled_note = (
        f"The rate the headroom table scales, {float(used):.4f}, falls "
        f"{'inside' if inside else 'OUTSIDE'} that spread"
        + (
            "."
            if inside
            else ", which means the check above is not checking the quantity "
            "actually used and the scaling below is unsupported."
        )
        if used is not None
        else "No rate is being scaled below, so there is nothing to check."
    )
    return [
        "",
        (
            f"That rate spans {min(rates):.4f} to {max(rates):.4f}, a factor "
            f"of {max(rates) / min(rates):.2f} across the {len(rates)} bands "
            "measured, so a single rate scaled by commissioned words is a "
            "defensible approximation over this range and an extrapolation "
            f"outside it. {scaled_note}"
        ),
    ]


def _render_scorable_share(data: dict[str, Any]) -> list[str]:
    """Return the reading of the scorable share the corpus supports.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The lines interpreting the scorable-share column.
    """
    quality: dict[str, Any] = data["delivery"]
    if not quality["books"]:
        return []
    filled = quality["min_fill_completeness"]
    dropped = quality["nodes_dropped_to_reading_level"]
    if filled == 1.0 and dropped == 0 and not quality["degraded_books"]:
        return [
            "",
            (
                "**Read the scorable share carefully, and read it as book "
                f"length.** All {quality['books']} delivered books report "
                "`fill_completeness: 1.0`, none was reading-level degraded, and "
                "none had a node dropped before measurement, so the measurement "
                "excluded nothing it was given. A share near half is these "
                "books coming in short against their commission, not scoring "
                "missing part of what they wrote. The dollars-per-delivered-"
                "word figures above are therefore what they say, with no "
                "unmeasured tail hiding behind them."
            ),
        ]
    return [
        "",
        (
            "**Read the scorable share carefully.** Delivery is not clean "
            f"across the {quality['books']} delivered books: the lowest "
            f"`fill_completeness` is {filled}, "
            f"{quality['degraded_books']} book(s) were reading-level degraded, "
            f"and {dropped} node(s) were dropped before measurement. Some of "
            "the shortfall below commission is therefore measurement rather "
            "than length, and the dollars-per-delivered-word figures above are "
            "pessimistic by an amount this corpus does not pin down."
        ),
    ]


def _render_cells(data: dict[str, Any]) -> list[str]:
    """Return the per-cell credit weight table lines.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The section's markdown lines.
    """
    lines = [
        "## Credit weight by cell",
        "",
        (
            "D3 ruled credits scale with book length and age band. The scale "
            "is commissioned words from the skeleton catalog, normalised to "
            "the smallest offered cell. Today's gate "
            "(`story_requests/service.py::enforce_family_quota`) counts "
            "stories instead, so every row below currently costs a family "
            "exactly 1."
        ),
        "",
        "| Cell | Shells | Median nodes | Median commissioned words | Credits |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for cell, row in data["cells"].items():
        lines.append(
            f"| `{cell}` | {row['shells']} | {row['median_nodes']} | "
            f"{row['median_words']:,} | {row['weight']:.2f} |"
        )
    return lines


def _render_headroom(data: dict[str, Any]) -> list[str]:
    """Return the headroom table lines.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The section's markdown lines.
    """
    lines = [
        "## Headroom at each candidate price point",
        "",
        (
            "D3 left the subscription at $1.99 or $4.99 and did not choose, so "
            "no absolute per-book cap is derived here. Each cell's cost is the "
            "billed **per commissioned word** rate above times that cell's "
            "median commissioned words, which are the same quantity, so the "
            "two sides of the multiplication agree on what a word is."
        ),
        "",
    ]
    delivered = int(data["fill"].get(RULED_FILL_LEG, {}).get("delivered", 0))
    if RULED_REVIEW_LEG in data["fill"]:
        lines += [
            (
                f"The ruled review leg `{RULED_REVIEW_LEG}` now has a billed "
                "record on this workload, so the figures here are no longer "
                "fill-only and this section needs rewriting against the pair."
            ),
            "",
        ]
    else:
        lines += [
            (
                f"**Fill only.** The ruled review leg `{RULED_REVIEW_LEG}` has "
                "no billed record on this workload, so the pair costs more than "
                "every figure here. That is a floor on the pair, not a floor on "
                f"these numbers: the fill half itself rests on {delivered} "
                "delivered books and moves in both directions."
            ),
            "",
        ]
    if not data["headroom"]:
        lines.append(
            "The ruled fill leg has no billed record with commissioned words "
            "behind it, so no headroom can be computed. Nothing is scaled and "
            "no table follows."
        )
        return lines
    lines += [
        (
            "| Price | $/1k commissioned words | Cheapest cell | Scaled min $ | "
            "Min share of price | Dearest cell | Scaled max $ | "
            "Max share of price |"
        ),
        "| ---: | ---: | --- | ---: | ---: | --- | ---: | ---: |",
    ]
    lines.extend(
        f"| ${row['price_usd']:.2f} | "
        f"{row['usd_per_1k_commissioned_words']:.4f} | "
        f"`{row['cheapest_cell']}` | {row['scaled_min_usd']:.4f} | "
        f"{row['share_of_price_min']:.1%} | "
        f"`{row['dearest_cell']}` | {row['scaled_max_usd']:.4f} | "
        f"{row['share_of_price_max']:.1%} |"
        for row in data["headroom"]
    )
    return lines


def render(data: dict[str, Any]) -> str:
    """Render the model as the committed markdown page.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The full page text, ending in a newline.
    """
    cov = data["coverage"]
    rec = data["provenance"]["records"]
    book = data["provenance"]["fill_books"]
    measured_bands = list(data["fill_by_band"])
    unmeasured_bands = [b.value for b in AgeBand if b.value not in measured_bands]
    lines = [
        "# Per-book unit-cost model",
        "",
        _MARKER,
        "",
        "Regenerate with `uv run python scripts/unit_cost_model.py --write`.",
        "",
        "## What is measured, and what is not",
        "",
        (
            "This model reads two different corpora and they must not be "
            "confused. **Skeleton authoring** invents a story shell from a "
            "premise; **prose fill** writes the bodies for a shell that already "
            "exists. Only the second is what a family's book costs."
        ),
        "",
        f"The skeleton-authoring records carry token counts for "
        f"**{cov['measured_cells']} of the {cov['offered_cells']} offered "
        "cells**: " + ", ".join(f"`{c}`" for c in cov["measured"]) + ".",
        "",
        (
            "The fill records are billed rather than recomputed and cover "
            f"**{len(measured_bands)} of the {len(AgeBand)} age bands**: "
            + ", ".join(f"`{b}`" for b in measured_bands)
            + (
                "."
                if not unmeasured_bands
                else ". There is no delivered fill book at "
                + ", ".join(f"`{b}`" for b in unmeasured_bands)
                + ", so every figure at those bands is scaled from the bands "
                "that were measured."
            )
        ),
        "",
        "These legs appear in the committed records but carry no token counts "
        "at all, so they cannot be costed from this evidence: "
        + ", ".join(f"`{leg}`" for leg in cov["legs_without_token_records"])
        + ".",
        "",
        (
            "**What was read, and what was set aside.** Skeleton-authoring "
            f"record files: {rec['files']} committed, {rec['excluded_run']} "
            "under runs the evidence README excludes from analysis, "
            f"{rec['replays']} byte-identical replays of a record already read, "
            f"{rec['analysed']} analysed. Fill book records: {book['books']} "
            f"written, {book['unmetered']} carrying no metered cost, "
            f"{book['analysed']} analysed. A set-aside book's spend is unknown "
            "rather than zero, so it is neither counted as free nor dropped in "
            "silence."
        ),
        "",
    ]
    lines += [*_render_legs(data), ""]
    lines += [*_render_fill(data), ""]
    lines += [*_render_fill_bands(data), ""]
    lines += [*_render_cells(data), ""]
    lines += [*_render_headroom(data), ""]
    lines += ["## Assumptions", ""]
    for name, text in data["assumptions"].items():
        lines.append(f"- **{name}**: {text}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run the CLI.

    Args:
        argv: Argument vector, or ``None`` to read ``sys.argv``.

    Returns:
        0 on success, 1 when ``--check`` finds the doc stale.
    """
    parser = argparse.ArgumentParser(
        description="Emit the per-book unit-cost model from committed evidence."
    )
    # All three are modes, not a format plus two modes. `--json` used to sit
    # outside the group and return first, so `--json --check` exited 0 with the
    # document absent entirely and `--json --write` was a silent no-op. A pair
    # of flags that cancel each other in silence is the same defect
    # `catalog_census.py` already shipped once and now carries a test for.
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--json", action="store_true", help="emit JSON")
    mode.add_argument("--write", action="store_true", help="regenerate the doc")
    mode.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args(argv)

    data = model()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True, default=str))
        return 0
    text = render(data)
    target = _REPO_ROOT / GENERATED_DOC
    if args.write:
        target.write_text(text, encoding="utf-8")
        print(f"wrote {GENERATED_DOC}")
        return 0
    if args.check:
        return _check(target, text)
    print(text)
    return 0


def _check(target: Path, text: str) -> int:
    """Compare the committed document with the freshly rendered one.

    A document that was never generated is a different fault from one that has
    drifted, and telling a reader "stale" when the file is absent sends them
    looking for a diff that does not exist.

    Args:
        target: The committed document's path.
        text: The freshly rendered document.

    Returns:
        0 when the committed document matches, 1 otherwise.
    """
    run = "Run: uv run python scripts/unit_cost_model.py --write"
    if not target.exists():
        print(f"{GENERATED_DOC} does not exist. {run}", file=sys.stderr)
        return 1
    if target.read_text(encoding="utf-8") != text:
        print(f"{GENERATED_DOC} is stale. {run}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
