"""Emit the per-book unit-cost model from committed evidence and prices.

Step 4 of the generation-review workstream plan
(``docs/planning/generation-review-workstream-plan-2026-08-22.md``) asks for a
per-book cost model in which every leg price traces to a committed run record.
This script is that model, and its main job is to be honest about how little
the committed evidence supports.

Three sources, all in-tree, none of them a live call:

* **Tokens** come from the committed run records under
  :data:`EVIDENCE_ROOT`. Only some records carry token counts, and they cover a
  strict subset of the offered grid; both facts are computed and published
  rather than smoothed over.
* **Prices** come from :mod:`cyo_adventure.core.pricing`, the same table
  ``generation/worker.py`` stamps ``generation_job.cost_usd`` with, so a figure
  here and a figure in the database cannot disagree about what a token costs.
* **Book size** comes from the skeleton catalog via
  ``generation/skeleton.py::commissioned_words_by_node``, reached through
  ``scripts/catalog_census.py::load_shells`` so this page and the catalog
  census cannot disagree about how large a book is.

WHAT THIS DELIBERATELY DOES NOT EMIT. D3 was ruled only partially on
2026-08-23: the revenue anchor is a subscription at $1.99 or $4.99 and which
of the two is still open. An absolute per-book cost ceiling therefore cannot
be derived yet, so the model carries both candidate price points and publishes
headroom at each. ``cap`` is ``None`` by construction, not by omission.

The cell grid is ``band_profile.offered_cells()``, never a cross-product; the
rationale is stated once in ``scripts/catalog_census.py`` and not repeated.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cyo_adventure.core.pricing import estimate_cost, price_for
from cyo_adventure.validator.band_profile import offered_cells
from scripts.analyze_sibling_exposure import iter_cells
from scripts.catalog_census import load_shells

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DOC = Path("docs/planning/unit-cost-model.md")
EVIDENCE_ROOT = Path("docs/planning/evidence/skeleton-author-vendors/runs")
FILL_EVIDENCE_ROOT = Path("docs/planning/vendor-comparison/runs")

_MARKER = "<!-- generated by scripts/unit_cost_model.py; do not edit by hand -->"

# The two candidate subscription price points D3 left open (2026-08-23).
PRICE_POINTS_USD: tuple[float, float] = (1.99, 4.99)

# The ``leg`` labels the committed run records use, mapped to the
# ``(provider, model)`` keys ``core.pricing.PRICES`` is keyed by. Hand-synced
# against both sides; `tests/unit/test_unit_cost_model.py` fails if either
# moves. Legs absent from this map (the four claude-*-subagent legs and
# moonshot-kimi-k3-modal) carry no token counts in any committed record, which
# is itself reported below rather than silently dropped.
LEG_MODELS: dict[str, tuple[str, str]] = {
    "anthropic-sonnet-5": ("openrouter", "anthropic/claude-sonnet-5"),
    "deepseek-v4-flash": ("openrouter", "deepseek/deepseek-v4-flash"),
    "deepseek-v4-pro": ("openrouter", "deepseek/deepseek-v4-pro"),
    "google-gemini-3.1-pro": ("openrouter", "google/gemini-3.1-pro-preview"),
    "openai-gpt-5.6-sol": ("openrouter", "openai/gpt-5.6-sol"),
}

# D1 (2026-08-23) fixed the family-lane pair: this fill leg and this review leg.
RULED_FILL_LEG = "deepseek-v4-pro"
RULED_REVIEW_LEG = "deepseek-v4-flash"

_LENGTH_ORDER = {"short": 0, "medium": 1, "long": 2}
_BAND_ORDER = {"3-5": 0, "5-8": 1, "8-11": 2, "10-13": 3, "13-16": 4, "16+": 5}


def _cell_sort_key(cell: tuple[str, str, str]) -> tuple[int, int, str]:
    """Return a stable sort key so the rendered tables never reorder."""
    band, length, style = cell
    return (_BAND_ORDER[band], _LENGTH_ORDER[length], style)


def load_records(root: Path = EVIDENCE_ROOT) -> list[dict[str, Any]]:
    """Return every committed run record, token-bearing or not.

    Args:
        root: The committed evidence root.

    Returns:
        One decoded record per ``*.record.json`` file, sorted by path.

    Raises:
        FileNotFoundError: If ``root`` does not exist, which almost always
            means the caller is not at the repository root.
    """
    if not root.is_dir():
        msg = f"evidence root {root} not found; run from the repository root"
        raise FileNotFoundError(msg)
    records: list[dict[str, Any]] = []
    for path in sorted(root.rglob("*.record.json")):
        decoded: object = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(decoded, dict):
            records.append(decoded)
    return records


def _record_cell(record: dict[str, Any]) -> tuple[str, str, str]:
    """Return the ``(band, length, style)`` cell a record was run against."""
    return (
        str(record.get("band")),
        str(record.get("length")),
        str(record.get("style")),
    )


def leg_costs(root: Path = EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Recompute per-leg cost from committed tokens and committed prices.

    Three counts are reported per leg and they are not interchangeable:
    ``records`` is every token-bearing record, ``without_error`` drops the legs
    that raised, and ``strict_pass`` keeps only those that also cleared the
    deterministic gate. Only the last are delivered books; a run that returned
    prose and then failed validation cost real money and delivered nothing.

    Args:
        root: The committed evidence root.

    Returns:
        One entry per leg that has at least one token-bearing record, keyed by
        the leg label the records use.
    """
    buckets: dict[str, list[dict[str, Any]]] = {}
    for record in load_records(root):
        leg = str(record.get("leg"))
        if leg in LEG_MODELS and isinstance(record.get("input_tokens"), int):
            buckets.setdefault(leg, []).append(record)

    out: dict[str, dict[str, Any]] = {}
    for leg, records in sorted(buckets.items()):
        out[leg] = _summarize_leg(leg, records)
    return out


def _summarize_leg(leg: str, records: list[dict[str, Any]]) -> dict[str, Any]:
    """Return one leg's cost summary from its token-bearing records.

    Args:
        leg: The leg label.
        records: That leg's token-bearing records.

    Returns:
        The summary row rendered into the per-leg table.
    """
    price = price_for(*LEG_MODELS[leg])
    priced = [
        (estimate_cost(price, r["input_tokens"], r.get("output_tokens")), r)
        for r in records
    ]
    clean = [float(e.amount_usd) for e, r in priced if not r.get("error")]
    shares = [
        (r.get("reasoning_tokens") or 0) / r["output_tokens"]
        for _, r in priced
        if r.get("output_tokens")
    ]
    return {
        "model": LEG_MODELS[leg][1],
        "records": len(records),
        "without_error": len(clean),
        "strict_pass": sum(1 for r in records if r.get("strict_pass")),
        "median_usd": round(statistics.median(clean), 4) if clean else None,
        "min_usd": round(min(clean), 4) if clean else None,
        "max_usd": round(max(clean), 4) if clean else None,
        "reasoning_share": (round(statistics.mean(shares), 4) if shares else None),
        "complete": all(e.complete for e, _ in priced),
        "cells": sorted({_record_cell(r) for r in records}, key=_cell_sort_key),
    }


def cell_weights() -> dict[tuple[str, str, str], dict[str, Any]]:
    """Return the credit weight of every offered cell, from commissioned words.

    D3 ruled that credits scale with book length and age band. Commissioned
    words are that scale: they are declared per node in the catalog, committed,
    and already what the catalog census counts, so a weight here and a size
    there cannot disagree. Weights are normalised to the smallest offered cell.

    Returns:
        One entry per offered cell, keyed by ``(band, length, style)``.

    Raises:
        ValueError: If the working directory is not the repository root, or
            if no shell covers any offered cell, which means the catalog and
            the offered grid have diverged completely.
    """
    _require_repo_root()
    by_slug = {shell.path.stem: shell for shell in load_shells()}
    populated = {
        (cell.band, cell.length, style): cell.slugs
        for cell in iter_cells()
        for style in cell.style.split("+")
        if cell.slugs
    }
    covered = offered_cells() & populated.keys()
    if not covered:
        msg = "no shell covers any offered cell; catalog and grid have diverged"
        raise ValueError(msg)

    sizes = {
        key: [by_slug[slug] for slug in populated[key] if slug in by_slug]
        for key in covered
    }
    medians = {
        key: statistics.median([s.commissioned_words for s in shells])
        for key, shells in sizes.items()
        if shells
    }
    base = min(medians.values())
    return {
        key: {
            "shells": len(sizes[key]),
            "median_words": int(medians[key]),
            "median_nodes": int(statistics.median([s.nodes for s in sizes[key]])),
            "weight": round(medians[key] / base, 2),
        }
        for key in sorted(medians, key=_cell_sort_key)
    }


def _require_repo_root() -> None:
    """Fail loudly when the process is not rooted at the repository.

    Same anchoring `scripts/catalog_census.py` states in full: `load_shells`
    honours a relative root but `iter_cells` reaches `skeleton_match`, whose
    root is a module-level relative constant with no override, so the two
    halves would describe different catalogs from any other directory.

    Raises:
        ValueError: If the working directory is not the repository root.
    """
    if Path.cwd() != _REPO_ROOT:
        msg = (
            f"run this from the repository root ({_REPO_ROOT}); "
            f"the working directory is {Path.cwd()}."
        )
        raise ValueError(msg)


def load_fill_books(root: Path = FILL_EVIDENCE_ROOT) -> list[dict[str, Any]]:
    """Return every billed book record from the vendor-comparison fill runs.

    This is a different workload from `load_records`. That one reads skeleton
    authoring: a leg is asked to invent a story shell from a premise, and its
    record accumulates every attempt and repair round. This one reads prose
    fill: a leg is given a finished skeleton and writes the bodies. Only the
    second is what a family's book costs, so only the second may anchor a price.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        Book records carrying a metered `cost`, in path order. Records without
        one are dropped: the runs recorded `cost: null` before the cost
        instrumentation landed (`AL-329`), and a null is not a zero.
    """
    _require_repo_root()
    catalog = {shell.path.stem: shell for shell in load_shells()}
    books: list[dict[str, Any]] = []
    for report in sorted((_REPO_ROOT / root).glob("**/report.json")):
        data: dict[str, Any] = json.loads(report.read_text(encoding="utf-8"))
        if data.get("mock"):
            continue
        skeletons: list[str] = [str(name) for name in data.get("skeletons", [])]
        for raw in data.get("books", []):
            book: dict[str, Any] = dict(raw)
            if book.get("cost") is None:
                continue
            index = int(book.get("brief_index", -1))
            slug = Path(skeletons[index]).stem if 0 <= index < len(skeletons) else ""
            shell = catalog.get(slug)
            book["skeleton"] = slug
            book["band"] = shell.band if shell else ""
            book["commissioned_words"] = shell.commissioned_words if shell else 0
            books.append(book)
    return books


def fill_by_band(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Summarize billed fill cost per age band.

    The band comes from the skeleton the book filled, not from the book, so it
    is the catalog's own classification rather than anything the run asserted.
    Reporting per band is what makes the model's linear scaling falsifiable: if
    dollars per commissioned word were wildly different at `3-5` and `16+`, a
    single rate scaled by word count would be indefensible, and this table is
    where that would show.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        One summary per band that has at least one delivered book, ordered by
        band.
    """
    by_band: dict[str, list[dict[str, Any]]] = {}
    for book in load_fill_books(root):
        if book["band"] and book.get("complete"):
            by_band.setdefault(str(book["band"]), []).append(book)

    out: dict[str, dict[str, Any]] = {}
    for band in sorted(by_band, key=lambda b: _BAND_ORDER.get(b, 99)):
        books = by_band[band]
        billed = sum(float(b["cost"]) for b in books)
        commissioned = sum(int(b["commissioned_words"]) for b in books)
        delivered_words = sum(int(b["leaf_words"] or 0) for b in books)
        if commissioned <= 0:
            continue
        out[band] = {
            "books": len(books),
            "billed_usd": round(billed, 4),
            "commissioned_words": commissioned,
            "delivered_words": delivered_words,
            "usd_per_1k_commissioned_words": round(1000 * billed / commissioned, 4),
            "delivered_share_of_commission": round(delivered_words / commissioned, 3),
        }
    return out


def fill_costs(root: Path = FILL_EVIDENCE_ROOT) -> dict[str, dict[str, Any]]:
    """Summarize billed prose-fill cost per leg.

    The figures are metered, not recomputed. The book records carry no
    `input_tokens`, so a token-derived estimate is not even available here, and
    the billed number is the better evidence anyway: it is what was charged,
    including whatever endpoint, cache state and discount actually applied.

    Failed books are charged to the books that landed. A call that returns
    nothing is still billed and still has to be retried, so cost per delivered
    book is the figure a subscription has to cover; cost per call is not.

    Args:
        root: Directory holding the comparison runs, relative to the repo root.

    Returns:
        One summary per leg, keyed by the leg label the run recorded.
    """
    by_leg: dict[str, list[dict[str, Any]]] = {}
    for book in load_fill_books(root):
        by_leg.setdefault(str(book.get("vendor")), []).append(book)

    out: dict[str, dict[str, Any]] = {}
    for leg, books in sorted(by_leg.items()):
        delivered = [
            b for b in books if b.get("complete") and int(b.get("leaf_words") or 0) > 0
        ]
        if not delivered:
            continue
        billed = sum(float(b["cost"]) for b in books)
        failed = billed - sum(float(b["cost"]) for b in delivered)
        words = sum(int(b["leaf_words"]) for b in delivered)
        per_1k = [1000 * float(b["cost"]) / int(b["leaf_words"]) for b in delivered]
        emitted = sum(int(b.get("output_tokens") or 0) for b in delivered)
        out[leg] = {
            "source": "metered",
            "books": len(books),
            "delivered": len(delivered),
            "billed_usd": round(billed, 4),
            "failed_usd": round(failed, 4),
            "words": words,
            "usd_per_delivered_book": round(billed / len(delivered), 4),
            "usd_per_1k_words": round(1000 * billed / words, 4),
            "usd_per_1k_words_min": round(min(per_1k), 4),
            "usd_per_1k_words_max": round(max(per_1k), 4),
            "output_tokens_per_word": round(emitted / words, 2),
            "reasoning_tokens": sum(int(b.get("reasoning_tokens") or 0) for b in books),
        }
    return out


def _headroom(
    cells: dict[tuple[str, str, str], dict[str, Any]],
) -> list[dict[str, Any]]:
    """Return per-price-point headroom against the billed fill rate.

    An earlier draft of this model scaled the skeleton-authoring cost by fill
    word counts. Those are different workloads measured on different corpora,
    so that was a category error and the figures it produced were meaningless.
    This scales the measured dollars-per-thousand-delivered-words on the ruled
    fill leg by each cell's commissioned words.

    The scaling is still an assumption, but now a checked one: across the five
    delivered books the per-thousand-word rate varies by a factor the model
    reports, over a book-size range it also reports, so a reader can see how
    much of the linearity is evidence and how much is extrapolation.

    Args:
        cells: The per-cell credit weights, carrying commissioned words.

    Returns:
        One row per candidate price point, or an empty list when the ruled fill
        leg has no billed record.
    """
    fill = fill_costs().get(RULED_FILL_LEG)
    if not fill:
        return []
    rate = float(fill["usd_per_1k_words"])
    scaled = {
        cell: rate * int(row["median_words"]) / 1000 for cell, row in cells.items()
    }
    cheapest = min(scaled, key=lambda c: scaled[c])
    dearest = max(scaled, key=lambda c: scaled[c])
    return [
        {
            "price_usd": price,
            "basis": "billed fill, ruled leg",
            "usd_per_1k_words": fill["usd_per_1k_words"],
            "cheapest_cell": "/".join(cheapest),
            "dearest_cell": "/".join(dearest),
            "scaled_min_usd": round(scaled[cheapest], 4),
            "scaled_max_usd": round(scaled[dearest], 4),
            "share_of_price_min": round(scaled[cheapest] / price, 4),
            "share_of_price_max": round(scaled[dearest] / price, 4),
        }
        for price in PRICE_POINTS_USD
    ]


def model() -> dict[str, Any]:
    """Compute the whole unit-cost model.

    Returns:
        A JSON-serializable model: per-leg costs, per-cell credit weights,
        headroom at each candidate price point, and the assumptions that are
        not measured. ``cap`` is always ``None``; see the module docstring.
    """
    legs = leg_costs()
    cells = cell_weights()
    measured = {tuple(c) for row in legs.values() for c in row["cells"]}
    unpriced = sorted(
        {
            str(r.get("leg"))
            for r in load_records()
            if str(r.get("leg")) not in LEG_MODELS
        }
    )
    return {
        "legs": legs,
        "fill": fill_costs(),
        "fill_by_band": fill_by_band(),
        "cells": {"/".join(k): v for k, v in cells.items()},
        "coverage": {
            "offered_cells": len(offered_cells()),
            "measured_cells": len(measured),
            "measured": sorted("/".join(c) for c in measured),
            "legs_without_token_records": unpriced,
        },
        "headroom": _headroom(cells),
        "cap": None,
        "assumptions": {
            "scaling": (
                "Cost at an unmeasured cell is the billed dollars-per-thousand "
                "delivered words on the ruled fill leg, scaled by that cell's "
                "commissioned words. Linear by assumption, but the assumption "
                "is checkable here rather than bare: the per-thousand-word rate "
                "and its spread across the delivered books are both reported "
                "below, over the book-size range those books actually covered."
            ),
            "review_leg": (
                f"D1 ruled the review leg to `{RULED_REVIEW_LEG}`, and no "
                "committed run bills that leg on the fill workload, so every "
                "figure here is the FILL half of the pair only. The review pass "
                "is a real cost that is simply not measured; treat the headroom "
                "numbers as a floor, never as the pair."
            ),
            "workloads": (
                "Skeleton authoring and prose fill are separate workloads on "
                "separate corpora and must not be scaled by each other's word "
                "counts. The skeleton table below prices inventing a story "
                "shell, including every retry and repair round in the record; "
                "the fill table prices writing the prose for a finished shell."
            ),
            "human_minutes": (
                "D3 ruled that human approval minutes are costed at a notional "
                "rate rather than excluded, but named no rate, and S-6 has not "
                "run, so the minutes are unmeasured. No minutes term is folded "
                "into any figure here; every cost below is LLM spend only."
            ),
            "modal": (
                "Modal is billed per GPU-second and carries no per-MTok price, "
                "so a Modal-served leg cannot be costed from this table at all."
            ),
        },
    }


def _render_legs(data: dict[str, Any]) -> list[str]:
    """Return the per-leg cost table lines."""
    lines = [
        "## Skeleton-authoring cost, recomputed from committed tokens",
        "",
        (
            "**This is not the cost of a book.** It prices inventing a story "
            "shell from a premise, and each record accumulates every attempt "
            "and repair round it took, so a record is a whole authoring "
            "episode rather than a call. Recomputed as `input_tokens x input "
            "price + output_tokens x output price` using `core/pricing.py`, "
            "over the committed run records that carry token counts. "
            "`delivered` counts records that also cleared the deterministic "
            "gate; the others cost money and delivered nothing."
        ),
        "",
        (
            "| Leg | Model | Records | No error | Delivered | Median $ | "
            "Min $ | Max $ | Reasoning share |"
        ),
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for leg, row in data["legs"].items():
        share = row["reasoning_share"]
        lines.append(
            f"| `{leg}` | `{row['model']}` | {row['records']} | "
            f"{row['without_error']} | {row['strict_pass']} | "
            f"{row['median_usd']:.4f} | {row['min_usd']:.4f} | "
            f"{row['max_usd']:.4f} | "
            f"{'n/a' if share is None else f'{share:.1%}'} |"
        )
    return lines


def _render_fill(data: dict[str, Any]) -> list[str]:
    """Return the billed prose-fill cost table lines."""
    lines = [
        "## Prose-fill cost, as billed",
        "",
        (
            "This is what a book costs. The figures are metered, not "
            "recomputed: the book records carry no `input_tokens`, and the "
            "billed number is better evidence anyway because it already "
            "includes whichever endpoint, cache state and discount applied. "
            "Failed books are charged to the books that landed, because a call "
            "that returns nothing is still billed and still has to be retried."
        ),
        "",
        (
            "| Leg | Books | Delivered | Billed $ | Spent on failures $ | "
            "Words delivered | $/delivered book | $/1k words | $/1k words "
            "range | Output tok/word |"
        ),
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    lines.extend(
        f"| `{leg}` | {row['books']} | {row['delivered']} | "
        f"{row['billed_usd']:.4f} | {row['failed_usd']:.4f} | "
        f"{row['words']:,} | {row['usd_per_delivered_book']:.4f} | "
        f"{row['usd_per_1k_words']:.4f} | "
        f"{row['usd_per_1k_words_min']:.4f} to "
        f"{row['usd_per_1k_words_max']:.4f} | "
        f"{row['output_tokens_per_word']:.2f} |"
        for leg, row in data["fill"].items()
    )
    return lines


def _render_fill_bands(data: dict[str, Any]) -> list[str]:
    """Return the per-band billed fill table lines."""
    lines = [
        "### The same cost, per band",
        "",
        (
            "The band is the catalog's classification of the skeleton each "
            "book filled, not anything the run asserted. This table is what "
            "makes the linear scaling below falsifiable: if dollars per "
            "commissioned word differed sharply across bands, scaling one rate "
            "by word count would be indefensible."
        ),
        "",
        (
            "| Band | Books | Billed $ | Commissioned words | Scorable words "
            "delivered | Scorable share | $/1k commissioned words |"
        ),
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    lines.extend(
        f"| `{band}` | {row['books']} | {row['billed_usd']:.4f} | "
        f"{row['commissioned_words']:,} | {row['delivered_words']:,} | "
        f"{row['delivered_share_of_commission']:.1%} | "
        f"{row['usd_per_1k_commissioned_words']:.4f} |"
        for band, row in data["fill_by_band"].items()
    )
    rates = [
        row["usd_per_1k_commissioned_words"] for row in data["fill_by_band"].values()
    ]
    if rates:
        lines += [
            "",
            (
                f"That rate spans {min(rates):.4f} to {max(rates):.4f}, a factor "
                f"of {max(rates) / min(rates):.2f} across the bands measured, so "
                "a single rate scaled by commissioned words is a defensible "
                "approximation over this range and an extrapolation outside it."
            ),
            "",
            (
                "**Read the scorable share carefully.** It is measured scorable "
                "words over the skeleton's commission, and `measure_book` scores "
                "only what it can score, so a share near half is consistent with "
                "books delivering about half their commissioned length AND with "
                "the measurement excluding much of what they wrote. Nothing "
                "committed separates those, and the difference matters: the first "
                "would mean these books are short, the second would mean the "
                "dollars-per-word figures above are pessimistic by up to 2x."
            ),
        ]
    return lines


def _render_cells(data: dict[str, Any]) -> list[str]:
    """Return the per-cell credit weight table lines."""
    lines = [
        "## Credit weight by cell",
        "",
        (
            "D3 ruled credits scale with book length and age band. The scale "
            "is commissioned words from the skeleton catalog, normalised to "
            "the smallest offered cell. Today's gate "
            "(`story_requests/service.py::enforce_family_quota`) counts "
            "stories instead, so every row below currently costs a family "
            "exactly 1."
        ),
        "",
        "| Cell | Shells | Median nodes | Median commissioned words | Credits |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for cell, row in data["cells"].items():
        lines.append(
            f"| `{cell}` | {row['shells']} | {row['median_nodes']} | "
            f"{row['median_words']:,} | {row['weight']:.2f} |"
        )
    return lines


def _render_headroom(data: dict[str, Any]) -> list[str]:
    """Return the headroom table lines."""
    lines = [
        "## Headroom at each candidate price point",
        "",
        (
            "D3 left the subscription at $1.99 or $4.99 and did not choose, so "
            "no absolute per-book cap is derived here. Each cell's cost is the "
            "billed rate above times that cell's median commissioned words. "
            "**Fill only**: the ruled review leg has no billed record, so every "
            "share below is a floor."
        ),
        "",
        (
            "| Price | $/1k words | Cheapest cell | Scaled min $ | Dearest "
            "cell | Scaled max $ | Max share of price |"
        ),
        "| ---: | ---: | --- | ---: | --- | ---: | ---: |",
    ]
    lines.extend(
        f"| ${row['price_usd']:.2f} | {row['usd_per_1k_words']:.4f} | "
        f"`{row['cheapest_cell']}` | {row['scaled_min_usd']:.4f} | "
        f"`{row['dearest_cell']}` | {row['scaled_max_usd']:.4f} | "
        f"{row['share_of_price_max']:.1%} |"
        for row in data["headroom"]
    )
    return lines


def render(data: dict[str, Any]) -> str:
    """Render the model as the committed markdown page.

    Args:
        data: The model returned by :func:`model`.

    Returns:
        The full page text, ending in a newline.
    """
    cov = data["coverage"]
    lines = [
        "# Per-book unit-cost model",
        "",
        _MARKER,
        "",
        "Regenerate with `uv run python scripts/unit_cost_model.py --write`.",
        "",
        "## What is measured, and what is not",
        "",
        (
            "This model reads two different corpora and they must not be "
            "confused. **Skeleton authoring** invents a story shell from a "
            "premise; **prose fill** writes the bodies for a shell that already "
            "exists. Only the second is what a family's book costs."
        ),
        "",
        f"The skeleton-authoring records carry token counts for "
        f"**{cov['measured_cells']} of the {cov['offered_cells']} offered "
        "cells**: " + ", ".join(f"`{c}`" for c in cov["measured"]) + ".",
        "",
        (
            f"The fill records are billed rather than recomputed and cover "
            f"**{data['fill_by_band'] and len(data['fill_by_band'])} of the 6 "
            "age bands**: "
        )
        + ", ".join(f"`{b}`" for b in data["fill_by_band"])
        + ". There is no delivered fill book at `3-5`, `5-8` or `10-13`, so "
        "every figure at those bands is scaled from the bands that were "
        "measured.",
        "",
        "These legs appear in the committed records but carry no token counts "
        "at all, so they cannot be costed from this evidence: "
        + ", ".join(f"`{leg}`" for leg in cov["legs_without_token_records"])
        + ".",
        "",
    ]
    lines += [*_render_legs(data), ""]
    lines += [*_render_fill(data), ""]
    lines += [*_render_fill_bands(data), ""]
    lines += [*_render_cells(data), ""]
    lines += [*_render_headroom(data), ""]
    lines += ["## Assumptions", ""]
    for name, text in data["assumptions"].items():
        lines.append(f"- **{name}**: {text}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run the CLI.

    Args:
        argv: Argument vector, or ``None`` to read ``sys.argv``.

    Returns:
        0 on success, 1 when ``--check`` finds the doc stale.
    """
    parser = argparse.ArgumentParser(
        description="Emit the per-book unit-cost model from committed evidence."
    )
    parser.add_argument("--json", action="store_true", help="emit JSON")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate the doc")
    mode.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args(argv)

    data = model()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True, default=str))
        return 0
    text = render(data)
    if args.write:
        GENERATED_DOC.write_text(text, encoding="utf-8")
        return 0
    if args.check:
        current = (
            GENERATED_DOC.read_text(encoding="utf-8") if GENERATED_DOC.exists() else ""
        )
        if current != text:
            print(f"{GENERATED_DOC} is stale; run with --write", file=sys.stderr)
            return 1
        return 0
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
