"""Tests for the naive-ux-check scenario data file and its paste-block renderer.

`scenarios.json` (`.claude/skills/naive-ux-check/scenarios.json`) is the
single source of truth for the 17 naive-user comprehension scenarios
(K0-K4, G0-G7, A0-A3; task D2a). `render.py`
(`.claude/skills/naive-ux-check/render.py`) is the single composer of the
block a human pastes into the Claude-for-Chrome extension: SKILL.md step 4
runs it rather than composing the block itself, so this module imports and
exercises the actual module the skill executes, not a test-local stand-in.

Three properties matter enough to be enforced by structure rather than by a
human reading SKILL.md's instructions:

1. Every scenario round-trips: all required fields are present and
   non-empty, and the id set is exactly the expected 17 with no
   duplicates.
2. Operator-only content (`operator_notes`: operator setup lines, operator
   notes, persona context, and expected-observations paragraphs) can never
   reach the block that gets pasted into the model. SKILL.md says twice,
   emphatically, that a prompt leaking its own expected observations tests
   transcription, not comprehension, so every verdict downstream of a leak
   would be worthless.
3. SKILL.md step 4 keeps running `render.py`. SKILL.md is the program an
   agent executes when it invokes this skill, so an edit that drops the
   renderer invocation and tells the agent to compose the block by hand is
   a live path to the leak, no matter how safe `render.py` itself is.

Property 2 is pinned by two generic checks that never rebuild the block:

* a **narrowing** check, that a record stripped to `id` plus the three
  model-facing fields renders byte-identically to the real record, so
  nothing outside those three is *read*; and
* a **sentinel** check, that replacing every string leaf outside those
  three fields with a unique `__LEAK_n__` marker leaves no marker in the
  output, so nothing outside those three is *emitted*. The markers are
  generated by tree-walk rather than by naming fields, so the check
  survives schema growth: a sub-key added under `operator_notes`, or a
  brand-new top-level field, gets a marker without anyone editing this
  file.

The block's *shape* is pinned separately, by hand-transcribed golden blocks
for K0, G4 and A1. An earlier revision compared the render against a
reference function that rebuilt the same f-string from the same three
fields; that reference was a line-for-line clone of the composer, so the
two moved together and the suite pinned nothing about the format. A golden
has to be re-transcribed by a human when the format changes, which is
exactly the friction that was missing.

One claim an earlier revision of this docstring got wrong, corrected here:
a brand-new top-level field in `scenarios.json` is **not** caught merely by
existing. Adding one with the renderer untouched changes no output and
fails nothing, which is correct: an unread field is not a leak. What is
caught is a *leak through* such a field, that is, a field the composer has
also been changed to read. The sentinel check catches that generically, and
the narrowing check makes the composer raise `KeyError` the moment it reads
anything the stripped record does not carry.

What none of this defends against, stated plainly rather than left to be
discovered: operator-style text written straight into `persona_text`,
`task_text`, or `report_back_questions` reaches the model, because those
three fields are model-facing by design. The operator/model split is a
boundary between fields, not a classifier of content, so keeping "what the
operator should notice" out of those three is an authoring convention, not
a control any test here can enforce.
"""

from __future__ import annotations

import importlib.util
import itertools
import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

if TYPE_CHECKING:
    from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILL_DIR = REPO_ROOT / ".claude" / "skills" / "naive-ux-check"
SCENARIOS_PATH = SKILL_DIR / "scenarios.json"
RENDER_MODULE_PATH = SKILL_DIR / "render.py"
SKILL_MD_PATH = SKILL_DIR / "SKILL.md"

# The exact command SKILL.md step 4 must keep telling the agent to run. Repo
# relative, because that is how the step is written and how a user pastes it.
RENDERER_INVOCATION = "python3 .claude/skills/naive-ux-check/render.py"

# Not a real target; only used to exercise the <URL> substitution the
# renderer performs. Never resolved to a live host.
_TEST_URL = "https://example.invalid/"

# This test module's own statement of which scenario fields are model-facing,
# written out here rather than imported from `render.py`. Importing the
# production tuple would make both sides move together, which is the failure
# this file already made once. It is deliberately NOT asserted to equal
# `render_module.MODEL_FACING_FIELDS`: pinning the constant's contents is
# decoration. It is used to build the stripped and sentinel-bearing records
# below, so a composer that reads a fourth field fails behaviourally.
_MODEL_FACING_FIELD_NAMES = ("persona_text", "task_text", "report_back_questions")

EXPECTED_IDS = (
    [f"K{i}" for i in range(5)]
    + [f"G{i}" for i in range(8)]
    + [f"A{i}" for i in range(4)]
)

REQUIRED_FIELDS = (
    "id",
    "persona",
    "name",
    "persona_text",
    "task_text",
    "report_back_questions",
    "requires_credentials",
    "production_safe",
    "operator_notes",
)

MUTATING_SCENARIO_IDS = frozenset({"G4", "G5", "G6", "A2", "A3"})

PREFIX_TO_PERSONA = {"K": "kid", "G": "guardian", "A": "admin"}


def _load_scenarios() -> list[dict[str, Any]]:
    return json.loads(SCENARIOS_PATH.read_text(encoding="utf-8"))


def _load_render_module() -> ModuleType:
    """Import the real `render.py` the skill executes, by file path.

    `.claude/skills/naive-ux-check/` is not a Python package (it is a
    Claude Code skill directory, not part of `src/cyo_adventure`), so this
    loads the module directly from its path rather than via a package
    import. This is the module under test for the leak property: there is
    exactly one paste-block composer in the repository, and this is it.
    """
    spec = importlib.util.spec_from_file_location(
        "naive_ux_check_render", RENDER_MODULE_PATH
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load render module from {RENDER_MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


render_module = _load_render_module()


# ---------------------------------------------------------------------------
# Golden paste blocks. Hand-transcribed from `scenarios.json` against the
# shape SKILL.md step 4 documents, NOT computed from the record. If the
# format changes, these must be retyped by a person; that friction is the
# point. K0 is the non-credentialed production-safe scenario, G4 is a
# mutating guardian scenario with non-empty `operator_notes`, and A1 is the
# only scenario carrying `operator_notes.persona_context`. Every scenario's
# operator content is absent from all three, by inspection.
# ---------------------------------------------------------------------------

GOLDEN_K0 = (
    "Persona: You are a 7-year-old who was just handed a brand-new tablet. Nobody in your family has used this app on it before, and no grown-up is nearby right now.\n"
    "\n"
    "Task: Go to https://example.invalid/ and try to start reading a story, using only what's on the screen.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What you clicked, in order, and why at each step.\n"
    "2. What the screen told you when you couldn't go any further, in your own words.\n"
    "3. Whether that screen felt friendly and clear about what to do next, or like something was broken.\n"
    '4. Whether you knew what to do next (even if it was "go find a grown-up"), or felt stuck.'
)

GOLDEN_G4 = (
    "Persona: You are a parent who just approved your child's story idea.\n"
    "\n"
    "Task: Go to https://example.invalid/, sign in, find your child's pending story request, and approve it. Then figure out whether there's anything else you still need to do before your child can actually read the story.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What happened right after you approved the request.\n"
    "2. Whether anything told you a second review step exists before the story reaches your child.\n"
    "3. If you had to go looking for that second step, how you found it.\n"
    "4. Whether you'd have assumed you were done after the first approval."
)

GOLDEN_A1 = (
    "Persona: You were just told you're an admin on this app, with no other explanation of what that means.\n"
    "\n"
    "Task: Go to https://example.invalid/, sign in, and try to figure out what, if anything, you can do that a regular parent account couldn't.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What, if anything, looked different from what you'd expect a parent account to see.\n"
    "2. Whether you found any action that felt admin-specific.\n"
    '3. How confident you are that you have elevated capability at all, on a scale of "certain" to "no idea."\n'
    "4. What you would look for next if you still weren't sure."
)

GOLDEN_BLOCKS = {"K0": GOLDEN_K0, "G4": GOLDEN_G4, "A1": GOLDEN_A1}


def _sentinelize(scenario: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    """Copy `scenario`, replacing every string leaf outside the three fields.

    Walks dicts and lists recursively instead of naming today's
    `operator_notes` sub-keys, so a field added anywhere in the schema
    later is sentinel-marked automatically. `id` is marked too, and the
    marked id is what the caller renders by, which is why nine scenarios
    with entirely empty `operator_notes` still exercise this check.
    """
    counter = itertools.count(1)
    sentinels: list[str] = []

    def walk(node: Any) -> Any:
        if isinstance(node, str):
            marker = f"__LEAK_{next(counter)}__"
            sentinels.append(marker)
            return marker
        if isinstance(node, dict):
            return {key: walk(value) for key, value in node.items()}
        if isinstance(node, list):
            return [walk(item) for item in node]
        return node

    marked = {
        key: value if key in _MODEL_FACING_FIELD_NAMES else walk(value)
        for key, value in scenario.items()
    }
    return marked, sentinels


def _write_scenarios(tmp_path: Path, records: list[dict[str, Any]]) -> Path:
    path = tmp_path / "scenarios.json"
    path.write_text(json.dumps(records), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# SKILL.md text helpers. SKILL.md is the program an agent runs, so its step 4
# is checked the way a program is checked.
# ---------------------------------------------------------------------------

_NEGATION_RE = re.compile(r"\b(never|not|avoid|without)\b", re.IGNORECASE)
_SELF_COMPOSE_RE = re.compile(r"\byourself\b", re.IGNORECASE)
_OPERATOR_FIELD_RE = re.compile(
    r"operator_notes|operator_setup|operator_note|persona_context"
    r"|expected_observations",
    re.IGNORECASE,
)
# Verbs that would put operator content INTO the block. Deliberately excludes
# "relay" and "paste", which step 4 legitimately uses for telling the operator
# things out of band, outside the pasted text.
_INSERTION_VERB_RE = re.compile(
    r"\b(append\w*|inline\w*|includ\w*|embed\w*|insert\w*|copy|copies|copying)\b",
    re.IGNORECASE,
)


def _skill_md_text() -> str:
    return SKILL_MD_PATH.read_text(encoding="utf-8")


def _skill_md_step(number: int) -> str:
    """Return the text of one top-level numbered step of SKILL.md.

    Steps start at column 0 as `N. `; their continuation lines are
    indented. Returns everything from that marker up to the next
    column-0 numbered step or the next `## ` heading.
    """
    lines = _skill_md_text().splitlines()
    start = next(
        (i for i, line in enumerate(lines) if line.startswith(f"{number}. ")), None
    )
    assert start is not None, f"SKILL.md has no step {number}"
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if re.match(r"^\d+\. ", lines[i]) or lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def _sentences(text: str) -> list[str]:
    """Unwrap markdown line wrapping and split into rough sentences.

    Splits on `.`, `:`, `;`, `!` and `?` followed by whitespace. Rough is
    fine: the checks below only ask whether a negation sits in the same
    sentence as a risky instruction, and over-splitting makes them
    stricter, never laxer.
    """
    flat = re.sub(r"\s+", " ", text)
    return [part for part in re.split(r"(?<=[.:;!?])\s+", flat) if part.strip()]


# ---------------------------------------------------------------------------
# Round-trip: every one of the 17 scenarios has every required field,
# non-empty, and the id set is exactly right with no duplicates.
# ---------------------------------------------------------------------------


def test_scenario_ids_are_exactly_the_expected_17_with_no_duplicates():
    scenarios = _load_scenarios()
    ids = [s["id"] for s in scenarios]
    assert len(ids) == 17, f"expected 17 scenarios, found {len(ids)}: {ids}"
    assert len(ids) == len(set(ids)), "duplicate scenario ids in scenarios.json"
    assert set(ids) == set(EXPECTED_IDS), (
        f"id set mismatch: missing={set(EXPECTED_IDS) - set(ids)}, "
        f"unexpected={set(ids) - set(EXPECTED_IDS)}"
    )
    # Array order is the selection order SKILL.md relies on: K0-K4, G0-G7,
    # A0-A3, with each persona's auth-gate scenario first in its group.
    assert ids == EXPECTED_IDS


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_scenario_has_all_required_fields_non_empty(scenario: dict[str, Any]):
    for field in REQUIRED_FIELDS:
        assert field in scenario, f"{scenario.get('id', '?')} missing field {field!r}"

    assert scenario["id"].strip()
    assert scenario["name"].strip()
    assert scenario["persona_text"].strip()
    assert scenario["task_text"].strip()
    assert scenario["persona"] in ("kid", "guardian", "admin")
    assert isinstance(scenario["requires_credentials"], bool)
    assert isinstance(scenario["production_safe"], bool)

    questions = scenario["report_back_questions"]
    assert isinstance(questions, list)
    assert len(questions) > 0
    assert all(isinstance(q, str) and q.strip() for q in questions)

    assert isinstance(scenario["operator_notes"], dict)


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_persona_field_matches_id_prefix(scenario: dict[str, Any]):
    expected_persona = PREFIX_TO_PERSONA[scenario["id"][0]]
    assert scenario["persona"] == expected_persona


def test_credential_and_production_safety_posture_is_unchanged():
    """D2a records these facts; it must not loosen them.

    Per SKILL.md: only K0 (the fresh-device auth-gate scenario) is
    non-credentialed and production-safe. Every other scenario either
    signs in with staging-only seeded credentials or mutates content.
    """
    scenarios = {s["id"]: s for s in _load_scenarios()}
    assert scenarios["K0"]["production_safe"] is True
    assert scenarios["K0"]["requires_credentials"] is False
    for sid, scenario in scenarios.items():
        if sid == "K0":
            continue
        assert scenario["production_safe"] is False, (
            f"{sid} must not be production_safe"
        )
        assert scenario["requires_credentials"] is True, (
            f"{sid} must require credentials"
        )

    for sid in MUTATING_SCENARIO_IDS:
        assert scenarios[sid]["production_safe"] is False


def test_a1_persona_context_gives_the_dropped_admin_premise_a_home():
    """Minor 5: admin.md's premise paragraph must live somewhere, not nowhere.

    D2a's migration dropped admin.md's substantive preamble (admins reuse
    every /guardian/* route; the distinguishing signals are the muted
    "Admin" hint, the absent "Books" link, the cross-family picker, and the
    moderation nav) with no replacement home. It is the stated premise of
    A1 ("indistinguishable surface"), so it now lives in
    `A1.operator_notes.persona_context`, an operator-only field alongside
    `operator_setup`/`operator_note`/`expected_observations`. This pins
    that it stays populated, not merely present.
    """
    scenarios = {s["id"]: s for s in _load_scenarios()}
    persona_context = scenarios["A1"]["operator_notes"]["persona_context"]
    assert isinstance(persona_context, list)
    assert persona_context, "A1 persona_context must not be empty"
    assert all(isinstance(text, str) and text.strip() for text in persona_context)


# ---------------------------------------------------------------------------
# Shape: hand-transcribed goldens. Nothing here recomputes the format.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scenario_id", sorted(GOLDEN_BLOCKS))
def test_golden_paste_block_is_rendered_verbatim(scenario_id: str):
    """The render must equal a block a human typed out, character for character.

    If this fails after a deliberate format change, retype the golden from
    `scenarios.json` and SKILL.md step 4's documented shape. Do not
    regenerate it from `render.py`: a computed reference is what the
    previous revision had, and it moved in lockstep with the composer.
    """
    rendered = render_module.render_paste_block(scenario_id, _TEST_URL)
    assert rendered == GOLDEN_BLOCKS[scenario_id]


# ---------------------------------------------------------------------------
# The leak property: nothing outside the three model-facing fields is read,
# and nothing outside them is emitted.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_render_reads_nothing_beyond_the_three_model_facing_fields(
    scenario: dict[str, Any], tmp_path: Path
):
    """A record stripped to the three fields renders identically to the real one.

    Narrowing check. If a future edit makes the composer read a fourth
    field, the stripped record raises `KeyError` here. If the composer
    starts reading something it happens to find on the real record, the two
    renders diverge. Either way this goes red without anyone having to
    anticipate which field.
    """
    stripped = {"id": scenario["id"]} | {
        field: scenario[field] for field in _MODEL_FACING_FIELD_NAMES
    }
    stripped_path = _write_scenarios(tmp_path, [stripped])

    from_stripped = render_module.render_paste_block(
        scenario["id"], _TEST_URL, scenarios_path=stripped_path
    )
    from_real = render_module.render_paste_block(scenario["id"], _TEST_URL)
    assert from_stripped == from_real


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_no_sentinel_from_outside_the_three_fields_reaches_the_render(
    scenario: dict[str, Any], tmp_path: Path
):
    """Every string leaf outside the three model-facing fields must stay out.

    Sentinel check. The markers are generated by walking the record, so a
    sub-key added under `operator_notes` later, or a brand-new top-level
    field, is covered with no edit here. Substituting markers rather than
    searching for the operator's real prose also removes the
    false-positive risk that operator text shares short substrings with
    the task text.
    """
    marked, sentinels = _sentinelize(scenario)
    assert sentinels, f"{scenario['id']}: no string leaves outside the three fields"
    marked_path = _write_scenarios(tmp_path, [marked])

    rendered = render_module.render_paste_block(
        marked["id"], _TEST_URL, scenarios_path=marked_path
    )
    leaked = [marker for marker in sentinels if marker in rendered]
    assert not leaked, f"{scenario['id']}: operator content reached the block: {leaked}"


def test_sentinel_check_would_catch_an_actual_leak(tmp_path: Path):
    """Proves the sentinel check above is not vacuous.

    Renders a sentinel-marked K0, then appends its marked `operator_notes`
    to the output the way a leaking composer would, and confirms the same
    detector fires. Without this, a sentinel check that never sees a
    positive is indistinguishable from one whose markers never appear
    anywhere.
    """
    k0 = next(s for s in _load_scenarios() if s["id"] == "K0")
    marked, sentinels = _sentinelize(k0)
    marked_path = _write_scenarios(tmp_path, [marked])

    rendered = render_module.render_paste_block(
        marked["id"], _TEST_URL, scenarios_path=marked_path
    )
    leaky = rendered + "\n\n" + json.dumps(marked["operator_notes"])

    assert not [marker for marker in sentinels if marker in rendered]
    assert [marker for marker in sentinels if marker in leaky], (
        "the detector found nothing in a deliberately leaky block, so it would "
        "not have caught a real leak either"
    )


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_no_literal_url_placeholder_survives_into_the_render(
    scenario: dict[str, Any],
):
    rendered = render_module.render_paste_block(scenario["id"], _TEST_URL)
    assert "<URL>" not in rendered, (
        f"{scenario['id']}: an unsubstituted <URL> reached the paste block"
    )
    assert _TEST_URL in rendered, f"{scenario['id']}: the target URL never appeared"


def test_every_url_placeholder_in_both_substituted_fields_is_replaced(tmp_path: Path):
    """Repeated and cross-field `<URL>` placeholders must all be substituted.

    The 17 real scenarios each carry exactly one `<URL>`, in `task_text`,
    so they cannot distinguish "replaces every occurrence in both fields"
    from "replaces the first occurrence in `task_text`". This synthetic
    record can.
    """
    synthetic = {
        "id": "SYNTH",
        "persona_text": "persona head <URL> persona tail <URL>",
        "task_text": "task head <URL> task tail <URL>",
        "report_back_questions": ["first question.", "second question."],
    }
    synthetic_path = _write_scenarios(tmp_path, [synthetic])

    rendered = render_module.render_paste_block(
        "SYNTH", _TEST_URL, scenarios_path=synthetic_path
    )
    assert "<URL>" not in rendered
    assert rendered.count(_TEST_URL) == 4, (
        f"expected 4 substitutions, got {rendered.count(_TEST_URL)}: {rendered!r}"
    )


# ---------------------------------------------------------------------------
# SKILL.md is the program: step 4 must keep running the renderer.
# ---------------------------------------------------------------------------


def test_skill_md_step_4_invokes_the_renderer():
    """Step 4 must contain the literal renderer invocation, in a fenced block.

    A safe `render.py` buys nothing if SKILL.md stops calling it. An agent
    invoking this skill reads step 4 and does what it says, so rewriting
    step 4 to compose the block from the scenario record reinstates the
    leak with `render.py` untouched. This is a doc-text assertion, weak in
    general, but here the doc is the program.
    """
    step_4 = _skill_md_step(4)
    assert RENDERER_INVOCATION in step_4, (
        f"SKILL.md step 4 no longer runs the renderer; expected the literal "
        f"{RENDERER_INVOCATION!r} in:\n{step_4}"
    )
    fenced = re.findall(r"```[a-z]*\n(.*?)```", step_4, flags=re.DOTALL)
    assert any(RENDERER_INVOCATION in block for block in fenced), (
        "the renderer invocation must stay inside a fenced code block so it is "
        "copy-pasteable, not buried in prose"
    )


def test_skill_md_names_a_renderer_path_that_resolves_on_disk():
    """The path step 4 names must exist, and be the module the tests exercise.

    This is the half that fires on a renamed or moved renderer rather than
    on a prose bypass: SKILL.md can go stale silently otherwise, and a
    stale instruction is a broken instruction.
    """
    step_4 = _skill_md_step(4)
    match = re.search(r"python3\s+(\S+render\.py)", step_4)
    assert match is not None, f"no renderer path found in SKILL.md step 4:\n{step_4}"

    named = REPO_ROOT / match.group(1)
    assert named.is_file(), f"SKILL.md step 4 names {named}, which does not exist"
    assert named.resolve() == RENDER_MODULE_PATH.resolve(), (
        f"SKILL.md step 4 names {named}, but the module under test is "
        f"{RENDER_MODULE_PATH}"
    )


def test_skill_md_has_no_unnegated_self_composition_instruction():
    """No sentence may tell the agent to build the block itself.

    Backstop to the two checks above, for a mutation that leaves the
    fenced invocation in place and adds a competing instruction beside it.
    Heuristic by nature: it requires every sentence mentioning "yourself"
    to also carry a negation, which is the shape the existing "never by
    composing it yourself" instruction already has.
    """
    offenders = [
        sentence
        for sentence in _sentences(_skill_md_text())
        if _SELF_COMPOSE_RE.search(sentence) and not _NEGATION_RE.search(sentence)
    ]
    assert not offenders, (
        f"SKILL.md appears to instruct composing the paste block by hand: {offenders}"
    )


def test_skill_md_never_instructs_putting_operator_content_in_the_block():
    """No sentence may pair an operator-only field with an insertion verb.

    The existing "Do not append, inline, or otherwise relay any
    `operator_notes` content into the pasted block" sentence passes because
    it is negated. A sentence saying to include
    `operator_notes.expected_observations` does not.
    """
    offenders = [
        sentence
        for sentence in _sentences(_skill_md_text())
        if _OPERATOR_FIELD_RE.search(sentence)
        and _INSERTION_VERB_RE.search(sentence)
        and not _NEGATION_RE.search(sentence)
    ]
    assert not offenders, (
        f"SKILL.md appears to instruct relaying operator-only content: {offenders}"
    )
