"""Tests for the naive-ux-check scenario data file and its paste-block renderer.

`scenarios.json` (`.claude/skills/naive-ux-check/scenarios.json`) is the
single source of truth for the 17 naive-user comprehension scenarios
(K0-K4, G0-G7, A0-A3; task D2a). `render.py`
(`.claude/skills/naive-ux-check/render.py`) is the single composer of the
block a human pastes into the Claude-for-Chrome extension: SKILL.md step 4
runs it rather than composing the block itself, so this module imports and
exercises the actual module the skill executes, not a test-local stand-in.

Three properties matter enough to be enforced by structure rather than by a
human reading SKILL.md's instructions:

1. Every scenario round-trips: all required fields are present and
   non-empty, and the id set is exactly the expected 17 with no
   duplicates.
2. Operator-only content (`operator_notes`: operator setup lines, operator
   notes, persona context, and expected-observations paragraphs) can never
   reach the block that gets pasted into the model. SKILL.md says twice,
   emphatically, that a prompt leaking its own expected observations tests
   transcription, not comprehension, so every verdict downstream of a leak
   would be worthless.
3. SKILL.md step 4 keeps running `render.py`, and its stdout is what the
   checks below actually observe. SKILL.md is the program an agent
   executes when it invokes this skill, so an edit that drops the renderer
   invocation and tells the agent to compose the block by hand is a live
   path to the leak, no matter how safe `render.py` itself is. The same
   goes for `main()`: `render_paste_block` is a function nobody pastes,
   and stdout is the artifact, so the CLI is exercised directly rather
   than trusted to be a thin wrapper.

Property 2 is pinned by two generic checks that never rebuild the block:

* a **narrowing** check, that a record stripped to `id` plus the three
  model-facing fields renders byte-identically to the real record, so
  nothing outside those three is *read*; and
* a **sentinel** check, that replacing every string leaf outside those
  three fields with a unique `__LEAK_n__` marker leaves no marker in the
  output, so nothing outside those three is *emitted*. The markers are
  generated by tree-walk rather than by naming fields, so the check
  survives schema growth: a sub-key added under `operator_notes`, or a
  brand-new top-level field, gets a marker without anyone editing this
  file.

The block's *shape* is pinned separately, by hand-transcribed golden blocks
for K0, G4 and A1. An earlier revision compared the render against a
reference function that rebuilt the same f-string from the same three
fields; that reference was a line-for-line clone of the composer, so the
two moved together and the suite pinned nothing about the format. A golden
has to be re-transcribed by a human when the format changes, which is
exactly the friction that was missing.

One claim an earlier revision of this docstring got wrong, corrected here:
a brand-new top-level field in `scenarios.json` is **not** caught merely by
existing. Adding one with the renderer untouched changes no output and
fails nothing, which is correct: an unread field is not a leak. What is
caught is a *leak through* such a field, that is, a field the composer has
also been changed to read. The sentinel check catches that generically, and
the narrowing check makes the composer raise `KeyError` the moment it reads
anything the stripped record does not carry.

The SKILL.md checks come in two strengths, and the difference matters when
reading a green suite:

* **Structural**, and therefore complete for what they claim: step 4 must
  contain the literal renderer invocation inside a fenced block; every
  `python3 <path>` invocation anywhere in SKILL.md must resolve to a file
  on disk; and step 4 may name an operator-only field only in the exact
  sentences grandfathered in `_STEP_4_OPERATOR_FIELD_SENTENCES`, fenced
  templates included. A new occurrence anywhere in step 4 fails, and the
  grandfather list is a ratchet that can only shrink.
* **Tripwires**, and therefore incomplete by construction: the two
  prose checks that look for an instruction to hand-compose the block or
  to relay operator content into it. They match a finite list of English
  verbs against rough sentence splits. They catch the ordinary phrasings
  a maintainer or an agent would actually reach for, which is worth
  having, but no verb list is closed and no negation heuristic is
  airtight. Read a pass from them as "no common phrasing of the
  instruction is present", never as "the leak cannot be reinstated in
  prose". Prose is not a language a test can fully police; the structural
  checks above are what actually hold the line.

What none of this defends against, stated plainly rather than left to be
discovered: operator-style text written straight into `persona_text`,
`task_text`, or `report_back_questions` reaches the model, because those
three fields are model-facing by design. The operator/model split is a
boundary between fields, not a classifier of content, so keeping "what the
operator should notice" out of those three is an authoring convention, not
a control any test here can enforce.
"""

from __future__ import annotations

import importlib.util
import itertools
import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

if TYPE_CHECKING:
    from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILL_DIR = REPO_ROOT / ".claude" / "skills" / "naive-ux-check"
SCENARIOS_PATH = SKILL_DIR / "scenarios.json"
RENDER_MODULE_PATH = SKILL_DIR / "render.py"
SKILL_MD_PATH = SKILL_DIR / "SKILL.md"

# The exact command SKILL.md step 4 must keep telling the agent to run. Repo
# relative, because that is how the step is written and how a user pastes it.
RENDERER_INVOCATION = "python3 .claude/skills/naive-ux-check/render.py"

# Not a real target; only used to exercise the <URL> substitution the
# renderer performs. Never resolved to a live host.
_TEST_URL = "https://example.invalid/"

# This test module's own statement of which scenario fields are model-facing,
# written out here rather than imported from `render.py`. Importing the
# production tuple would make both sides move together, which is the failure
# this file already made once. It is deliberately NOT asserted to equal
# `render_module.MODEL_FACING_FIELDS`: pinning the constant's contents is
# decoration. It is used to build the stripped and sentinel-bearing records
# below, so a composer that reads a fourth field fails behaviourally.
_MODEL_FACING_FIELD_NAMES = ("persona_text", "task_text", "report_back_questions")

EXPECTED_IDS = (
    [f"K{i}" for i in range(5)]
    + [f"G{i}" for i in range(8)]
    + [f"A{i}" for i in range(4)]
)

REQUIRED_FIELDS = (
    "id",
    "persona",
    "name",
    "persona_text",
    "task_text",
    "report_back_questions",
    "requires_credentials",
    "production_safe",
    "operator_notes",
)

MUTATING_SCENARIO_IDS = frozenset({"G4", "G5", "G6", "A2", "A3"})

PREFIX_TO_PERSONA = {"K": "kid", "G": "guardian", "A": "admin"}


def _load_scenarios() -> list[dict[str, Any]]:
    return json.loads(SCENARIOS_PATH.read_text(encoding="utf-8"))


def _load_render_module() -> ModuleType:
    """Import the real `render.py` the skill executes, by file path.

    `.claude/skills/naive-ux-check/` is not a Python package (it is a
    Claude Code skill directory, not part of `src/cyo_adventure`), so this
    loads the module directly from its path rather than via a package
    import. This is the module under test for the leak property: there is
    exactly one paste-block composer in the repository, and this is it.
    """
    spec = importlib.util.spec_from_file_location(
        "naive_ux_check_render", RENDER_MODULE_PATH
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load render module from {RENDER_MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


render_module = _load_render_module()


# ---------------------------------------------------------------------------
# Golden paste blocks. Hand-transcribed from `scenarios.json` against the
# shape SKILL.md step 4 documents, NOT computed from the record. If the
# format changes, these must be retyped by a person; that friction is the
# point.
#
# What the three goldens actually cover, counted against `scenarios.json`
# rather than asserted from memory: K0 is the non-credentialed
# production-safe scenario, and the only golden carrying operator content
# that states the answer (`operator_setup` 1 line, `expected_observations`
# 1 line). G4 is a mutating guardian scenario whose `operator_notes` is
# entirely EMPTY, all four sub-keys `[]`; it covers the mutating-scenario
# shape, not operator content. A1 is the only scenario in the file carrying
# `operator_notes.persona_context` (1 line).
#
# So no golden covers a populated `operator_note`; K1, K2, K4 and G1 are the
# scenarios that have one. A leak confined to that sub-key would be caught
# by the sentinel and narrowing checks below, which walk every scenario, and
# not by any golden. Do not read this set as four-sub-key coverage.
# ---------------------------------------------------------------------------

GOLDEN_K0 = (
    "Persona: You are a 7-year-old who was just handed a brand-new tablet. Nobody in your family has used this app on it before, and no grown-up is nearby right now.\n"
    "\n"
    "Task: Go to https://example.invalid/ and try to start reading a story, using only what's on the screen.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What you clicked, in order, and why at each step.\n"
    "2. What the screen told you when you couldn't go any further, in your own words.\n"
    "3. Whether that screen felt friendly and clear about what to do next, or like something was broken.\n"
    '4. Whether you knew what to do next (even if it was "go find a grown-up"), or felt stuck.'
)

GOLDEN_G4 = (
    "Persona: You are a parent who just approved your child's story idea.\n"
    "\n"
    "Task: Go to https://example.invalid/, sign in, find your child's pending story request, and approve it. Then figure out whether there's anything else you still need to do before your child can actually read the story.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What happened right after you approved the request.\n"
    "2. Whether anything told you a second review step exists before the story reaches your child.\n"
    "3. If you had to go looking for that second step, how you found it.\n"
    "4. Whether you'd have assumed you were done after the first approval."
)

GOLDEN_A1 = (
    "Persona: You were just told you're an admin on this app, with no other explanation of what that means.\n"
    "\n"
    "Task: Go to https://example.invalid/, sign in, and try to figure out what, if anything, you can do that a regular parent account couldn't.\n"
    "\n"
    "Report back:\n"
    "\n"
    "1. What, if anything, looked different from what you'd expect a parent account to see.\n"
    "2. Whether you found any action that felt admin-specific.\n"
    '3. How confident you are that you have elevated capability at all, on a scale of "certain" to "no idea."\n'
    "4. What you would look for next if you still weren't sure."
)

GOLDEN_BLOCKS = {"K0": GOLDEN_K0, "G4": GOLDEN_G4, "A1": GOLDEN_A1}


def _sentinelize(scenario: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    """Copy `scenario`, replacing every string leaf outside the three fields.

    Walks dicts and lists recursively instead of naming today's
    `operator_notes` sub-keys, so a field added anywhere in the schema
    later is sentinel-marked automatically. `id` is marked too, and the
    marked id is what the caller renders by, which is why the eight
    scenarios with entirely empty `operator_notes` (G2-G7, A2, A3) still
    exercise this check.
    """
    counter = itertools.count(1)
    sentinels: list[str] = []

    def walk(node: Any) -> Any:
        if isinstance(node, str):
            marker = f"__LEAK_{next(counter)}__"
            sentinels.append(marker)
            return marker
        if isinstance(node, dict):
            return {key: walk(value) for key, value in node.items()}
        if isinstance(node, list):
            return [walk(item) for item in node]
        return node

    marked = {
        key: value if key in _MODEL_FACING_FIELD_NAMES else walk(value)
        for key, value in scenario.items()
    }
    return marked, sentinels


def _write_scenarios(tmp_path: Path, records: list[dict[str, Any]]) -> Path:
    path = tmp_path / "scenarios.json"
    path.write_text(json.dumps(records), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# SKILL.md text helpers. SKILL.md is the program an agent runs, so its step 4
# is checked the way a program is checked.
# ---------------------------------------------------------------------------

_NEGATION_RE = re.compile(r"\b(never|not|avoid|without)\b", re.IGNORECASE)
_SELF_COMPOSE_RE = re.compile(r"\byourself\b", re.IGNORECASE)
_OPERATOR_FIELD_RE = re.compile(
    r"operator_notes|operator_setup|operator_note|persona_context"
    r"|expected_observations",
    re.IGNORECASE,
)
# Verbs that would put operator content INTO the block.
#
# Deliberately EXCLUDES "relay" and "paste": step 4 legitimately uses both for
# telling the operator things out of band, outside the pasted text. Also
# excludes "list", which in this document is overwhelmingly a noun about the
# JSON schema ("an object with ... `[]`") rather than an imperative, so
# including it would trip on schema prose and pressure a maintainer into
# weakening this check.
#
# Suffixes are enumerated rather than left as `\w*` where the bare stem is a
# prefix of an unrelated common word: `add\w*` would match "address" and
# "additional".
_INSERTION_VERB_RE = re.compile(
    r"\b("
    r"add|adds|added|adding"
    r"|append\w*|prepend\w*"
    r"|inline\w*|includ\w*|embed\w*|insert\w*|attach\w*"
    r"|put|puts|putting"
    r"|supply|supplies|supplied|supplying"
    r"|quote|quotes|quoted|quoting"
    r"|reproduce|reproduces|reproduced|reproducing"
    r"|copy|copies|copying"
    r"|pass along|passes along|passed along|passing along"
    r")\b",
    re.IGNORECASE,
)
# Double-negative constructions that turn a negation into an order. "Do not
# forget to append X" carries a negation token while being an unambiguous
# instruction to append X, so a negation in the same sentence as one of these
# must not exempt anything.
_NEGATION_REVERSAL_RE = re.compile(
    r"\b(forget\w*|fail|fails|failing|omit\w*|neglect\w*|skip\w*|hesitat\w*)\b",
    re.IGNORECASE,
)
# How far before a risky token a negation may sit and still be read as
# governing it. Bounded so that a negation elsewhere in a long sentence does
# not silently exempt a clause it has nothing to do with.
_NEGATION_WINDOW = 60

# Any `python3 <something>.py` command anywhere in SKILL.md, not only the
# renderer. A second fenced command naming a script that does not exist is a
# live instruction to run and paste unknown output.
_PYTHON3_INVOCATION_RE = re.compile(r"\bpython3\s+(\S+\.py)")

# Every sentence of SKILL.md step 4 that legitimately names an operator-only
# field, verbatim as `_sentences` yields it. Step 4 has to name these fields in
# order to tell the operator to keep them OUT of the pasted block, so the check
# below cannot simply ban the names; it grandfathers exactly these three and
# fails on any fourth, prose or fenced template alike. Both directions are
# asserted, so this list can only ever shrink: deleting one of these sentences
# from SKILL.md is also a failure.
_STEP_4_OPERATOR_FIELD_SENTENCES = (
    (
        "it never reads `operator_notes` (`operator_setup`, `operator_note`, "
        "`persona_context`, or `expected_observations`), by construction."
    ),
    (
        "Do not append, inline, or otherwise relay any `operator_notes` content "
        "into the pasted block itself;"
    ),
    (
        "Where `operator_notes.operator_setup` is non-empty, relay it to the user "
        "before they paste (it covers things like starting from a signed-out "
        "browser or signing in first)."
    ),
)


def _skill_md_text() -> str:
    return SKILL_MD_PATH.read_text(encoding="utf-8")


def _skill_md_step(number: int) -> str:
    """Return the text of one top-level numbered step of SKILL.md.

    Steps start at column 0 as `N. `; their continuation lines are
    indented. Returns everything from that marker up to the next
    column-0 numbered step or the next `## ` heading.
    """
    lines = _skill_md_text().splitlines()
    start = next(
        (i for i, line in enumerate(lines) if line.startswith(f"{number}. ")), None
    )
    assert start is not None, f"SKILL.md has no step {number}"
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if re.match(r"^\d+\. ", lines[i]) or lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def _sentences(text: str) -> list[str]:
    """Unwrap markdown line wrapping and split into rough sentences.

    Splits on `.`, `:`, `;`, `!` and `?` followed by whitespace. Rough is
    fine: the checks below only ask whether a negation sits in the same
    sentence as a risky instruction, and over-splitting makes them
    stricter, never laxer.
    """
    flat = re.sub(r"\s+", " ", text)
    return [part for part in re.split(r"(?<=[.:;!?])\s+", flat) if part.strip()]


def _negation_governs(sentence: str, target: re.Match[str]) -> bool:
    """Is `target` inside this sentence actually negated?

    Two conditions, both necessary, replacing the earlier "a negation token
    appears somewhere in the sentence" rule. That rule was inverted for
    imperatives: "Do not forget to append X" and "compose it yourself if
    the renderer is not available" both carry a negation token while being
    plain instructions to do the thing.

    1. The negation must PRECEDE the target, within `_NEGATION_WINDOW`
       characters. A negation after the target, or far away at the other
       end of a long sentence, governs a different clause.
    2. The sentence must carry no `_NEGATION_REVERSAL_RE` word. "Do not
       forget", "do not omit", "never fail to" are double negatives: the
       negation is there, and the sentence still says to do it.

    This is a heuristic and is documented as one wherever it is used. It
    is deliberately biased towards flagging: a false positive is a loud,
    one-line fix, whereas a false negative is a silent leak.

    Args:
        sentence: the whole rough sentence the target was found in.
        target: the match object for the risky token, from a search over
            that same sentence.

    Returns:
        True when the target may be treated as negated and skipped.
    """
    if _NEGATION_REVERSAL_RE.search(sentence):
        return False
    window_start = max(0, target.start() - _NEGATION_WINDOW)
    # `pos`/`endpos` rather than a slice: Python keeps the real surrounding
    # characters in view for `\b`, so a window boundary landing mid-word
    # cannot manufacture a "not" out of "cannot".
    return _NEGATION_RE.search(sentence, window_start, target.start()) is not None


def _self_composition_offenders(text: str) -> list[str]:
    """Sentences instructing the reader to compose the paste block itself.

    Extracted from the tripwire test so that test and its positive control
    run the SAME detector over different text. A control that re-implements
    the loop would prove something about the control, not about the code
    the real test calls.

    Args:
        text: Prose to scan, sentence-split by :func:`_sentences`.

    Returns:
        Every sentence whose self-composition token is not governed by a
        negation, in sentence order.
    """
    offenders: list[str] = []
    for sentence in _sentences(text):
        match = _SELF_COMPOSE_RE.search(sentence)
        if match is not None and not _negation_governs(sentence, match):
            offenders.append(sentence)
    return offenders


def _operator_relay_offenders(text: str) -> list[str]:
    """Sentences pairing an operator-only field with an insertion verb.

    Extracted for the same reason as :func:`_self_composition_offenders`:
    the tripwire and its positive control must exercise one detector.

    Args:
        text: Prose to scan, sentence-split by :func:`_sentences`.

    Returns:
        Every sentence naming an operator-only field alongside at least one
        insertion verb that no negation governs, in sentence order and
        without duplicates.
    """
    offenders: list[str] = []
    for sentence in _sentences(text):
        if not _OPERATOR_FIELD_RE.search(sentence):
            continue
        for verb in _INSERTION_VERB_RE.finditer(sentence):
            if not _negation_governs(sentence, verb):
                offenders.append(sentence)
                break
    return offenders


# ---------------------------------------------------------------------------
# Round-trip: every one of the 17 scenarios has every required field,
# non-empty, and the id set is exactly right with no duplicates.
# ---------------------------------------------------------------------------


def test_scenario_ids_are_exactly_the_expected_17_with_no_duplicates():
    scenarios = _load_scenarios()
    ids = [s["id"] for s in scenarios]
    assert len(ids) == 17, f"expected 17 scenarios, found {len(ids)}: {ids}"
    assert len(ids) == len(set(ids)), "duplicate scenario ids in scenarios.json"
    assert set(ids) == set(EXPECTED_IDS), (
        f"id set mismatch: missing={set(EXPECTED_IDS) - set(ids)}, "
        f"unexpected={set(ids) - set(EXPECTED_IDS)}"
    )
    # Array order is the selection order SKILL.md relies on: K0-K4, G0-G7,
    # A0-A3, with each persona's auth-gate scenario first in its group.
    assert ids == EXPECTED_IDS


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_scenario_has_all_required_fields_non_empty(scenario: dict[str, Any]):
    for field in REQUIRED_FIELDS:
        assert field in scenario, f"{scenario.get('id', '?')} missing field {field!r}"

    assert scenario["id"].strip()
    assert scenario["name"].strip()
    assert scenario["persona_text"].strip()
    assert scenario["task_text"].strip()
    assert scenario["persona"] in ("kid", "guardian", "admin")
    assert isinstance(scenario["requires_credentials"], bool)
    assert isinstance(scenario["production_safe"], bool)

    questions = scenario["report_back_questions"]
    assert isinstance(questions, list)
    assert len(questions) > 0
    assert all(isinstance(q, str) and q.strip() for q in questions)

    assert isinstance(scenario["operator_notes"], dict)


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_persona_field_matches_id_prefix(scenario: dict[str, Any]):
    expected_persona = PREFIX_TO_PERSONA[scenario["id"][0]]
    assert scenario["persona"] == expected_persona


def test_credential_and_production_safety_posture_is_unchanged():
    """D2a records these facts; it must not loosen them.

    Per SKILL.md: only K0 (the fresh-device auth-gate scenario) is
    non-credentialed and production-safe. Every other scenario either
    signs in with staging-only seeded credentials or mutates content.
    """
    scenarios = {s["id"]: s for s in _load_scenarios()}
    assert scenarios["K0"]["production_safe"] is True
    assert scenarios["K0"]["requires_credentials"] is False
    for sid, scenario in scenarios.items():
        if sid == "K0":
            continue
        assert scenario["production_safe"] is False, (
            f"{sid} must not be production_safe"
        )
        assert scenario["requires_credentials"] is True, (
            f"{sid} must require credentials"
        )

    for sid in MUTATING_SCENARIO_IDS:
        assert scenarios[sid]["production_safe"] is False


def test_a1_persona_context_gives_the_dropped_admin_premise_a_home():
    """Minor 5: admin.md's premise paragraph must live somewhere, not nowhere.

    D2a's migration dropped admin.md's substantive preamble (admins reuse
    every /guardian/* route; the distinguishing signals are the muted
    "Admin" hint, the absent "Books" link, the cross-family picker, and the
    moderation nav) with no replacement home. It is the stated premise of
    A1 ("indistinguishable surface"), so it now lives in
    `A1.operator_notes.persona_context`, an operator-only field alongside
    `operator_setup`/`operator_note`/`expected_observations`. This pins
    that it stays populated, not merely present.
    """
    scenarios = {s["id"]: s for s in _load_scenarios()}
    persona_context = scenarios["A1"]["operator_notes"]["persona_context"]
    assert isinstance(persona_context, list)
    assert persona_context, "A1 persona_context must not be empty"
    assert all(isinstance(text, str) and text.strip() for text in persona_context)


# ---------------------------------------------------------------------------
# Shape: hand-transcribed goldens. Nothing here recomputes the format.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scenario_id", sorted(GOLDEN_BLOCKS))
def test_golden_paste_block_is_rendered_verbatim(scenario_id: str):
    """The render must equal a block a human typed out, character for character.

    If this fails after a deliberate format change, retype the golden from
    `scenarios.json` and SKILL.md step 4's documented shape. Do not
    regenerate it from `render.py`: a computed reference is what the
    previous revision had, and it moved in lockstep with the composer.
    """
    rendered = render_module.render_paste_block(scenario_id, _TEST_URL)
    assert rendered == GOLDEN_BLOCKS[scenario_id]


# ---------------------------------------------------------------------------
# The leak property: nothing outside the three model-facing fields is read,
# and nothing outside them is emitted.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_render_reads_nothing_beyond_the_three_model_facing_fields(
    scenario: dict[str, Any], tmp_path: Path
):
    """A record stripped to the three fields renders identically to the real one.

    Narrowing check. If a future edit makes the composer read a fourth
    field, the stripped record raises `KeyError` here. If the composer
    starts reading something it happens to find on the real record, the two
    renders diverge. Either way this goes red without anyone having to
    anticipate which field.
    """
    stripped = {"id": scenario["id"]} | {
        field: scenario[field] for field in _MODEL_FACING_FIELD_NAMES
    }
    stripped_path = _write_scenarios(tmp_path, [stripped])

    from_stripped = render_module.render_paste_block(
        scenario["id"], _TEST_URL, scenarios_path=stripped_path
    )
    from_real = render_module.render_paste_block(scenario["id"], _TEST_URL)
    assert from_stripped == from_real


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_no_sentinel_from_outside_the_three_fields_reaches_the_render(
    scenario: dict[str, Any], tmp_path: Path
):
    """Every string leaf outside the three model-facing fields must stay out.

    Sentinel check. The markers are generated by walking the record, so a
    sub-key added under `operator_notes` later, or a brand-new top-level
    field, is covered with no edit here. Substituting markers rather than
    searching for the operator's real prose also removes the
    false-positive risk that operator text shares short substrings with
    the task text.
    """
    marked, sentinels = _sentinelize(scenario)
    assert sentinels, f"{scenario['id']}: no string leaves outside the three fields"
    marked_path = _write_scenarios(tmp_path, [marked])

    rendered = render_module.render_paste_block(
        marked["id"], _TEST_URL, scenarios_path=marked_path
    )
    leaked = [marker for marker in sentinels if marker in rendered]
    assert not leaked, f"{scenario['id']}: operator content reached the block: {leaked}"


def test_sentinel_check_would_catch_an_actual_leak(tmp_path: Path):
    """Proves the sentinel check above is not vacuous.

    Renders a sentinel-marked K0, then appends its marked `operator_notes`
    to the output the way a leaking composer would, and confirms the same
    detector fires. Without this, a sentinel check that never sees a
    positive is indistinguishable from one whose markers never appear
    anywhere.
    """
    k0 = next(s for s in _load_scenarios() if s["id"] == "K0")
    marked, sentinels = _sentinelize(k0)
    marked_path = _write_scenarios(tmp_path, [marked])

    rendered = render_module.render_paste_block(
        marked["id"], _TEST_URL, scenarios_path=marked_path
    )
    leaky = rendered + "\n\n" + json.dumps(marked["operator_notes"])

    assert not [marker for marker in sentinels if marker in rendered]
    assert [marker for marker in sentinels if marker in leaky], (
        "the detector found nothing in a deliberately leaky block, so it would "
        "not have caught a real leak either"
    )


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_no_literal_url_placeholder_survives_into_the_render(
    scenario: dict[str, Any],
):
    rendered = render_module.render_paste_block(scenario["id"], _TEST_URL)
    assert "<URL>" not in rendered, (
        f"{scenario['id']}: an unsubstituted <URL> reached the paste block"
    )
    assert _TEST_URL in rendered, f"{scenario['id']}: the target URL never appeared"


def test_every_url_placeholder_in_both_substituted_fields_is_replaced(tmp_path: Path):
    """Repeated and cross-field `<URL>` placeholders must all be substituted.

    The 17 real scenarios each carry exactly one `<URL>`, in `task_text`,
    so they cannot distinguish "replaces every occurrence in both fields"
    from "replaces the first occurrence in `task_text`". This synthetic
    record can.
    """
    synthetic = {
        "id": "SYNTH",
        "persona_text": "persona head <URL> persona tail <URL>",
        "task_text": "task head <URL> task tail <URL>",
        "report_back_questions": ["first question.", "second question."],
    }
    synthetic_path = _write_scenarios(tmp_path, [synthetic])

    rendered = render_module.render_paste_block(
        "SYNTH", _TEST_URL, scenarios_path=synthetic_path
    )
    assert "<URL>" not in rendered
    assert rendered.count(_TEST_URL) == 4, (
        f"expected 4 substitutions, got {rendered.count(_TEST_URL)}: {rendered!r}"
    )


# ---------------------------------------------------------------------------
# The CLI is the artifact. Everything above tests `render_paste_block`, which
# is a function nobody pastes; SKILL.md step 4 runs the module and says its
# stdout is the block to paste, verbatim. Until stdout itself is observed, a
# `main()` that prints the block and then prints the answer key underneath it
# passes every leak check in this file.
# ---------------------------------------------------------------------------


def _non_model_facing_string_leaves(scenario: dict[str, Any]) -> list[str]:
    """Every string leaf of `scenario` outside the three model-facing fields.

    Same tree-walk as `_sentinelize`, without the substitution: used to
    search real operator prose in real CLI output, where a sentinel-bearing
    `scenarios.json` cannot be substituted because `main()` takes no path
    override.
    """
    found: list[str] = []

    def walk(node: Any) -> None:
        if isinstance(node, str):
            found.append(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    for key, value in scenario.items():
        if key not in _MODEL_FACING_FIELD_NAMES:
            walk(value)
    return found


# Below this length a scenario's non-model-facing strings are ids and one-word
# persona labels ("K0", "kid"), which collide with ordinary block text. The
# real operator lines in `scenarios.json` are 18 characters and up, so this
# threshold separates the two cleanly with room to spare.
_LEAK_SEARCH_MIN_LENGTH = 12


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_cli_stdout_is_exactly_the_paste_block(scenario: dict[str, Any], capsys):
    """`main()`'s stdout must be the composed block and nothing else.

    Byte equality is the whole point: it transitively inherits every
    property the checks above prove about `render_paste_block`, and it
    fails on anything appended, prepended, or interleaved. A `main()` that
    prints the block and then prints `operator_notes.expected_observations`
    underneath is exactly the leak SKILL.md forbids, and it is invisible to
    a suite that only calls the composer.
    """
    exit_code = render_module.main([scenario["id"], _TEST_URL])
    captured = capsys.readouterr()

    assert exit_code == 0, f"{scenario['id']}: CLI exited {exit_code}"
    assert captured.err == "", (
        f"{scenario['id']}: CLI wrote to stderr: {captured.err!r}"
    )
    expected = render_module.render_paste_block(scenario["id"], _TEST_URL) + "\n"
    assert captured.out == expected


@pytest.mark.parametrize("scenario", _load_scenarios(), ids=lambda s: s["id"])
def test_no_operator_content_reaches_cli_stdout(scenario: dict[str, Any], capsys):
    """No operator string from the record may appear in what the human pastes.

    The sentinel walk of the checks above, aimed at real CLI output. It
    searches the record's actual operator prose rather than substituted
    markers, because `main()` reads `SCENARIOS_PATH` and takes no override,
    so there is no sentinel-bearing file to point it at. Strings shorter
    than `_LEAK_SEARCH_MIN_LENGTH` are skipped to keep ids and persona
    labels from matching ordinary block text.
    """
    assert render_module.main([scenario["id"], _TEST_URL]) == 0
    stdout = capsys.readouterr().out

    searchable = [
        text
        for text in _non_model_facing_string_leaves(scenario)
        if len(text) >= _LEAK_SEARCH_MIN_LENGTH
    ]
    leaked = [text for text in searchable if text in stdout]
    assert not leaked, f"{scenario['id']}: operator content reached stdout: {leaked}"


def test_cli_rejects_a_wrong_argument_count(capsys):
    """Two arguments exactly; anything else is a usage error on stderr."""
    for argv in ([], ["K0"], ["K0", _TEST_URL, "extra"]):
        assert render_module.main(argv) == 2, f"argv {argv!r} should be a usage error"
        captured = capsys.readouterr()
        assert captured.out == "", f"argv {argv!r} printed to stdout: {captured.out!r}"
        assert "usage:" in captured.err


def test_cli_rejects_an_unknown_scenario_id(capsys):
    """An unknown id exits 1 and prints nothing to stdout.

    Printing a partial or empty block on a typo'd id would be worse than
    failing: the operator pastes whatever appeared.
    """
    assert render_module.main(["NOPE", _TEST_URL]) == 1
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "NOPE" in captured.err


# ---------------------------------------------------------------------------
# SKILL.md is the program: step 4 must keep running the renderer.
# ---------------------------------------------------------------------------


def test_skill_md_step_4_invokes_the_renderer():
    """Step 4 must contain the literal renderer invocation, in a fenced block.

    A safe `render.py` buys nothing if SKILL.md stops calling it. An agent
    invoking this skill reads step 4 and does what it says, so rewriting
    step 4 to compose the block from the scenario record reinstates the
    leak with `render.py` untouched. This is a doc-text assertion, weak in
    general, but here the doc is the program.
    """
    step_4 = _skill_md_step(4)
    assert RENDERER_INVOCATION in step_4, (
        f"SKILL.md step 4 no longer runs the renderer; expected the literal "
        f"{RENDERER_INVOCATION!r} in:\n{step_4}"
    )
    fenced = re.findall(r"```[a-z]*\n(.*?)```", step_4, flags=re.DOTALL)
    assert any(RENDERER_INVOCATION in block for block in fenced), (
        "the renderer invocation must stay inside a fenced code block so it is "
        "copy-pasteable, not buried in prose"
    )


def test_skill_md_names_a_renderer_path_that_resolves_on_disk():
    """The path step 4 names must exist, and be the module the tests exercise.

    This is the half that fires on a renamed or moved renderer rather than
    on a prose bypass: SKILL.md can go stale silently otherwise, and a
    stale instruction is a broken instruction.
    """
    step_4 = _skill_md_step(4)
    match = re.search(r"python3\s+(\S+render\.py)", step_4)
    assert match is not None, f"no renderer path found in SKILL.md step 4:\n{step_4}"

    named = REPO_ROOT / match.group(1)
    assert named.is_file(), f"SKILL.md step 4 names {named}, which does not exist"
    assert named.resolve() == RENDER_MODULE_PATH.resolve(), (
        f"SKILL.md step 4 names {named}, but the module under test is "
        f"{RENDER_MODULE_PATH}"
    )


def test_every_python3_invocation_in_skill_md_resolves_on_disk():
    """Every `python3 <path>` in SKILL.md must name a file that exists.

    The renderer-path check above resolves only the path its regex matches,
    `\\S+render\\.py`. That leaves a second fenced command free to name
    anything at all: "then run the enrichment step and paste its output
    too", pointing at a script nobody wrote, reads to an agent as a real
    instruction and passes silently. SKILL.md is the program, so every
    command in it is checked, not just the one the suite happens to care
    about.
    """
    text = _skill_md_text()
    named = _PYTHON3_INVOCATION_RE.findall(text)
    assert named, "SKILL.md names no python3 invocation at all"

    missing = [rel for rel in named if not (REPO_ROOT / rel).is_file()]
    assert not missing, (
        f"SKILL.md tells the operator to run scripts that do not exist: {missing}"
    )


def test_step_4_names_operator_fields_only_where_grandfathered():
    """Step 4 may name an operator-only field only in the sentences on the list.

    Structural, not a tripwire: this covers ALL of step 4, fenced blocks
    included, and does not depend on a verb appearing anywhere. A code
    fence documenting the paste block's shape with an
    `OPERATOR EXPECTS: <operator_notes.expected_observations>` slot has no
    verb for the prose guards to match, and an agent handed "paste stdout,
    in the shape: <shape>" plus a shape with a slot stdout does not fill
    has a plain instruction to fill it from the record.

    Step 4 legitimately names these fields while telling the operator to
    keep them out of the block, so the exceptions are grandfathered
    verbatim, and their continued presence is asserted too. The list is a
    ratchet: it can only shrink.
    """
    naming = [s for s in _sentences(_skill_md_step(4)) if _OPERATOR_FIELD_RE.search(s)]

    unexpected = [s for s in naming if s not in _STEP_4_OPERATOR_FIELD_SENTENCES]
    assert not unexpected, (
        "SKILL.md step 4 names an operator-only field somewhere new. If this is "
        "legitimate, say so out loud by adding it to "
        "_STEP_4_OPERATOR_FIELD_SENTENCES; do not delete this check. "
        f"New occurrences: {unexpected}"
    )

    for grandfathered in _STEP_4_OPERATOR_FIELD_SENTENCES:
        assert grandfathered in naming, (
            "a grandfathered step 4 sentence is gone or reworded, so the "
            "exception list no longer describes SKILL.md. Re-verify the "
            "sentence is still safe, then update the list: "
            f"{grandfathered!r}"
        )


def test_skill_md_has_no_unnegated_self_composition_instruction():
    """No sentence may tell the agent to build the block itself.

    Backstop to the checks above, for a mutation that leaves the fenced
    invocation in place and adds a competing instruction beside it.

    This is a TRIPWIRE, not a proof. It keys on the single word
    "yourself", and asks `_negation_governs` whether a negation actually
    precedes it. Passing means "no sentence phrased that way is present",
    which is worth knowing and is not the same as "SKILL.md cannot tell
    the agent to hand-compose the block". Plenty of English says that
    without the word "yourself". The invocation and renderer-path checks
    above are the structural half.
    """
    offenders = _self_composition_offenders(_skill_md_text())
    assert not offenders, (
        f"SKILL.md appears to instruct composing the paste block by hand: {offenders}"
    )


# Synthetic prose for the positive control below. Constructed here and never
# written to SKILL.md: the point is to prove the detector fires, not to put a
# dangerous instruction into the file an agent executes.
_SELF_COMPOSE_POSITIVE = "Then compose the paste block yourself from the record."
_SELF_COMPOSE_REVERSED = "Do not forget to compose the paste block yourself."
_SELF_COMPOSE_NEGATED = "Never compose the paste block yourself."
_SELF_COMPOSE_ABSENT = "Run the renderer and paste its stdout unchanged."


def test_the_self_composition_tripwire_can_actually_fire():
    """Positive control: the tripwire above must be able to produce a hit.

    The tripwire asserts an empty offender list against SKILL.md. That
    assertion holds just as well when the detector is incapable of ever
    matching anything, so on its own it is indistinguishable from a
    detector whose regex was blanked or whose negation check was stubbed
    to always exempt. This is the same reasoning
    `test_sentinel_check_would_catch_an_actual_leak` states for the
    sentinel check.

    Four arms, run through the same `_self_composition_offenders` the
    tripwire calls, so the control proves discrimination rather than only
    that something fires:

    * a plain instruction is flagged;
    * a double-negative instruction ("do not forget to ...") is flagged,
      because its negation token does not make it safe;
    * a genuinely negated prohibition is NOT flagged; and
    * prose that never raises the subject is NOT flagged.
    """
    assert _self_composition_offenders(_SELF_COMPOSE_POSITIVE) == [
        _SELF_COMPOSE_POSITIVE
    ], "the detector did not fire on a plain self-composition instruction"
    assert _self_composition_offenders(_SELF_COMPOSE_REVERSED) == [
        _SELF_COMPOSE_REVERSED
    ], "the detector was fooled by the negation in a double negative"
    assert _self_composition_offenders(_SELF_COMPOSE_NEGATED) == [], (
        "the detector fired on a correctly negated prohibition, so it does "
        "not discriminate and would pressure a maintainer into deleting it"
    )
    assert _self_composition_offenders(_SELF_COMPOSE_ABSENT) == [], (
        "the detector fired on prose that never mentions self-composition"
    )


def test_skill_md_never_instructs_putting_operator_content_in_the_block():
    """No sentence may pair an operator-only field with an insertion verb.

    The existing "Do not append, inline, or otherwise relay any
    `operator_notes` content into the pasted block" sentence passes because
    the negation directly precedes both verbs. "Then add each line of
    `operator_notes.expected_observations` to the end of that stdout" does
    not, and neither does "Do not forget to append ...", whose negation is
    reversed by "forget".

    This is a TRIPWIRE, not a proof. It matches a finite verb list against
    rough sentence splits, and no verb list is closed: a sentence can
    instruct the leak in words nobody enumerated ("the block should end
    with the expected observations"). Read a pass as "no common phrasing
    is present". What actually holds step 4's line is
    `test_step_4_names_operator_fields_only_where_grandfathered`, which
    needs no verb at all.
    """
    offenders = _operator_relay_offenders(_skill_md_text())
    assert not offenders, (
        f"SKILL.md appears to instruct relaying operator-only content: {offenders}"
    )


# Synthetic prose for the positive control below, constructed here for the
# same reason as `_SELF_COMPOSE_POSITIVE`: SKILL.md must never carry a
# working example of the instruction this suite exists to forbid.
_OPERATOR_RELAY_POSITIVE = (
    "Then append each line of `operator_notes.expected_observations` to the "
    "end of that stdout."
)
_OPERATOR_RELAY_REVERSED = (
    "Do not forget to append `operator_notes.expected_observations` to the block."
)
_OPERATOR_RELAY_NEGATED = (
    "Do not append any `operator_notes` content into the pasted block itself."
)
_OPERATOR_RELAY_FIELD_ONLY = "The renderer never reads `operator_notes` at all."
_OPERATOR_RELAY_VERB_ONLY = "Append the target URL to the end of the task text."


def test_the_operator_relay_tripwire_can_actually_fire():
    """Positive control: the tripwire above must be able to produce a hit.

    Same reasoning as `test_the_self_composition_tripwire_can_actually_fire`.
    Blanking `_OPERATOR_FIELD_RE` or `_INSERTION_VERB_RE`, or stubbing
    `_negation_governs` to always exempt, leaves the tripwire green because
    an empty offender list is its passing state; only a text that SHOULD
    trip it can tell the two apart.

    Five arms through the same `_operator_relay_offenders` the tripwire
    calls. The last two are the discrimination arms: this detector must
    fire on the CONJUNCTION of an operator-only field and an insertion
    verb, not on either half alone.
    """
    assert _operator_relay_offenders(_OPERATOR_RELAY_POSITIVE) == [
        _OPERATOR_RELAY_POSITIVE
    ], "the detector did not fire on a plain relay instruction"
    assert _operator_relay_offenders(_OPERATOR_RELAY_REVERSED) == [
        _OPERATOR_RELAY_REVERSED
    ], "the detector was fooled by the negation in a double negative"
    assert _operator_relay_offenders(_OPERATOR_RELAY_NEGATED) == [], (
        "the detector fired on the correctly negated prohibition SKILL.md "
        "actually carries, so it does not discriminate"
    )
    assert _operator_relay_offenders(_OPERATOR_RELAY_FIELD_ONLY) == [], (
        "the detector fired on a sentence naming an operator field with no "
        "insertion verb"
    )
    assert _operator_relay_offenders(_OPERATOR_RELAY_VERB_ONLY) == [], (
        "the detector fired on an insertion verb with no operator field"
    )
